### PR TITLE
ISSUE #2917 password is encoded before log in to allow @ symbol in it

### LINKED ISSUE #2917: Make password fix a hotfix
https://github.com/3drepo/3drepo.io/issues/2814 needs to be applied to master for a hotfix deployment

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #2917

#### Description
Cherry picked 26569045cacc43b6d174d612f3890d1de7608ff8 to master

### CODE REVIEW

**Comment by mosment3DRepo** [comment]
@carmenfan was there an issue with deployment:

image

**Comment by carmenfan** [comment]
@3drepo/devops

**Comment by carmenfan** [comment]
@mosment3DRepo should be available now

**Review by mosment3DRepo — APPROVED** [review]
Edited existing user password and created new user using all the following characters:
```
";,/?:@&=+$";  // Reserved Characters
"-_.!~*'()";   // Unescaped Characters
"#";           // Number Sign
"ABC abc 123"; // Alphanumeric Characters + Space
```

**Pull request merged**
