### PR TITLE
ISSUE #2084 - Make it possible to destroy and reinitialise the viewer

### LINKED ISSUE #2084: Make it possible to destroy and reinitialise the viewer
Unity Introduced the ability to quit the game and destroy it's instance in Unity 2019. We should expose it in unityUtils and allow the user to offload and reload the game.

Rick has hacked around with the minified version to make it work via the embeddable viewer approach. We should take this into and implement it in the typescript file.

Screenshot from 2020-06-18 09-40-14

### PR DESCRIPTION
**Pull request by m1chalkubiak**
This fixes #2084

#### Description
- [x] Add method for quitting the Unity instance 
- [x] Add method for reloading the Unity instance
- [x] Methods should be exposed for users in unityUtil

### CODE REVIEW

**Review by carmenfan — APPROVED** [review]
changed the doc comment slightly, as this is a function we should expose to users.

looks fine

**Comment by m1chalkubiak** [comment]
> changed the doc comment slightly, as this is a function we should expose to users.
> 
> looks fine

Thanks @carmenfan, I wasn't 100% sure about doc part.

**Pull request merged**
