### PR TITLE
Issue 3690 - Viewer Facelift - Sequence

### LINKED ISSUE #3690: Viewer Facelift - Sequences card
### Description
Most of the components in the viewer have been facelifted, but the sequences card doesn't look very nice yet.

### Goals
Sequences card should be facelifted, this should also include the two panels that can be opened by toggling the two toggles.

### Tasks
- [ ] Basic Sequences card;
- [ ] Legend panel;
- [ ] Activity List panel

### Related Resources
image
image

**Note** the toggles are being refactored in #3632 and will eventually look like this
image

Make sure to show the number value here 
image

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #3690

#### Description
The sequence card has been facelifted.

#### Test cases
- Sequence card;
- Legend modal;
- Activities modal;
- Expanded activity

#### Resources
A good model to test the sequence card is the `training building.spm` that can be found at
https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Product/3D%20Models/Synchro/6.4%20SPM

### CODE REVIEW

**Comment by Amantini1997** [comment]
\azp run

**Review by The-Daniel — DISMISSED** [review]

**Review by sanmont3drepo — DISMISSED** [review]

**Comment by george-hadfield** [comment]
### Add a touch extra spacing inbetween input and back and forward arrows

Build
image
 
Design
image

**Comment by george-hadfield** [comment]
### Left align number with 'Step interval' label

image

**Comment by george-hadfield** [comment]
### Left align back arrow with play icon

Currently the back arrow is indented slightly

image

**Comment by george-hadfield** [comment]
### Remove unwanted space to the right of search icon in activity list

image

**Comment by george-hadfield** [comment]
### Left align 'Sequence legend' title correctly

image

**Review by george-hadfield — CHANGES_REQUESTED** [review]
Small tweaks left

**Comment by Amantini1997** [comment]
> ### Remove empty space tp the right of the padlock icon
> image

The floating icon on the top right is because the 2 other icons (`search` and `options`) are hidden. The same happens with the search icon that looks floating. Shall I change this behaviour for all the cards in the viewer?

**Comment by Amantini1997** [comment]
> ### Left align number with 'Step interval' label
> image

The step value can go up to a maximum of 100. When that value is reached, the label and the value are aligned together. If I move the label to the right to align it to the value made of a single digit (e.g. `1`), such a label would not be aligned to all the values with 2 digits. Would you still like me to align the label with right-most digit of the value?

**Comment by The-Daniel** [comment]
> > > ### Remove empty space tp the right of the padlock icon
> > > image
> > 
> > 
> > The floating icon on the top right is because the 2 other icons (`search` and `options`) are hidden. The same happens with the search icon that looks floating. Shall I change this behaviour for all the cards in the viewer?
> 
> If they are hidden can we add logic to ensure the space is removed?

This should be fixed in ISSUE 3822

**Review by george-hadfield — APPROVED** [review]

**Review by The-Daniel — APPROVED** [review]

**Review by sanmont3drepo — APPROVED** [review]

**Pull request merged**
