### PR TITLE
ISSUE #4020 catch unhandled promise rejections and send an notification email

### LINKED ISSUE #4020: Catch error before exit and send notifications
### Description
With node v18 upgrade, they have finally forced exit on an unhandled promise rejection, and it seems like we may have some going on with the handling of model imports.

We should add something to catch any uncaught errors and send a notification to devops so we know to start tracing them and find out what's wrong.

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #4020

#### Description
- tap on the `unhandledRejection` event
- log the error in the log
- send an error notification email before we exit

#### Test cases
- 3drepo.io should function as normal
- unhandled rejections (create a Promise.reject somewhere that gets called) shall result in triggering the new function

### CODE REVIEW

**Review by Charence — APPROVED** [review]

**Review by Charence — CHANGES_REQUESTED** [review]
backend test is failing

**Comment by Charence** [comment]
```
Summary of all failing tests
FAIL tests/v5/unit/processors/users.test.js
  ● processors/users › Reset password token › should reset password token

    TypeError: Cannot read properties of undefined (reading 'name')

      148 | 		'customData.email': 1,
      149 | 		'customData.firstName': 1 });
    > 150 | 	await sendEmail(templates.FORGOT_PASSWORD.name, email, { token: resetPasswordToken.token,
          | 	                                          ^
      151 | 		email,
      152 | 		username,
      153 | 		firstName });

      at Object.<anonymous>.Users.generateResetPasswordToken (src/v5/processors/users.js:150:44)
      at Object.<anonymous> (tests/v5/unit/processors/users.test.js:209:4)

  ● processors/users › Sign up a user › should sign a user up and send verification email (non SSO user)

    TypeError: Cannot read properties of undefined (reading 'name')

      53 | 		});
      54 | 	} else {
    > 55 | 		await sendEmail(templates.VERIFY_USER.name, newUserData.email, {
         | 		                                      ^
      56 | 			token: formattedNewUserData.token,
      57 | 			email: newUserData.email,
      58 | 			firstName: newUserData.firstName,

      at Object.<anonymous>.Users.signUp (src/v5/processors/users.js:55:41)
      at Object.<anonymous> (tests/v5/unit/processors/users.test.js:245:4)
```

**Review by Charence — CHANGES_REQUESTED** [review]
Tests are complaining about coverage

```
 services/mailer                                                     |      80 |       75 |   83.33 |   79.68 |                   
  index.js                                                           |   75.92 |       75 |      80 |   75.47 | 70-93             
  mailer.constants.js                                                |     100 |      100 |     100 |     100 |                   
 services/mailer/templates                                           |   92.75 |    33.33 |      75 |   92.18 |                   
  baseTemplate.js                                                    |     100 |      100 |     100 |     100 |                   
  common.js                                                          |     100 |      100 |     100 |     100 |                   
  errorNotification.js                                               |   71.42 |        0 |       0 |   71.42 | 30-34,39-40       
  forgotPassword.js                                                  |     100 |      100 |     100 |     100 |                   
  systemTemplate.js                                                  |   88.88 |      100 |       0 |   88.88 | 26                
  verifyUser.js                                                      |     100 |      100 |     100 |     100 |                   
```

**Comment by carmenfan** [comment]
@Charence  third time's the charm? 
image

**Review by Charence — APPROVED** [review]

**Pull request merged**
