### PR TITLE
Issue 3910 - v5.0.0 release candidate

### LINKED ISSUE #3910: v5.0.0 release candidate
cutting a release for v5

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #3910

#### Description
contains the following milestones:
- https://github.com/3drepo/3drepo.io/milestone/245
- https://github.com/3drepo/3drepo.io/milestone/246

And additionally: 
- https://github.com/3drepo/3drepo.io/issues/3792
- https://github.com/3drepo/3drepo.io/issues/3926
- https://github.com/3drepo/3drepo.io/issues/3921

### Bugs List

- [x] [BIM card hover over 'Select elements with same parameter value'](https://github.com/3drepo/3drepo.io/pull/3911#issuecomment-1415871646) (Alessandro)
- [ ] [Measurements card: Custom polygonal area ](https://github.com/3drepo/3drepo.io/pull/3911#issuecomment-1415881383) (sebjf)
- [ ] [Measurements card: Length measurement oddities](https://github.com/3drepo/3drepo.io/pull/3911#issuecomment-1415888733) (sebjf)
- [x] [Routing to V4 when already logged in](https://github.com/3drepo/3drepo.io/pull/3911#issuecomment-1415927427) (Santiago)
- [ ] [Measurements card Settings: 'Delete all' button](https://github.com/3drepo/3drepo.io/pull/3911#issuecomment-1415949419) (sebjf)
- [x] [Objects become permanently transparent](https://github.com/3drepo/3drepo.io/pull/3911#issuecomment-1418922615) (sebjf)
- [x] [Diff tool UI gets stuck on loading](https://github.com/3drepo/3drepo.io/pull/3911#issuecomment-1419221636) (sebjf)
- [x] [Existing Toy porject not loading](https://github.com/3drepo/3drepo.io/pull/3911#issuecomment-1419326332) (sebjf)
#### Test cases
Should pass release QA

### CODE REVIEW

**Comment by carmenfan** [comment]
waiting on @keifgwinn to deal with  https://github.com/3drepo/DevOps/issues/522 and https://github.com/3drepo/DevOps/issues/523

**Comment by mosment3DRepo** [comment]
@carmenfan can we azp run this?

**Comment by carmenfan** [comment]
> @carmenfan can we azp run this?

yes

**Comment by carmenfan** [comment]
@mosment3DRepo ready for testing

**Comment by miadibe** [comment]
### Bugs List

- [ ] 1. BIM card hover over 'Select elements with same parameter value'
- [ ] 2. Measurements card: (WIP)

**Comment by miadibe** [comment]
### 1. BIM card hover over 'Select elements with same parameter value'

### Description
Hover over icon 'Select elements with same parameter value' and/or clicking on it generates an unnecessary scroll bar in the bottom of the screen

### Steps to replicate

- Open any model and click on any element
- Open the BIM card
- Hover over icon 'Select elements with same parameter value' or click on it

### Current Behaviour 
- Scroll bar appears, takes 2 seconds to disappear again
- This applies to any field selected in the BIM card

### Expected Behaviour
No UI oddity, no scroll bar to be shown

### Video of the error
https://user-images.githubusercontent.com/56918163/216614515-9a84b52c-1240-484c-bc96-10d8c113f518.mp4

**Comment by miadibe** [comment]
### 2. Measurements card: Custom polygonal area 

### Description
Creating custom polygonal area generates unnecessary lines and does not get deleted unless user zooms in/out

### Steps to replicate
- Create a custom polygonal area 
- Shape oddity happens unless you zoom in/out it reinitialises the actual shape
- Save the custom polygonal area as a measurement then delete it
- Shape stays unless you zoom in/out

###Current behaviour 
Anywhere the cursor moves is currently interpreted as a user input which displays a line.
Delete action is not instant unless user zooms in/out of the screen

### Expected Behaviour
No odd lines to appear. Only create the shape upon clicks rather than cursor navigation. 

### Video of the error
https://user-images.githubusercontent.com/56918163/216616862-e0f1472c-6ab5-4292-9a4e-5ce2b2d691f4.mp4

**Comment by miadibe** [comment]
### 3. Measurements card: Length measurement oddities

### Description
This bug is similar to [Bug 2](https://github.com/3drepo/3drepo.io/pull/3911#issuecomment-1415881383) 
Point-to-point, Ray Cast and Min distance are all length measurements that have this issue. 
- Issue 1: Measurement lines (shape of length) appear in the model but line does not get erased directly when the measurement is deleted from the card.
- Issue 2: Every cursor move is currently interpreted as a visual line generation

### Steps to replicate
- Create a length measurement (any of the 3 mentioned above)
- Multiple lines are drawn unless you zoom in/out it
- Save the measurements then delete them
- Length stays unless you zoom in/out

### Current behaviour 
Anywhere the cursor moves is currently interpreted as a user input which displays a line.
Delete action is not instant unless user zooms in/out of the screen

### Expected Behaviour
No odd lines to appear. Only create the lines upon clicks rather than cursor navigation. 

### Video of the error

**Comment by mosment3DRepo** [comment]
### Routing to V4 when already logged in

### Description
Once a user is already logged in and try to access https://issue-3910.dev.3drepo.io/ again they are taken to the V4 dashboard instead of V5

### Steps to replicate
- Log into https://issue-3910.dev.3drepo.io/
- Open new tab
- Access https://issue-3910.dev.3drepo.io/


### Video of the error

https://user-images.githubusercontent.com/62879582/216624910-749751f5-ff92-4b7d-9dd6-5bcbb9dee3eb.mp4

**Comment by carmenfan** [comment]
> ### 2. Measurements card: Custom polygonal area
> ### Description
> Creating custom polygonal area generates unnecessary lines and does not get deleted unless user zooms in/out
> 
> ### Steps to replicate
> * Create a custom polygonal area
> * Shape oddity happens unless you zoom in/out it reinitialises the actual shape
> * Save the custom polygonal area as a measurement then delete it
> * Shape stays unless you zoom in/out
> 
> ### Current behaviour
> Anywhere the cursor moves is currently interpreted as a user input which displays a line. Delete action is not instant unless user zooms in/out of the screen
> 
> ### Expected Behaviour
> No odd lines to appear. Only create the shape upon clicks rather than cursor navigation.
> 
> ### Video of the error
>  Bug2.Custom.polygonal.area.mp4

@sebjf this is your area i think. Any idea?

**Comment by miadibe** [comment]
@carmenfan I don't have rights to edit your first comment and add more bugs to the list but I'll continue adding them as new comments regardless

**Comment by miadibe** [comment]
4. Measurements card Settings: 'Delete all' button 

### Description 
This is also related to other measurements bugs.
'Delete all' button removes all the measurements from the list **but not the model** unless user zooms in/out

### Expected Behaviour
Instant delete of measurements in both the list **and** the model without having to navigate the model

Refer to [this](https://github.com/3drepo/3drepo.io/pull/3911#issuecomment-1415888733) for full context

**Comment by mosment3DRepo** [comment]
> > ### 2. Measurements card: Custom polygonal area
> > ### Description
> > Creating custom polygonal area generates unnecessary lines and does not get deleted unless user zooms in/out
> > ### Steps to replicate
> > 
> > * Create a custom polygonal area
> > * Shape oddity happens unless you zoom in/out it reinitialises the actual shape
> > * Save the custom polygonal area as a measurement then delete it
> > * Shape stays unless you zoom in/out
> > 
> > ### Current behaviour
> > Anywhere the cursor moves is currently interpreted as a user input which displays a line. Delete action is not instant unless user zooms in/out of the screen
> > ### Expected Behaviour
> > No odd lines to appear. Only create the shape upon clicks rather than cursor navigation.
> > ### Video of the error
> > Bug2.Custom.polygonal.area.mp4
> 
> @sebjf this is your area i think. Any idea?

@miadibe I can't replicate this, can you have another look?

**Comment by miadibe** [comment]
### 5. GIS card: GIS card does not show currently chosen map provider with corresponding layer visibility after reopening card even if map tile are still running

### Description 
This confuses the user who has to refresh browser page and choose again the chosen provider with the different layer visibility. 

### Steps to replicate
- Add GIS coordinates to a model in 3D Repo (if it doesn't have the GIS settings already setup) 
- Go back to maps list, chose any provide from the dropdown (**any but** Open street map default provider)
- Close GIS card, map tiles are still running
- Open GIS card again, provider shown is default and not the latest chosen

### Current behaviour 
User can close GIS card. When user opens GIS card again, map tiles are still running but **don't show the current/chosen provider.** Instead, card always shows default provider Open Street map

### Expected Behaviour
GIS card should always show the current map provider and layer visibility (show/hide) rather than the default maps list

### Video of the error
Uploading Bug 5 - GIS.mp4…

**Comment by Ramadyfm** [comment]
Objects become permanently transparent 

**Description**
When unchecking the color override box for a group that has an assigned color transparency, the object becomes permanently and fully transparent. 


**Steps to replicate**

In the groups card:
Create a new normal group that consists of several walls next to one another
Select a color 
Click on the opacity check box 
Use the slider to select opacity at 20% 
Save (in the color section) 
Save the group 
Return to the groups card and toggle the color override boxes next to the group just created.


**Expected Behaviour**
When unchecking  the color override  box, the transparency should disappear and go back to the original visual of the element

Video of the error

ezgif com-gif-maker

**Comment by carmenfan** [comment]
> Cannot isolate elements in a group hierarchy from a parent color override
> 
> Description The isolate button in the bottom tool bar does not isolate elements with the color override of the parent checked
> 
> Steps to replicate In the groups card: Create 2 new normal group that consists of "::" delimiter with the same parent Check the color override for the parent Click on the isolate button in the bottom tool bar
> 
> Expected Behaviour To be able to isolate the elements that have their parent checked using the isolate button in the bottom tool bar
> 
> Video of the error ezgif com-gif-maker (1) [ ](https://user-images.githubusercontent.com/100203626/216971059-959535e4-746f-4333-a961-7c55117a6208.gif) ezgif com-gif-maker (1) [ ](https://user-images.githubusercontent.com/100203626/216971059-959535e4-746f-4333-a961-7c55117a6208.gif)

That's not how the isolate button works. It isolates highlighted objects, not colour overridden objects

**Comment by mosment3DRepo** [comment]
### Diff tool UI gets stuck on loading

### Description
The Diff tool works fine but the card gets stuck on a loading sign.



### Steps to replicate
- Open a model with multiple revisions (eg. https://issue-3910.dev.3drepo.io/v5/viewer/miaTemp/31b266a0-09d6-11ed-ac45-0515a9eb834d/3c5e2e90-09d6-11ed-9f14-6951a872631a)
- Start a 3D Diff
- See that the Diff works in the 3D view, but the card remains in a loading state and is unresponsive
- Refresh page to get out of it



### Video of the error

https://user-images.githubusercontent.com/62879582/217006240-06a00d0d-f5dd-4a39-942c-861d8222e9ef.mp4

**Comment by mosment3DRepo** [comment]
### Existing Toy project not loading (detail to follow)

### Description
Opening an existing Toy model does not load the 3D geometery

### Steps to replicate
- Open a Sample_Project model eg https://issue-3910.dev.3drepo.io/viewer/carmen/0aa65310-8b36-11ec-85af-83e7a2b2ed1e
- See that the model never loads


### Picture of the error
image

**Comment by carmenfan** [comment]
> ### Existing Toy project not loading (detail to follow)
> ### Description
> Opening an existing Toy model does not load the 3D geometery
> 
> ### Steps to replicate
> * Open a Sample_Project model eg https://issue-3910.dev.3drepo.io/viewer/carmen/0aa65310-8b36-11ec-85af-83e7a2b2ed1e
> * See that the model never loads
> * Open Console, see following error:
> 
> ```
> Bundle carmen.844239a0-00c6-11ec-8d97-41a278fb55fd.89d5580a-3224-4e50-bbab-89d855c320e0 does not have a primitive type. It is likely the metadata is incomplete. {"_id":"89d5580a-3224-4e50-bbab-89d855c320e0","nVertices":0,"nFaces":6019,"nUVChannels":1,"primitive":0,"min":[0.0,0.0,-14380.0],"max":[13580.0,3200.0,0.0]}
> ```
> 
> ### Picture of the error
> image

@sebjf could we make primitive type default to 3? old models prior to 2D line support don't' have this property. alternatively we'd have to do a migration script to add this in

**Comment by sanmont3drepo** [comment]
> **Objects become permanently transparent**
> 
> **Description** When unchecking the color override box for a group that has an assigned color transparency, the object becomes permanently and fully transparent.
> 
> **Steps to replicate**
> 
> In the groups card: Create a new normal group that consists of several walls next to one another Select a color Click on the opacity check box Use the slider to select opacity at 20% Save (in the color section) Save the group Return to the groups card and toggle the color override boxes next to the group just created.
> 
> **Expected Behaviour** When unchecking the color override box, the transparency should disappear and go back to the original visual of the element
> 
> Video of the error
> 
> ezgif com-gif-maker [ ezgif com-gif-maker ](https://user-images.githubusercontent.com/100203626/216958597-b070b5e3-4274-4125-a96d-d3af2f54dda0.gif) [ ](https://user-images.githubusercontent.com/100203626/216958597-b070b5e3-4274-4125-a96d-d3af2f54dda0.gif)

This seems to be a a Unity issue. In the frontend is calling the right function and unity is throwing an error:
image

**Comment by Amantini1997** [comment]
> ### Diff tool UI gets stuck on loading
> ### Description
> The Diff tool works fine but the card gets stuck on a loading sign.
> 
> ### Steps to replicate
> * Open a model with multiple revisions (eg. https://issue-3910.dev.3drepo.io/v5/viewer/miaTemp/31b266a0-09d6-11ed-ac45-0515a9eb834d/3c5e2e90-09d6-11ed-9f14-6951a872631a)
> * Start a 3D Diff
> * See that the Diff works in the 3D view, but the card remains in a loading state and is unresponsive
> * Refresh page to get out of it
> 
> ### Video of the error
>  Diff.mp4

Looks like an issue related to Unity.
Inside the file `unity-util.ts` there is a function (`diffToolLoadComparator`) that gets called after pressing the `compare` button.

This function returns a `Promise` which never gets rejected or resolved, but remains in a `pending` state.
This prevents the diff loader to exit the loading state

**Comment by carmenfan** [comment]
@mosment3DRepo all bugs (besides the measuring tool ones) fixed

**Comment by keifgwinn** [comment]
image
visual settings drop downs have gone a little strange

**Comment by keifgwinn** [comment]
3D Repo vector path is off colour, should be white @george-hadfield to confirm colour code
image

**Comment by george-hadfield** [comment]
> 3D Repo logo in the top left, a vector path is off colour, should be white @george-hadfield to confirm colour code image

Thanks Keif - should be #ffffff

**Review by mosment3DRepo — APPROVED** [review]

**Pull request merged**
