### PR TITLE
Issue 3226 - Viewer Facelift - Measurement card

### LINKED ISSUE #3226: Viewer facelift - Measure Card
### Description
We need to revamp the Measure card to match v5 styles

### Goals
- [ ] To have the Measure card styled like v5 

### Tasks
- [ ] Just follow the styles in the mockup

### Related Resources
[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136292%3A177725)

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #3226

#### Description
Extended Shape tab styling to Measurements card

### CODE REVIEW

**Comment by george-hadfield** [comment]
### Icons should be centred when editing the measurement name

image

**Comment by george-hadfield** [comment]
### Give a bit more space below the last line of text and the next line
It just looks a touch too tight between the text and lines

image

**Comment by george-hadfield** [comment]
### lines should span full width of card

image

**Comment by george-hadfield** [comment]
### measurement titles for accordions are too small
These are 12px should be 13px

image

**Comment by george-hadfield** [comment]
### Chevron and text is positioned too far right

Build
image

Design
image

**Comment by george-hadfield** [comment]
### Left align measurement text

Also open up the spacing between each point measurement as its almost touching

image

**Review by sanmont3drepo — APPROVED** [review]

**Pull request merged**
