### PR TITLE
Issue 4137 - Release Candidate 5.2.0

### LINKED ISSUE #4137: Release candidate for 5.2.0
Snapshotting staging to create a release candidate for 5.2.0 so we can start the QA process

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #4137

#### Description
3drepo.io changes:
https://github.com/3drepo/3drepo.io/milestone/247
https://github.com/3drepo/3drepo.io/milestone/248
https://github.com/3drepo/3drepo.io/milestone/249
https://github.com/3drepo/3drepo.io/milestone/250

3drepobouncer changes:
https://github.com/3drepo/3drepobouncer/milestone/121?closed=1

3drepounity: 
https://github.com/3drepo/3drepounity/milestone/85?closed=1

#### Test cases
QA sheet: https://docs.google.com/spreadsheets/d/1bG-goyim0qMo6wJgAQpbki02_Vud3qzOp4kGgg7FTjw/edit#gid=126155524

###### Release critical
- [x] [Back to login link is in the wrong place](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484908372) (Santiago)
- [x] [Non teamspace admin is not seeing the avatar of the teamspace](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484919474) (Santiago)
- [x] [Cannot remove project as project admin](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484935445) (Daniel)
- [x] [When deleting a container that is associated to a federation instead of showing why you cant do it it shows an unexpected error.](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484970411) (Santiago)
- [x] [When trying to sign up with a duplicate e-mail, the top of the form says "Username"](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485078681) (Santiago)
- [x] [Creating and deleting a viewpoint from a custom ticket before saving causes the page to crash](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485165901) (Santiago)
- [x] [In the viewer, exporting a set of groups that contains a title-less group, and then reimporting it, throws an error
](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485178573) (Alessandro)
- [x] [Attempting to update a ticket from an account without permissions results in a 401 that takes the user back to the project page.](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485202167) (Daniel)
- [x] [Custom tickets with a required boolean property require it to be true](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485262885) (Santiago)
- [x] [Adding and removing text from an image-only comment in a Custom Ticket leaves the old text in other users conversations](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485355819) (Alessandro)
- [x] [Opacity doesn't reset properly on colour overrides](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485457370) (Alessandro)
- [x] [Error popping up when entering a model that is not within your own teamspace](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1490217104)

###### Highly desirable
- [x] [After entering and then deleting a date in the Start or End field of an Issue, the Cancel button returns the previous date.](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484932038) (Alessandro)
- [x] [Create issue/risk button in the Kanban board is not disabled for users with Viewer permissions](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484947278) (Daniel)
- [x] [Consistent icons on add image/screenshot](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484949753) (Alessandro)
- [x] [Risk data drop down is coming up way too high on the tab](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484970752) (Alessandro)
- [x] [Hitting Enter instead of pressing the Save button when labelling a measurement on an Issue causes the viewer to re-load.](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484988662)  (Alessandro)
- [x] [Invalid groups option in the ellipsis menu trigger 404 error. Namely, Delete All and Export groups](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485009370) (Alessandro)
- [x] [Closing or Voiding an Issue does not immediately remove it shapes] (Alessandro)(https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485031709)
- [x] [Save button is not being disabled for non-admins in GIS Settings.](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485095097) (Daniel)
- [x] [Non-smart group with 0 objects should not be saveable](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485188592) (Alessandro)
- [x] [Deleting a smart group and creating a non-smart title-less one immediately after crashes the app](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485230664) (Alessandro)

###### Nice to haves
- [x] [The notifications centre doenst get realtime events](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484978293) (Santiago)
- [x] [ Date field is not being disabled for viewers in risk](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484990128) (Alessandro)
- [ ] [Viewer shouldn't be able to try to create a shape on a risk](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484992264)(Daniel)
- [x] [Cannot undo/clear canvas with one stroke](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485079293) (Alessandro)
- [ ] [When selecting a new map type, the old map doesn't change until the user interacts again with the viewer](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485111802)
- [x] [Smart groups can have an operation called does not exist. Exporting and then re-importing a group of that kind, makes clicking the chip breaking the app](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485262105)  (Alessandro)
- [ ] [Kanban Permission UI oddities](https://github.com/3drepo/3drepo.io/issues/4137#issuecomment-1485047719)
- [x] [When filtering a model, deselect action deselects all models instead of the selected one.](https://github.com/3drepo/3drepo.io/issues/4137#issuecomment-1485063880) (Alessandro)
- [x] [In the group card, a viewer should not be able to click on import groups or delete all](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485355221) (Alessandro)
- [x] [Sign up (email taken) Try to sign up with an email that already has an account](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485206852) (Santiago)
- [x] [UX on groups card filter menu](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485448979) (Alessandro)
- [x] [Both users should have the edited label](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1487203073) (Alessandro)

###### Low priority nice to haves
- [ ] [Kanban Date and Date/Time picker styling is a bit off](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484899485)
- [ ] [Setting an End Date in an Issue that precedes the Start Date shows a modal error dialog](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484940915)
- [ ] [The screenshot preview modal becomes misaligned in narrow windows.](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484978962)
- [ ] [Screenshot modal looks odd when you have a small image](https://github.com/3drepo/3drepo.io/issues/4137#issuecomment-1485053163)
- [ ] [Groups delete modal is too small and the close icon overlaps with the title](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484987045)
- [ ] [Kanban behaviour on commenters not being able to change properties they are not allowed to](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1484989433)
- [ ] [The arrow in the GIS maps drop-down is insensitive](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485101359)
- [x] [Switching groups from the card arrows at the top shows some as saveable when nothing was actually changed](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485169022) (Alessandro)
- [ ] [The 'Go to frame' button of the sequences field in kanban board issues/risks doesn't do anything.](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485171862)
- [ ] [Invalid comment in a group does not use the right colours](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485323129)
- [ ] [When opening the compare card in a container the container is not selected in the list by default](https://github.com/3drepo/3drepo.io/issues/4137#issuecomment-1485058209)
- [ ] [In the group card, the button to delete a smart filter value is not aligned with it](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485415333)

###### Known issues (won't fix or has it's own issue)
- [Clicking a Pin for a custom ticket does not jump to that ticket
](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485190198) - #4128 
- [Signing up using SSO, Try to sign up with an email that already has an account](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485247746)- Changed behaviour since scoping
- [addTicketTemplate on Swagger contains an invalid sample](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485218081) - #https://github.com/3drepo/3drepo.io/issues/3916
- [Check quota on expired enterprise/discretionary license.](https://github.com/3drepo/3drepo.io/pull/4138#issuecomment-1485258056) - desired behaviour

#### Bug Template
````
#### Description
<!-- Describe what you've observed here -->

#### Steps to replicate
<!-- Step by step instructions on how to replicate the situation -->

#### Current Behaviour
<!-- Describe the erroneous behaviour you're seeing -->

#### Expected Behaviour
<!-- Describe what you believe is the correct behaviour -->

#### Pictures/ Gifs of the error
<!-- Post any pictures/videos that will help the person to understand the problem -->

````

### CODE REVIEW

**Comment by carmenfan** [comment]
#### Description


#### Steps to replicate


#### Current Behaviour


#### Expected Behaviour


#### Pictures/ Gifs of the error

**Comment by The-Daniel** [comment]
#### Description
Kanban Date and Date/Time picker styling is a bit off. These can be found when editing an issue/risk. The DateTime picker is found in the sequences tab.
The cancel and ok button are inconsistent sizes.
The horizontal bar on the DateTime picker which holds the tabs for date and time does not extend all the width of the modal. I think this is wrong @george-hadfield ?
There might also be too much padding, but that's up to what George thinks.

#### Pictures/ Gifs of the error
image
image

**Comment by carmenfan** [comment]
#### Description
`Back to login` link is in the wrong place

#### Steps to replicate
- follow the normal (non SSO) sign up procedure
- click on the verification link

#### Current Behaviour
- once verified, the bubble is showing the `back to login` link under the logo

#### Expected Behaviour
- the link should be inside the message bubble

#### Pictures/ Gifs of the error



image

**Comment by carmenfan** [comment]
#### Description
Non teamspace admin is not seeing the avatar of the teamspace

#### Steps to replicate
Assign a user with some model level privileges within the teamspace, enter the teamspace page as that user

#### Current Behaviour
- Landing page is showing the avatar correctly, but default placeholder is being shown on the teamspace page

image
image



#### Expected Behaviour
teamspace avatar should be shown where available

**Comment by sebjf** [comment]
#### Description
After entering and then deleting a date in the Start or End field of an Issue, the Cancel button returns the previous date.

#### Steps to replicate
1. Go into an issue (with the Start date deleted/unset)
2. Add a date
3. Delete the date
4. Click the field again
5. Click Cancel

#### Current Behaviour
The date that was originally set is still visible

#### Expected Behaviour
There should be no date

#### Pictures/ Gifs of the error

https://user-images.githubusercontent.com/5058369/227922326-a6113c39-e762-4ddf-8987-e71a3c566ebe.mp4

**Comment by carmenfan** [comment]
#### Description
Cannot remove project as project admin

#### Steps to replicate
- create a new project
- give project admin privilege to a user
- delete the project as that user

#### Current Behaviour
- it fails with an expected error message
image

#### Expected Behaviour
confirming with @anorrie , either project admins should be able to delete the project (i.e. backend needs changing) or they shouldn't get the option in the UI (front end needs changing)

**Comment by sebjf** [comment]
#### Description
Setting an End Date in an Issue that precedes the Start Date shows a modal error dialog

#### Steps to replicate
1. Go into any issue
2. Set the start date to the current day
3. Set the end date to a day before the start date

#### Current Behaviour
A modal dialog is displayed. The message is informative, but the dialog could be intimidating to some users (giant Error text, status codes they won't understand, message at the top saying "something has gone wrong").

#### Expected Behaviour
A dedicated dialog or the inability to set preceding dates.

#### Pictures/ Gifs of the error
image

**Comment by The-Daniel** [comment]
#### Description
Create issue/risk button in the Kanban board is not disabled for users with Viewer permissions

#### Steps to replicate
Open the kanban board for a federation/container where you have viewer permissions.
The create button will not be disabled.
Upon trying to create a new issue/risk you get an error modal

#### Current Behaviour
The button is not disabled letting a viewer fill out the form to create a new issue/risk.
Submitting the form opens an error modal

#### Expected Behaviour
The button is disabled or hidden

#### Pictures/ Gifs of the error
image
image

**Comment by sebjf** [comment]
The Add Screenshot and Add Upload image buttons have the little crosses on opposite sides. Is this deliberate @george-hadfield?

image

**Comment by sanmont3drepo** [comment]
#### Description
When deleting a container that is associated to a federation instead of showing why you cant do it it shows an unexpected error.

#### Steps to replicate
- Create a federation
- try to delete a container for that federation

#### Current Behaviour
It says there was an unexpected error

#### Expected Behaviour
sshould say that the container couldnt be deleted because it belongs to a federation.

#### Pictures/ Gifs of the error
image

**Comment by carmenfan** [comment]
#### Description
Risk data drop down is coming up way too high on the tab

#### Steps to replicate
- enter a teamspace with mitigation suggestions (or upload them in the teamspace settings with [this file](https://www.dropbox.com/s/czc3bmqs4knjwst/treatement%20suggestions.csv?dl=0))
- try to create a risk

#### Current Behaviour
The suggested fields are coming up way too high
img

#### Expected Behaviour
The drop down menu should function similarly to other drop downs

**Comment by sanmont3drepo** [comment]
#### Description
The notifications centre doenst get realtime events

#### Steps to replicate
- Go to the containers page
- Refresh 
-  Upload a bad revision (https://www.dropbox.com/s/jrqi6uowh4y6sse/badFile.ifc?dl=0)

#### Current Behaviour
- doenst show the error in the notification centre until you refresh

#### Expected Behaviour
- Should get the notification in realtime

#### Pictures/ Gifs of the error
nonotification

**Comment by sebjf** [comment]
#### Description
The screenshot preview modal becomes misaligned in narrow windows.

#### Steps to replicate
1. Go to an issue
2. Create a screenshot, or upload/edit an image
3. Make the window narrow relative to the image editing tools

#### Current Behaviour
The screenshot header ends before the image

#### Expected Behaviour
The screenshot header should span the editing tools bar

#### Pictures/ Gifs of the error
image

**Comment by Amantini1997** [comment]
#### Description
Groups delete modal is too small and the close icon overlaps with the title

#### Steps to replicate
In the viewer:
- open the groups card;
- click on the ellipsis;
- click on `Delete all`.

#### Pictures/ Gifs of the error
image

**Comment by sebjf** [comment]
#### Description
Hitting Enter instead of pressing the Save button when labelling a measurement on an Issue causes the viewer to re-load.

#### Steps to replicate
1. Go into an Issue
2. Create a Shape
3. Click the Edit button next to the label of the shape
4. Change the name, and press Enter

#### Current Behaviour
The viewer reloads

#### Expected Behaviour
The new string is saved

#### Pictures/ Gifs of the error

https://user-images.githubusercontent.com/5058369/227930772-25319fbd-8692-4028-9328-fe36e71722f8.mp4

**Comment by The-Daniel** [comment]
#### Description
Viewers with commenter permissions get a different permissions error when editing a non-assigned issue/risk.

So I think it's correct that commenters can only edit issues/risks they have created/assigned to. But the method of showing lack of permissions is different from a user with viewer permissions trying to edit.
An error modal pops up. When closed the kanban board appears as if the change was made. Refreshing the page resets it to its original state.

#### Steps to replicate
As a user with commenter permissions on a container/federation. Try to move an issue/risk that you have not been assigned to and have not created yourself.

#### Current Behaviour
An error modal pops up. The issue looks like it has been editted

#### Expected Behaviour
It should act like when a viewer tries to edit an issue/risk. A toast message appears saying insufficient permissions. The kanban board shows that no change has been made

#### Pictures/ Gifs of the error

When a commenter tries to edit an issue/risk they shouldn't be able to edit:
image
When a viewer tries to edit an issue/risk they shouldn't be able to edit:
image

**Comment by carmenfan** [comment]
Date field is not being disabled for viewers in risk

img

**Comment by carmenfan** [comment]
Viewer shouldn't be able to try to create a shape on a risk

img

**Comment by sebjf** [comment]
#### Description
Save button is not being disabled for non-admins in GIS Settings.

#### Steps to replicate
1. Open a GIS-enabled project as a Collaborator
2. Open the GIS card and go to Settings
3. Change a field and Save

#### Current Behaviour
A modal error dialog is displayed

#### Expected Behaviour
The save button should not be accessible for unauthorised users

#### Pictures/ Gifs of the error
image

**Comment by sebjf** [comment]
#### Description
The arrow in the GIS maps drop-down is insensitive

#### Steps to replicate
1. Open a container in a GIS enabled project with Here Maps enabled

#### Current Behaviour
Hovering the cursor over the arrow does not allow the user to click it

#### Expected Behaviour
The entire drop-down should allow the user to click it to select the map

#### Pictures/ Gifs of the error
image

**Comment by sebjf** [comment]
#### Description
When selecting a new map type, the old map doesn't change until the user interacts again with the viewer

#### Steps to replicate
1. Open a GIS model from a Here Maps enabled teamspace
2. Select the Open Street Map type and turn on tiles
3. Select the Here Terrain type

#### Current Behaviour
The Open Street Map tiles remain visible until another UI element is touched

#### Expected Behaviour
The Open Street Map tiles should be removed immediately

#### Pictures/ Gifs of the error
https://user-images.githubusercontent.com/5058369/227955137-a38a4173-33f6-42ae-b2a0-adfa81c15573.mp4

**Comment by sebjf** [comment]
#### Description
Creating and deleting a viewpoint from a custom ticket before saving causes the page to crash

#### Steps to replicate
1. Create or have a template with the `defaultView` enabled
2. Create a new ticket of that template
3. Click Create Viewpoint
4. Delete the Viewpoint
5. Try to save the ticket

#### Current Behaviour
The page shows an error 400

#### Expected Behaviour
The ticket should be created successfully

#### Pictures/ Gifs of the error
https://user-images.githubusercontent.com/5058369/227962667-b9a2646d-dca5-476d-bd2d-bea5b702c9dc.mp4

**Comment by Amantini1997** [comment]
#### Description
In the viewer, exporting a set of groups that contains a title-less group, and then reimporting it, throws an error

#### Steps to replicate
In the viewer, open the group cards and make sure to have at least one non-SMART title-less group (i.e. create a group without editing anything)
- export the groups into a file 
- import such a file

#### Current Behaviour
A 404 error is thrown stating 'Something went wrong trying to export the groups'

#### Expected Behaviour
The file should be imported successfully

**Comment by Amantini1997** [comment]
#### Description
Cannot create a non-smart group if any fields is dirty

#### Steps to replicate
In the viewer, open the group cards and
- Click on new group (notice that the button save is enabled)
- edit the title or the description

#### Current Behaviour
The group cannot be saved

#### Expected Behaviour
The group should still be saveable

**Comment by sebjf** [comment]
#### Description
Clicking a Pin for a custom ticket does not jump to that ticket

#### Steps to replicate
1. Create a custom ticket of a template with Pin enabled
2. Add a Pin to the model
3. Exit the ticket
4. Click on the Pin

#### Current Behaviour
Nothing happens

#### Expected Behaviour
The ticket should open up in the Custom Tickets view

#### Pictures/ Gifs of the error
https://user-images.githubusercontent.com/5058369/227966390-c220e85c-a8c5-4e31-844f-e2c3331f5ef5.mp4

**Comment by Amantini1997** [comment]
#### Description
Invalid comment in a group does not use the right colours

#### Steps to replicate
In the viewer, open the group cards
- Click on new group (or edit one)
- write a description long at least 221 chars (first oddity: border should be red)
- click on another focus an lose the focus on the description (second oddity: the field looks correct)

#### Current Behaviour
The colours combinations are wrong

#### Expected Behaviour
The colours should be the same as the rest of aff

#### Pics
**on focused**
image

**on blurred**
image

**Comment by Amantini1997** [comment]
#### Description
In the group card, a viewer should not be able to click on import groups or delete all

#### Steps to replicate
In the viewer, open the group cards with a user who's a viewer
- Click on the ellipsis menu

#### Current Behaviour
The user can import groups and click (unsuccesfully) on `delete all`

#### Expected Behaviour
These options should be disabled

**Comment by sebjf** [comment]
#### Description
Adding and removing text from an image-only comment in a Custom Ticket leaves the old text in other users conversations

#### Steps to replicate
1. Create a new Custom Ticket with Comments, and open it for USER1 and USER2
2. Have USER1 create an image-only message
3. Have USER1 edit the message to include some text
4. Have USER1 edit the message again to remove the text

#### Current Behaviour
After (4) the text added in (3) remains visible for USER2

#### Expected Behaviour
The message displays identically for USER1 and USER2.

#### Pictures/ Gifs of the error
image

**Comment by Amantini1997** [comment]
#### Description
In groups:
- the filter menu does not close after selecting an option and none of the items is ever disabled (even if not effective).
- some options should be disabled.
- The first "paste filter" overlaps with the label

#### Steps to replicate
In the viewer, open the group cards 
- create a smart group  (but do not save)
- click on the ellipsis button in the `filters` section
- notice that, even though no filters have been created yet, all the options are available (first oddity)
- click on any of these options, but the `paste filter` and notice that the menu does not fade away (second oddity)
- click on `paste filter` (third oddity)
- create a filter
- Do not click on the chip of the newly created filter and notice that, clicking on the ellipsis button, the option `deselect` is clickable

#### Current Behaviour
All the oddities described above

#### Expected Behaviour
The first "paste filter" should be positioned closer to the bottom to not overlap the `Filters` labels;
Invalid options should not be displayed or should be disabled

#### Pics

image
image

**Comment by Amantini1997** [comment]
#### Description


#### Steps to replicate
In the viewer, open the group cards 
- create 2 smart groups targeting the same objects (group A and Group B)
- for group A, select a color with opacity set to 30%;
- for group B, select a color with opacity set to 100%;
- now go back to the list of menus
- color overrides group A first and then group B
- deselect Group B

#### Current Behaviour
The object have a color with opacity of 100%

#### Expected Behaviour
The object should be partial opaque since A (the group still selected) has opacity of 30%

**Comment by Charence** [comment]
#### Description

3drepo4unity works but:

- Need to add additional references to 3drepo4unity VS solution
- SampleUnityProject uses a slightly older Unity (2020.1.17f1)

#### Pics
Screenshot 2023-03-27 17 11 17

Screenshot 2023-03-27 17 16 02

**Comment by Charence** [comment]
#### Description
Unexpected error messages when importing model into Unreal Demo

#### Steps to replicate
`3drepoimport charence 6b8a6380-cc8d-11ed-9c1a-07be958a4758`

#### Pictures/ Gifs of the error
Screenshot 2023-03-28 11 48 28

**Comment by Charence** [comment]
Staging doesn't have that error so will merge in:
image

**Comment by carmenfan** [comment]
#### Description
Error popping up when entering a model that is not within your own teamspace

#### Steps to replicate
- go to a model that belongs to a teamspace that is shared with you (i.e. you are not the teamspace owner)

#### Current Behaviour
This error is showing 
MicrosoftTeams-image (1)

#### Expected Behaviour
Error should not show

**Comment by Charence** [comment]
> #### Description
> 3drepo4unity works but:
> 
> * Need to add additional references to 3drepo4unity VS solution
> * SampleUnityProject uses a slightly older Unity (2020.1.17f1)
> 
> #### Pics
> Screenshot 2023-03-27 17 11 17
> 
> Screenshot 2023-03-27 17 16 02

This is now done. A new version of `3drepo4unity" should be published on 3drepo.com.

**Comment by Charence** [comment]
> Staging doesn't have that error so ~will~ can merge in

Staging to be merged into master for `3drepoUnreal` and version published on 3drepo.com to be updated.

https://github.com/3drepo/3drepoUnreal/pull/85

**Comment by carmenfan** [comment]
Passed QA testing with accepted failures/oddities noted

image

**Review by anorrie — APPROVED** [review]

**Pull request merged**
