### PR TITLE
Issue 1184: Migration - Profile

### LINKED ISSUE #1184: Migration: Profile
#### Description
This issue includes migration of Profile view.

#### Goals
Migration of Profile view to ReactJS

#### Tasks

- Main route
- Component to edit profile data
- Refactor and move old logic to new component

### PR DESCRIPTION
**Pull request by simplypixi**
This fixes #1184 

Description
This PR should be merge after #1177  (PR #1182 ).

- Moved styles to styled components
- Bound react dialogs
- Created new profile page design
- Refactored code
- Remove old (angular) components
- Added editable avatar
- Changed a way of copying zxcnbn to the bundle (gulp => webpack)

### CODE REVIEW

**Comment by simplypixi** [comment]
@carmenfan Could you check locally the result of `yarn build`? On my side everything works perfectly but Travis is definitely disagreed with that fact. ;)

**Comment by simplypixi** [comment]
@carmenfan 
> Avatar on the left doesnt' load if you refresh on profile page. It also doesn't update if you change the avatar.

I didn't change anything in that component (menu on the left). If you will look at the gif you will see that avatar loads properly but loading or rendering time takes long.
It'll work faster (and sync) after migration to React, but I have this component at the end of my list.

**Comment by carmenfan** [comment]
> @carmenfan
> 
> > Avatar on the left doesnt' load if you refresh on profile page. It also doesn't update if you change the avatar.
> 
> I didn't change anything in that component (menu on the left). If you will look at the gif you will see that avatar loads properly but loading or rendering time takes long.
> It'll work faster (and sync) after migration to React, but I have this component at the end of my list.
> 

Ok fair enough! :)

> > Also, maybe we should give some prompt that the password has been updated?
> 
> https://material-ui.com/demos/snackbars/
> Is it ok for you?
> I can add snackbar to each operation, which was migrated to React. It's a good way to show user, what is happening with the requests or to show some important notifications (sometime it's a better solutions than big dialog)

Yes, sounds good! If we have have it pop up on the right bottom corner that'd be awesome 😃

**Comment by simplypixi** [comment]
@carmenfan Fixed ;)
Is the default snackbar styling ok for you? Should I change something?

**Comment by simplypixi** [comment]
@carmenfan Should be ok now

**Comment by carmenfan** [comment]
@simplypixi 

Just got some feedback from the business teams, would it be possible to add another input box to confirm the new password?

**Comment by carmenfan** [comment]
- Profile shows the last sessions' info after I log out and log into a different user:
filter

**Comment by simplypixi** [comment]
> Just got some feedback from the business teams, would it be possible to add another input box to confirm the new password?

Yes, it's possible. 

> Profile shows the last sessions' info after I log out and log into a different user:

I'll check that.

**Comment by simplypixi** [comment]
@carmenfan Fixed!

**Comment by carmenfan** [comment]
#1177 merged, changed target branch for this PR to #1141. please rebase when you have a minute :)

**Comment by carmenfan** [comment]
I'm just going to merge this and do the testing in 1141 !

**Pull request merged**
