### PR TITLE
Issue 5223 Release candidate 5.12.0

### LINKED ISSUE #5223: 5.12.0 Release Candidate
Release QA branch

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #5223

#### Issues addressed:
https://github.com/3drepo/3drepo.io/milestone/268
https://github.com/3drepo/3drepo.io/milestone/271

### Test cases
Full QA test should pass: https://asitesol.sharepoint.com/:x:/s/3DRepoTeamFolder/EYiaHuA-Y5ZBligBNUw4u1kBB-WUG6pZFGWkVfmFJnWLMw?e=2ff05f

### Bug template
````
### Description
<!-- Brief description of the bug -->

### Steps to replicate

### Current Behaviour

### Expected Behaviour

### Pictures/ Gifs of the error
````
Next bug to triage: https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422457724

### Bugs

- [x] [Teamspace not found error is popping up when you update your profile](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2437435817)
- [x] [Sometimes dragging camera result in the picture moving instead](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2435391201) (Alessandro)
- [x] [Group import error dialog is saying export error](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2437757996) (Daniel)
- [x] [Too high momentum when dragging the 2D Drawing](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2438025485) (Daniel)
- [x] [viewer whitescreens when you try to calibrate a second drawing ](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2446346501) (Alessandro)

Graphics:
- [x] [Pin is disappearing on certain angle](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2438037886) (Sebastian)
- [x] [DWGs seems to be assuming a black background instead of white](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2442094121) (could be devops instead. needs checking)

Devops:
- [x] [Error submitting io-activity](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2441308390)

<details><summary>Round 1</summary>
<p>

##### Frontend
- [x] [Sort by calibration order does not change when you alter the sort](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422048824) (Alessandro)
- [x] [Version number links to Intercom Help home rather than Change Logs page](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422183500) (Daniel)
- [x] [Vertical calibration fields are not disabled if the user doesn't have sufficient privilege to update them](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422260759) (Daniel)
- [x] [Collaborators are getting an error when they try to upload a drawing.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422279070) (Alessandro)
- [x] [Can't save a ticket that has a view with transformations](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422583073) (Daniel)
- [x] [Sorting of federations by tickets doesnt work correctly](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422600475) (Alessandro)
- [x] [Changing the code of a federation from something to empty, the list doesn't reflect it and editing still shows the old code.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422622917) (Alessandro)
- [x] [White screen when you delete the last image from a text comment in a ticket](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422690700) (Daniel)
- [x] [Opacity is not being respected in v4 groups](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422804669) (Alessandro)
- [x] [Viewer whitescreens if I change revision after selecting a group](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422827834) (Daniel)
- [x] [The 'close 2D' circle button is appearing during calibration which is unnecessary as there is already a cancel calibration button](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2419192605) (Daniel)
- [x] [Clipping is not available when calibrating](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2419403780) (Daniel)
  - Duplicate: [I dont know if this is an issue, but when I change the the containers included It doesnt update last updated](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422641755)
- [x] [Viewer occasionally crashes when trying to recalibrate from the dashboard.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2419820513) (Alessandro - cannot reproduce)
- [x] [Drawing filename is getting overwritten](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2426417396) (Daniel)

##### Unity
- [x] [Tree behaves strangely on this federation](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422479861) (Sebastian; https://github.com/3drepo/3drepounity/pull/555)

##### Backend
- [x] [Drawings are being downloaded with the statusCode-Revision code as the name of the file instead of the original file name](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422234278) (Carmen)
- [x] [Refreshing page during drawing queue for processing makes the new revision disappear](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422209881) (Carmen)
  - Duplicate: https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2419656204

#### Highly desired
- [x] [Broken link in Terms](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2420029464) (Carmen)
- [x] [Typo in Cookies](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2420039252) (Carmen)
- [x] [User list page is visible even though you're not a teamspace admin](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422016740) (Alessandro)
  - duplicate: https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422201240
- [x] [Update/Add project image fails on images over 1MB. Images under that seem to work.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422142756) (Alessandro)
- [x] [Socket.io groups messages doesn't seem to be registering if I've viewed a different model previously.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422557697) (Alessandro)
- [x] [Upload modals (drawings/containers) are using metric file sizes whereas everywhere else on the app we use IEC units.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2419374994) (Alessandro)

#### Nice to have
- [x] [Add user button should look disabled when it is](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422209881) (Daniel)
- [x] [Setting opacity causes shapes to be filled in.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422513540) (Alessandro)
- [x] [Gis survey point doesnt reflect when changed except for angle. Description and code cant get blanked also.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422630740) (Daniel)

#### Lower priority nice to have
- [x] [Update button stays active when you upload a new avatar](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2421902187) (Daniel)
- [x] [Clip plane border width setting does not work.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422096817) (Daniel)
- [x] [Cannot add new issue types/risk categories](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422166859) (Can't reproduce - Daniel)
- [x] [Updating GIS settings hides tiles
](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422449228) (Daniel)
- [x] [Markup triangle does not fit transform box](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422523136)  (Alessandro)

#### Won't fix
- [Intercom layout is a bit odd](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2421950276)
- [Issues filter list container too small, even when there are no issues.
](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422149760)
- [No spacing below long Description strings in issue.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422183304)
- [The frontend attempts to read fulltree.json for empty containers, and containers it does not have access to when loading a federation.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422198409)
- [Issues 4D dialog should not allow setting start date after end date, or end date before start date.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422230571)
- [When closing an issue, shapes are not removed until the issue exits.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422380670)
- [Internal server error when trying to load Here Map Tiles](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422457724)
- [Unreal readme is incorrect](https://github.com/3drepo/3drepoUnreal/issues/89) 
- [clipping is not available when calibrating. I think this comes from the design change that when you create a drawing there are default planes values.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422834424)
- [The user can calibrate a drawing against a federation of empty containers. Other forms of empty model are hidden in this dropdown](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2419840753)

#### Expected behaviour
- [Unable to drag and drop a risk](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422194532)
- [Drawing revisions can have the same Revision Code but should not.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422242048)
- [No option to download the Risk report in any other format than JSON.
](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422367391)
- [The last two tests in "Viewer - Risks" ask to set the treatment status to "fully treated". This option is missing from the dropdown.](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422396444)
- [There is no Create Report option for Issues](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422399572)
- [Focus button not visible on toolbar
](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422424157)

#### Queue issues
Same queue serving multiple branches is causing these issues:
 - https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2419978824

</p>
</details>

### CODE REVIEW

**Comment by The-Daniel** [comment]
### Description
The 'close 2D' circle button is appearing during calibration which is unnecessary as there is already a cancel calibration button

It looks like a separate close button was added during a merge
image

### Pictures/ Gifs of the error
image

**Comment by The-Daniel** [comment]
### Description
Upload modals (drawings/containers) are using metric file sizes whereas everywhere else on the app we use IEC units.

### Current Behaviour
File sizes are using different formats in the upload modals

### Expected Behaviour
All file sizes use the same format

### Pictures/ Gifs of the error
image
image

**Comment by The-Daniel** [comment]
### Description
Clipping is not available when calibrating

### Steps to replicate
- Open the calibration viewer for any drawing

### Current Behaviour
- There is no option in the 3D side of the viewer for adding clipping planes

### Expected Behaviour
- In the 3D Viewer the user can introduce clipping planes
- The clipping plane option along with the clipping planes must be removed in the vertical calibration step otherwise they interact negatively with the planes calibration

### Pictures/ Gifs of the error
image

**Comment by The-Daniel** [comment]
### Description

Drawing uploads appear to sometimes silently fail when uploading to a new drawing from the uploads modal. The drawing is added to the dashboard list and shows the status as queued. Upon refresh there is no active upload and no revisions. If the user tries to upload to this drawing container using the same status code and revision code then the upload will error saying that this code combination already exists despite showing no revisions.

Uploading the same file to an existing drawing appears to work fine. 

### Steps to replicate
- Open the drawings upload modal
- Add a file (I used the autocalibrated .dwg which Carmen provided above)
- Set the destination to be a new drawing.
- Fill out all the other required fields and submit

### Current Behaviour
- The drawing container is created. The revision upload seems stuck in queued
- Upon refresh the revision is missing and no upload is happening

### Expected Behaviour
- The user can create a drawing and upload a revision at the same time using the drawing uploads modal

### Pictures/ Gifs of the error
image
image

**Comment by The-Daniel** [comment]
### Description
The user can calibrate a drawing against a federation of empty containers. Other forms of empty model are hidden in this dropdown

### Steps to replicate
- Create an empty container
- Create a Federation containing only this empty container
- From the drawings list calibrate a drawing against this new federation

### Current Behaviour
- This form of empty federation still appears on the list
- Upon trying to calibrate against this model the user will see an empty federation page

### Expected Behaviour
- This form of empty federation is filtered from the list

### Pictures/ Gifs of the error
image
image

**Comment by The-Daniel** [comment]
### Description

Drawing uploads get stuck in 'Processing' even when they appear to have uploaded correctly. Sometimes when uploading a file to a drawing the revision count goes up but the drawing status is stuck in 'Processing'. When calibrating that drawing it uses this recently uploaded file. So what is it processing?

### Steps to replicate
- In the drawings dashboard upload a file
- Wait for the file to complete

### Current Behaviour
- The revision count will increase and an empty drawing will change to having the functionality of a populated drawing
- The item is stuck in the 'Processing' state and the user cannot upload another file to this drawing

### Expected Behaviour
- The drawing status changes to OK when the revision is sucessfuly uploaded
- The user can upload further revisions if they so wish

### Pictures/ Gifs of the error
image
image

**Comment by Charence** [comment]
### Description
Section 4 pricing information link broken: https://issue-5223.dev.3drepo.io/v5/terms

### Steps to replicate
Press link

### Current Behaviour
Broken

### Expected Behaviour
Not broken

### Pictures/ Gifs of the error
image

**Comment by Charence** [comment]
### Description
Typo in Cookies Policy: missing space

### Steps to replicate
Go to Cookies Polices

### Current Behaviour
Missing space

### Expected Behaviour
Correct spelling

### Pictures/ Gifs of the error
image

**Comment by sebjf** [comment]
### Description
When updating the profile image, the Update button stays active and errors are printed to the console. (The image does update though.)

### Steps to replicate
1. Open the Profile modal
2. Update the image to a valid one

### Current Behaviour
Update profile button remains active

### Expected Behaviour
Update profile button should be greyed out once changes are applied

### Pictures/ Gifs of the error

https://github.com/user-attachments/assets/f1455d80-2055-467d-83c7-5d5a7e753b70

**Comment by sebjf** [comment]
### Description
Intercom layout is a little odd.

There is a scroll bar on the right, but it doesn't reveal anything, and the top right corner cut off. The close button overlaps with it.

### Steps to replicate
Open the Intercom dialog

### Pictures/ Gifs of the error
image

**Comment by carmenfan** [comment]
### Description
User list page is visible even though you're not a teamspace admin

### Steps to replicate
- Log in as a non teamspace admin user, go to https://issue-5223.dev.3drepo.io/v5/dashboard/5_12_qa/t/users

### Current Behaviour
It will pop up with not authorised, but once you click ok, it continues to render the page

### Expected Behaviour
Should probably redirect you to https://issue-5223.dev.3drepo.io/v5/dashboard/5_12_qa

### Pictures/ Gifs of the error

**Comment by FJThiel** [comment]
### Description
When sorting Drawings by the category "2D/3D Calibration" the order does not change when switching between ascending and descending.

### Steps to replicate
- Create a project
- Add two drawings
- Upload a file to one of them and wait for the status to change to "calibrate"
- Click on "2D/3D Calibration" to change the order.

### Current Behaviour
The order remains the same.

### Expected Behaviour
The order should change.

### Pictures/ Gifs of the error
image

image

**Comment by sebjf** [comment]
### Description
Clip plane border width setting does not work.

### Steps to replicate
1. Set a clipping plane
2. Update the Clip Plane Border Width in the visual settings

### Current Behaviour
Width is unchanged.

### Expected Behaviour
With should change with setting.

### Pictures/ Gifs of the error
image

(Width above should be set to 15, which is huge...)

**Comment by Amantini1997** [comment]
### Description
Creating a project with an image, adds the project to the teamspace, but the image is not visible

### Steps to replicate
- Create a new project with image set before creation

### Current Behaviour
- The image does not show

### Expected Behaviour
- The image should display straight away

**Comment by apeitup** [comment]
### Description
Update/Add project image fails on images over 1MB. Images under that seem to work.

### Steps to replicate
Go to Teamspace, click 'New project', add the project name, and then add an image over 1mb. 
Or navigate to a project, click project settings, and upload an image larger than 1 MB. 
### Current Behaviour
Fails with the error message "The file you tried to upload was too big. File uploads should be no larger than 1.0 MiB."
### Expected Behaviour
The image should be added to project, Or updates the project image.
### Pictures/ Gifs of the error

Screenshot 2024-10-18 at 11 14 49
Screenshot 2024-10-18 at 11 15 08

**Comment by sebjf** [comment]
### Description
Issues filter list container too small, even when there are no issues.

### Steps to replicate
1. Open an empty issues list in the viewer

### Current Behaviour
The filters header hides some filters and has a scrollbar, even though there is plenty of space below

### Expected Behaviour
The filters are all visible.

### Pictures/ Gifs of the error
image

**Comment by Amantini1997** [comment]
### Description
In teamspace settings, I can't add new issue types/risk categories

### Steps to replicate
- Go to the teamspace settings tab
- type in a new issue type

### Current Behaviour
- Save button become enabled the first time. Pressing it does not add the issue
- After refresh, typing in a new issue type does not enable the save button

### Expected Behaviour
- Save button should become enable. Pressing it should add the new type

**Comment by Charence** [comment]
### Description
Version number links to Intercom Help home rather than Change Logs page

### Steps to replicate
Click on the version number below the log in box

### Current Behaviour
Opens Intercom Help home page. If you navigate to "Change Logs" there are only 3 v4 change logs.

### Expected Behaviour
Show change log for current/recent release

### Pictures/ Gifs of the error
image
image

**Comment by ChristosTsiotsias** [comment]
### Description
Unable to drag and drop a risk

### Steps to replicate
1. Go to risks in the kanban as a teamspace admin
2. Try to drag and drop a risk to a different column

### Current Behaviour
Unsufficient Permissions Error is thrown

### Expected Behaviour
Should be able to drop the risk

### Pictures/ Gifs of the error

https://github.com/user-attachments/assets/0eee237d-421d-4f14-8062-6c7d52f8ad87

**Comment by sebjf** [comment]
### Description
The frontend attempts to read `fulltree.json` for empty containers, and containers it does not have access to when loading a federation.

Note this isn't a test case, I just noticed it.

I am also not sure how serious it is: it doesn't cause any further issues with the viewer. Though from a security perspective it leaks the UUIDs of the other containers. That said, the UUIDs don't contain any information themselves and can't be used to get it...

### Steps to replicate
1. Create a federation with two containers, where one is accessible to another user and the other is not.
2. Log in as the other user and attempt to load the federation with the network tab open

### Current Behaviour
The frontend will attempt to access the `fulltree.json` endpoint for all containers, not just those the user has access to, receiving a 401 in response.

### Expected Behaviour
The frontend does not issue any requests for inaccessible containers.

### Pictures/ Gifs of the error
image

**Comment by Amantini1997** [comment]
### Description
A non teamspace-admin shouldn't be able to see the users permissions page at all

### Steps to replicate
- Copy the user permission tab url
- Log in with a user that is not a teamspace admin
- Reach the copied URL

### Current Behaviour
- A modal informs the user they don't have the authorisation, but after closing it, they can still see the information

### Expected Behaviour
- A modal informs the user they don't have the authorisation AND they get redirected somewhere else

### Pictures/ Gifs of the error
image

**Comment by Amantini1997** [comment]
### Description
When there are no seats available in the teamspace, the "add user" button seems enabled

### Steps to replicate
Reach a teamspace with no seats left

### Current Behaviour
The "add user" button is disabled, but uses the enabled colours

### Expected Behaviour
The "add user" button is disabled, and uses the appropriate colours

### Pictures/ Gifs of the error
image

**Comment by FJThiel** [comment]
### Description
Refreshing page during drawing queue for processing makes the new revision disappear 

### Steps to replicate
- Create drawing and upload file
- After status has changed to "Queued", press F5 to reload the window.

### Current Behaviour
The drawing shows "Drawing empty" and extending into the revisions view only shows the box to upload files. It also does not appear to recover from this, never showing the processed drawing.

### Expected Behaviour
Status remains at "Queued" until the next step is reached and then changes to whatever is next.

### Pictures/ Gifs of the error
After uploading the file into a newly created container:
image

After pressing refresh:
image

**Comment by sebjf** [comment]
### Description
For completeness, this is still to be resolved:

https://github.com/3drepo/3drepo.io/issues/4145#issuecomment-1490066719
https://github.com/3drepo/3drepo.io/pull/4717#issuecomment-1908437328

**Comment by carmenfan** [comment]
### Description
Drawings are being downlanded with the statusCode-Revision code as the name of the file instead of the original file name

### Steps to replicate
- upload a drawing
- download it again

### Current Behaviour
it is being downloaded with the statusCode/RevCode as name

### Expected Behaviour
it should be downloaded with the original file name

**Comment by FJThiel** [comment]
### Description
Drawing revisions can have the same Revision Code but should not.

### Steps to replicate
- Create empty drawing
- Add a new revision with a Revision Code
- Add a second revision with the same Revision Code

### Current Behaviour
Both revisions are added with the same Revision Code.

### Expected Behaviour
This should not be possible.

### Pictures/ Gifs of the error
image

**Comment by carmenfan** [comment]
### Description
Collaborators are getting an error when they try to upload a drawing.

### Steps to replicate
- As a collaborator of a drawing, click on `Upload files`

### Current Behaviour
- a error modal pops up with `NOT AUTHORIZED` error, this came from the drawingCategories endpoint (this is only needed for creating a new drawing container whilst you're trying to upload a file, but collaborator has no rights to create a new drawing container so they never need this...) 

### Expected Behaviour
- Collaborator should be able to upload drawings to existing containers without encountering the error modal.

### Pictures/ Gifs of the error

**Comment by FJThiel** [comment]
### Description
No option to download the Risk report in any other format than JSON.

### Steps to replicate
- Open viewer
- Create risks

### Current Behaviour
Only option for the download is the JSON

### Expected Behaviour
According to the test sheet, there should be an option for a report, but I can't find it.

### Pictures/ Gifs of the error
image

**Comment by sebjf** [comment]
### Description
When closing an issue, shapes are not removed until the issue exits.

### Steps to replicate
1. Create a new Issue with a Shape and a Pin
2. Set the status to closed

### Current Behaviour
The pin is immediately removed but the shapes are not until the Issue is exited

### Expected Behaviour
Both pins and shapes are removed at the same time

### Pictures/ Gifs of the error

https://github.com/user-attachments/assets/307e4fa8-a6a0-472b-8aa5-bb16a1871404

**Comment by FJThiel** [comment]
### Description
The last two tests in "Viewer - Risks" ask to set the treatment status to "fully treated". This option is missing from the dropdown.

### Steps to replicate
- In the SafetiBase tab, open a new risk
- Switch to the treatment tab
- Under "Treatment Status" open the dropdown menu.

### Current Behaviour
The option "fully treated" is missing

### Expected Behaviour
There should be an option "fully treated"

### Pictures/ Gifs of the error
image

**Comment by sebjf** [comment]
### Description
There is no Create Report option for Issues

### Steps to replicate
1. Open a viewer with active issues and click the ellipses menu

### Current Behaviour
There is no Create Report option

### Expected Behaviour
There is an option to Create Report

### Pictures/ Gifs of the error
image

**Comment by nkuberaf** [comment]
### Description
Only models matching the search term should be shown

### Steps to replicate
Enter a search term on the search filter

### Current Behaviour

Search doesnt work.

### Expected Behaviour
When searching for the model name it should appear

### Pictures/ Gifs of the error
image
image

**Comment by apeitup** [comment]
### Description
Focus button not visible on toolbar

### Steps to replicate
Open container

### Current Behaviour
No fucus button visible
### Expected Behaviour
Should have a focus button
### Pictures/ Gifs of the error
Screenshot 2024-10-18 at 13 57 31

**Comment by sebjf** [comment]
### Description
Updating GIS settings hides tiles

### Steps to replicate
1. Set up a model with GIS coordinates
2. Show Open Street Map Tiles
3. Use the settings menu to change the vertical offset slightly

### Current Behaviour
Tiles disappear, and do not reappear until they are toggled again

### Expected Behaviour
Tiles update in-place

### Pictures/ Gifs of the error

**Comment by sebjf** [comment]
### Description
Internal server error when trying to load Here Map Tiles

### Steps to replicate
1. Open a model that has GIS coordinates and Here enabled (i.e. from the QA, teamspace), eg. https://issue-5223.dev.3drepo.io/v5/viewer/5_12_qa/240b0862-68b7-4710-8db6-f6bf7c73a726/83a24cb9-4429-4f12-9f4a-06f83562c578
2. Open the GIS card and enabled Here Map Tiles

### Current Behaviour
Only half the tiles load and the server returns 500 for the others

### Expected Behaviour
All tiles load

### Pictures/ Gifs of the error
image

**Comment by carmenfan** [comment]
Text is obscured in delete all groups button

image

**Comment by sebjf** [comment]
### Description
Setting opacity causes shapes to be filled in.

### Steps to replicate
1. Open an image for Markup
2. Draw a Shape
3. Use the Color option to change the opacity
4. Click on the shape again to move it

### Current Behaviour
The shape fills in

### Expected Behaviour
The outline updates its opacity

### Pictures/ Gifs of the error
https://github.com/user-attachments/assets/dee37566-5391-40d7-9c92-1889c1932ba9

**Comment by sebjf** [comment]
### Description
Markup triangle does not fit transform box 

### Steps to replicate
1. Add a Triangle shape to an image markup

### Current Behaviour
The transform box is a different size to the triangle

### Expected Behaviour
The triangle is the same size as the transform box

### Pictures/ Gifs of the error
image

**Comment by carmenfan** [comment]
### Description
Socket.io groups messages doesn't seem to be registering if I've viewed a different model previously.

### Steps to replicate
NOTE: this doesn't always happen and you may have to try it couple of times:

Prepare 2 models, model 1 has groups and model 2 has no groups, and a group export json (can be the same groups as model 1's):
- Go to model 1, open the groups tab
- Flip to model 2, open the groups tab and try to import the groups
(If it didn't trigger, delete the groups and try again)

### Current Behaviour
- For a few seconds, will will see model 1's groups
- Occasionally, after you've imported the groups in model 2, the groups don't appear until a refresh

### Expected Behaviour
- Should not see groups from a different model when your'e loading a new model
- Groups should always appear when you imported them successfully

### Pictures/ Gifs of the error

**Comment by Amantini1997** [comment]
### Description
Can't save a ticket that has a view with transformations

### Steps to replicate
- Open up a model with sequences
- Go to a point with a transformation

### Current Behaviour
- Can't save the ticket

### Expected Behaviour
- It should be possible to save the ticket

### Pictures/ Gifs of the error

https://github.com/user-attachments/assets/636eef63-73b3-48ac-890b-27f4c98da557

**Comment by sanmont3drepo** [comment]
- Sorting of federations by tickets doesnt work correctly
sorting failed

**Comment by sanmont3drepo** [comment]
- Changing the code of a federation from something to empty, the list doesn't reflect it and editing still shows the old code.
 
 
blank error

**Comment by sanmont3drepo** [comment]
- I dont know if this is an issue, but when I change the the containers included It doesnt update last updated

updated-error

**Comment by Charence** [comment]
https://github.com/3drepo/3drepoUnreal/issues/89

**Comment by carmenfan** [comment]
### Description
Opacity is not being respected in v4 groups

### Steps to replicate
- Go to groups panel, open an existing group
- Set the opacity to something below 100%
- impose colour override

### Current Behaviour
objects do not turn semi transparent

### Expected Behaviour
objects should turn semi transparent

### Pictures/ Gifs of the error

**Comment by carmenfan** [comment]
### Description
Viewer whitescreens if I change revision after selecting a group

### Steps to replicate
- Go to here: https://issue-5223.dev.3drepo.io/v5/viewer/QA_Static/6f256e3b-f9b4-49ad-93b2-f2c45d87e775/54545cae-60a4-44d4-862c-b32f2562418c
- Open a groups tab
- Select the groups
- Change revision

### Current Behaviour
white screens

### Expected Behaviour
Should change revision
### Pictures/ Gifs of the error

**Comment by sanmont3drepo** [comment]
- clipping is not available when calibrating. I think this comes from the design change that when you create a drawing there are default planes values.
image

**Comment by The-Daniel** [comment]
### Description

On the log in screen I believe the correct phrasing should be "Sign in to" instead of "Sign into"
https://linguix.com/english/common-mistake/sign_into#:~:text=The%20phrase%20%22sign%20into%22%20is,is%20%22sign%20in%20to%22.

### Pictures/ Gifs of the error
image

**Comment by carmenfan** [comment]
### Description
found after fixing https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422234278

The backend now respond with a filename, but it looks like frontend is overriding it with the status code and revision code:
image


### Steps to replicate
go to drawing list, download a revision

### Current Behaviour
the file is being downloaded as `<rev code>-<status code>`

### Expected Behaviour
the file should download with its original filename

**Comment by carmenfan** [comment]
> FYI for whoever's interested, I have pushed a unity viewer with a fix to test for [#5224 (comment)](https://github.com/3drepo/3drepo.io/pull/5224#issuecomment-2422479861), so you'll see the splash screen until its rebuilt (if the fix works!)

@sebjf  can you make a PR on the unity side so I can rebuild and merge if it's all good please ? thank you 😄

**Comment by The-Daniel** [comment]
### Description

Dragging the camera in the 2D viewer occasionally switches to dragging the picture instead.
I think this usually happens when dragging the camera outside the bounds of the drawing.

### Steps to replicate
Open a calibrated drawing in the viewer
Zoom out in the 2D viewer
Grab the camera and move it around outside of the drawing

### Current Behaviour
The dragged object will randomly change from the camera to the drawing

### Expected Behaviour
The dragged object remains the camera

### Pictures/ Gifs of the error

https://github.com/user-attachments/assets/0c1a3b2c-681a-493c-b6cf-21cd7a8daec0

**Comment by carmenfan** [comment]
### Description
Teamspace not found error is popping up when you update your profile

### Steps to replicate
- Go onto profile and edit surname
- Click save

### Current Behaviour
Profile saves correctly, but a error modeal about teamspace not found is popping up

Network tab indicates that we're trying to call teamspace members API for some reason:
image


### Expected Behaviour
Should not be calling members endpoint 

### Pictures/ Gifs of the e

rror

**Comment by carmenfan** [comment]
### Description
Error on group import is showing a modal with export groups in the text

### Steps to replicate
- trigger an error on the group import 

### Current Behaviour
- error modal is saying there's an error exporting the group

### Expected Behaviour
- should be error importing the groups

### Pictures/ Gifs of the error

**Comment by carmenfan** [comment]
### Description
Pin is disappearing on certain angle

### Steps to replicate
- Go here https://issue-5223.dev.3drepo.io/v5/viewer/5_12_qa/cf224468-e8ad-4de7-adfd-a018fcf953e7/06868893-c1e0-4c7f-a906-809c558dc925?drawingId=d97caafe-ada2-4ebb-b59e-df86b8ccc8a1&ticketId=3ccced35-05ff-4b07-8e6e-275f294553c4

- Observe the red pin on the roof

### Current Behaviour
At certain camera angles it's not showing up

### Expected Behaviour
It should always show

### Pictures/ Gifs of the error

**Comment by carmenfan** [comment]
io activity is not being recorded with the log saying `version conflict`
image

**Comment by carmenfan** [comment]
DWG exports are coming out really faint:

on this branch:
image

on my local:
image

**Comment by carmenfan** [comment]
### Description
viewer white screens when you try to calibrate a 2nd drawing

### Steps to replicate
- prepare 2 drawings
- go through the calibration on the first drawing (has to save, cancel doens't seem to trigger it)
- try to calibrate a 2nd drawing

### Current Behaviour
- viewer whitescreens

### Expected Behaviour
- should setup the wizard to let you calibrate the second drawing

### Pictures/ Gifs of the error

**Comment by carmenfan** [comment]
QA complete 
image

**Pull request merged**
