### PR TITLE
ISSUE #2231 - Fix updating of risks comments

### LINKED ISSUE #2231: Kanban Board Risk comments don't appear after submitting
### Description
When I open existing Risk Cards in Kanban board and submit a comment, they do not appear in the list. A user can get confused and submit several comments without realising. Once you close the risk and open it again you see the original comment or multiple comments if you were hoping it was going to work originally.

### Steps to replicate
- Open the Risk & Issues Board in 3D Repo
- Select any model/federation that contains Risks
- Add a comment to a risk
- Add several comments if they still don't appear in the comments list

### Pictures/ Gifs of the error
Risk Comments

### PR DESCRIPTION
**Pull request by m1chalkubiak**
This fixes #2231

### CODE REVIEW

**Comment by har00n-haider** [comment]
Looks good to me, can confirm the original issue does not happen on this branch build. 

There was a small side note about how the risk comments show up in the SafetiBase view as opposed to the "Issues & Risks" view. The scroll bar does not reset to the latest added comment as it does in the "Issues & Risks" view:

issue2231

**Comment by m1chalkubiak** [comment]
> There was a small side note about how the risk comments show up in the SafetiBase view as opposed to the "Issues & Risks" view. The scroll bar does not reset to the latest added comment as it does in the "Issues & Risks" view:

@carmenfan in fact, on the viewer page, this scrolling feature thas not work, I implemented it on kanban board page, but don't remember if we forgot to add it in the model view or if there was any particular reason why it cannot work there. Anyway, the question is do we want to improve it on the same PR or do we want to create a separate issue for it?

**Comment by carmenfan** [comment]
> > There was a small side note about how the risk comments show up in the SafetiBase view as opposed to the "Issues & Risks" view. The scroll bar does not reset to the latest added comment as it does in the "Issues & Risks" view:
> 
> @carmenfan in fact, on the viewer page, this scrolling feature thas not work, I implemented it on kanban board page, but don't remember if we forgot to add it in the model view or if there was any particular reason why it cannot work there. Anyway, the question is do we want to improve it on the same PR or do we want to create a separate issue for it?

@m1chalkubiak if it's not a massive change/task then it'd be great if we change it in here. Otherwise make a separate issue please :)

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak if it's not a massive change/task then it'd be great if we change it in here. Otherwise make a separate issue please :)

Of course, I will check if it is quickly doable, in case of problems I will let you know.

**Review by carmenfan — APPROVED** [review]

**Comment by m1chalkubiak** [comment]
Hi @carmenfan I think we were in too much of a rush with merging this PR, there was also the issue of the scroll, which I checked and it works in the model view, but you have to collapse the upper part of the ticket description. I think it makes sense because scrolling every time a new comment is added, even when we are currently trying to read or edit something in the ticket description, could be super irritating. However, I found one bug that shows up on this PR, when we add a comment to the issue, it appears twice, it is quite strange because I didn't make any changes to the issue itself. But I'm in the process of checking it out.

**Comment by carmenfan** [comment]
@m1chalkubiak  apologies! forgot about that!

It's now in staging, so if you can create another issue to fix those issues that'd be great

**Pull request merged**
