### PR TITLE
Issue 1177: Migration - User management

### LINKED ISSUE #1177: Migration: User management (main component)
#### Description
This issue includes migration of Users Management view and small clean up.

#### Goals
Migration of Users Management view to ReactJS

#### Tasks
- Migrate logic to React.js
- Move pug templates to JSX
- Move styles to styled components
- Add react-router to manage route visibility

### PR DESCRIPTION
**Pull request by simplypixi**
This fixes #1177 

#### Description
This PR should be merge after #1170 (PR #1176).

- Moved styles to styled components
- Bound new react dialog (federation reminder)
- Migrated User management view logic
- Refactored code
- Remove old (angular) components

### CODE REVIEW

**Comment by carmenfan** [comment]
#1170 is merged, i've changed this PR to merge into #1141 please rebase when you have a moment! :)

**Comment by simplypixi** [comment]
@carmenfan 
It was happening because of this:
image

I cleaned this part of code up. Now everything should be ok and state change handler should run even a bit faster.

**Comment by simplypixi** [comment]
@carmenfan Fixed! ;)

**Comment by carmenfan** [comment]
@simplypixi can we make it so the default tab is user unless the user doesn't have access to it? (project admin)?

**Comment by simplypixi** [comment]
> @simplypixi can we make it so the default tab is user unless the user doesn't have access to it? (project admin)?

Sure!

**Comment by simplypixi** [comment]
@carmenfan Fixed ;)

**Comment by carmenfan** [comment]
I'm not sure if this is worth fixing as it is probably related to the state manager and you'll be moving away from it. But when you do the following, the UI becomes blank:

1. Log in as User 1
2. Go to User Management tab
3. Log out
4. Log in as User 2
5. Go to User Management tab

One thing I notice is that the url doesn't have the `teamspace` querystring when it usually do
filter

Looks good otherwise. I've approved this PR, so if you think this will soon be redundant and not worth fixing then feel free to merge this in.

**Comment by simplypixi** [comment]
> I'm not sure if this is worth fixing as it is probably related to the state manager and you'll be moving 

I checked this bug and... yes, it's state manager. I'll removed whole manager during migration to new routing, so the issue will resolve too.

**Comment by simplypixi** [comment]
@carmenfan Fixed.

**Pull request merged**
