### PR TITLE
Issue 3231 - Viewer facelift - Tree Card

### LINKED ISSUE #3231: Viewer facelift - Tree Card
### Description
We need to revamp the Tree card to match v5 styles

### Goals
- [ ] To have the Tree card styled like v5 

### Tasks
- [ ] Just follow the styles in the mockup

### Related Resources
[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136292%3A177725)

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #3231

#### Description
Fixed the styling

### CODE REVIEW

**Comment by george-hadfield** [comment]
### Row item missing selected state

Build
image

Design 
image

**Comment by carmenfan** [comment]
@george-hadfield ready for another look when the deployment is ready

**Review by sanmont3drepo — APPROVED** [review]

**Pull request merged**
