### PR TITLE
Issue 963 - Keep panel menu open and fix some minor UX issues 

### LINKED ISSUE #963: Panel menu shouldn't close on click of a child button
### Goals
Make sure that the panel menu doesn't close when you click a button inside of it

### Tasks
Stop the menu from closing

### PR DESCRIPTION
**Pull request by JamesMilnerUK**
This fixes #963 

#### Description
The menu shouldn't close when you click on a button

#### Test cases
Open the menu, select buttons
Change the direction of the sort by date button

### CODE REVIEW

**Comment by JamesMilnerUK** [comment]
Should all be fixed minus filtering out issues with no job. I'll create a separate issue for that

**Comment by carmenfan** [comment]
didn't work on mine... 
image

**Comment by JamesMilnerUK** [comment]
@carmenfan I think the over sizing of the panel is fixed

**Comment by carmenfan** [comment]
Still showing my teamspace's jobs when I go to pavol's (after loading my own):
image

**Pull request merged**
