### PR TITLE
ISSUE #2973 add nwd support

### LINKED ISSUE #2973: NWD support
### Description
pairing issue for https://github.com/3drepo/3drepobouncer/issues/518

We need to allow nwds to go through the web service

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #2973

### Bugs

- [ ] [Model Tree in Branch does not match Prod / Plugin](https://github.com/3drepo/3drepo.io/pull/2974#pullrequestreview-869423073)
- [ ] [Selection Behaviour in Branch does not match Prod / plugin](https://github.com/3drepo/3drepo.io/pull/2974#issuecomment-1027048023)

#### Description
- allow nwd extensions on uploads

#### Test cases
- `.nwd` files should be accepted through model upload

### CODE REVIEW

**Comment by carmenfan** [comment]
@mosment3DRepo ready for testing

**Review by miadibe — COMMENTED** [review]
### 1. Model Tree in Branch does not match Prod / Plugin
Model tree structure has different parents/children hierarchy in all uploaded file formats: DWG, DXF, DGN, RVT and NWD.

**Steps to replicate**
- Upload models to branch and prod (plugin to branch for the formats not yet supported in prod). Models found here: [https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Product/3D%20Models/ODA%20Testing/220128](url)
- Open Tree card and observe changes between model in branch and model in prod

**Pictures/ Gifs of the error**
_Example screenshot_
dwg_tree
More screenshots of the results found here: [https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Product/3D%20Models/ODA%20Testing/220128](url)
Also full report found here: [https://coda.io/d/3D-Repo-Product-Management_dPKjhWeEmM9/ODA-Testing_sultb#_lu-Dt](url)

**Comment by miadibe** [comment]
### Selection Behaviour in Branch does not match Prod / plugin
Model tree structure is different. Consequently, discrepancy in object selection is observed for all formats DWG, DXF, DGN, RVT and NWD.

**Steps to replicate**
- Upload models to branch and prod (plugin to branch for the formats not yet supported in prod). Models found here: [https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Product/3D%20Models/ODA%20Testing/220128](url)
- Select some objects and observe single (plugin/prod) vs multiple selection (branch) issues

**Pictures/ Gifs of the error**
_Example screenshot_
nwd2022_selection
More screenshots of the results found here: [https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Product/3D%20Models/ODA%20Testing/220128](url)
Also full report found here: [https://coda.io/d/3D-Repo-Product-Management_dPKjhWeEmM9/ODA-Testing_sultb#_lu-Dt](url)

**Comment by miadibe** [comment]
### 3. Inconsistent Metadata schema in BIM card
This is mostly visible for some elements in RVT files.

**Steps to replicate**
- Upload models to branch and prod (plugin to branch for the formats not yet supported in prod). Models found here: [https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Product/3D%20Models/ODA%20Testing/220128](url)
- Open BIM card, select some objects and compare metadata. _i.e: Material and Finishes + Head Height fields (for RVT uploads)_
_I made @carmenfan and @sebjf as Teamspace admins to my teamspace (miaTemp and mia_dibe), you'll find all the models in Prod and Branch uploaded in the project called **Navis Support**_

**Pictures/ Gifs of the error**
_Example screenshot_
rvt2021_selection behaviour 2
More screenshots of the results found here: [https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Product/3D%20Models/ODA%20Testing/220128](url)
Also full report found here: [https://coda.io/d/3D-Repo-Product-Management_dPKjhWeEmM9/ODA-Testing_sultb#_lu-Dt](url)

**Comment by miadibe** [comment]
@mosment3DRepo more minor comments raised on Coda. I'll add them only if needed

**Comment by sebjf** [comment]
Hi @miadibe, thank you for the reports!

I am just looking at the NWD example above, and see something strange, in that when I look at it on 2973 I don't get the double selection..

image

(The above is from this morning just now)

Am I looking at the right model/version?

**Comment by sebjf** [comment]
@miadibe, also, are there any DXF/DWG/DGNs with multiple levels to the hierarchy? Or are they all one set of layers, with each layer having one or more meshes, but no more layers?

**Comment by sebjf** [comment]
Hi @mosment3DRepo 

To summarise my understanding of the tests:

1. The Drawings SDK (DWG, DGN, DXF) have severe issues with the hierarchy changing. This also affects partial meshes, which result in selection issues.

2. The existing Revit versions (2020, 2021) are OK. The BIM cards have slightly different parameters due to (mostly good) changes in ODA. The default tessellation settings have changed.

3. The new Revit import has a different hierarchy to the Plugin. Both are 'correct', but the plugin has additional groupings that are not reflected in the ODA import.

4. There is a single selection issue for NWD 2022 (see above).


From the above,

1. Needs to be fixed
2. Is OK
3. I am not sure?
4. Being discussed above.

Is that right?

**Comment by sebjf** [comment]
Hi @carmen,

A quick update,

I have a possible explanation for the Drawings. [This](https://github.com/3drepo/3drepobouncer/blob/982200044b228a7e6f16fafe4096655b4d02dd2a/bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_dgn.cpp#L92) loop in `doDraw` attempts to find the penultimate root the hierarchy, and set the mesh group by its Id.

I suspect that ODA have changed something meaning the `ownerId` is no longer null when expected. For example, they've added a new virtual root node for all elements. This results in the meshes being combined.

It is interesting that the 'faulty' Id in a couple of examples across files has the handle `[11]`.

In Mia's DGN example, this is the handle of the element returned by the `OdGiSubEntityTraitsData::layer()` member, which is used to set the layer, hence the treatment of the entries as partial mesh objects.

Could it be the case that before the elements had a level but were not parented to it, and now they are (parented to it)?

As a test I just ignored this and set the group Ids to the actual element Ids, leaving the Layer name returned from the level.

```	
std::string groupID = convertToStdString(toString(pElm->elementId().getHandle()));
```

This fixes the issue in that on the test models the meshes are no longer combined incorrectly. 

image

However it still doesn't match production because now some meshes that should be combined are not.

image

I am building the production version of bouncer to compare the behaviour of the the loop.

**Comment by sebjf** [comment]
Hi @carmenfan @mosment3DRepo,

I have modified onDraw to check the element type when deciding to terminate the traversal to find the group root. This appears to fix the Drawing issues. 

I have added to 528 and merged to 518.

**Comment by carmenfan** [comment]
@mosment3DRepo  @miadibe 

Can we get a confirmation about this https://github.com/3drepo/3drepo.io/pull/2974#issuecomment-1033618057

sounds like @sebjf has done 1. if we need any of the others addressed (maybe 4?) then i think he needs some input 

If this is all we need then I need to grab keif's attention to update the branch so you guys can try again

**Comment by mosment3DRepo** [comment]
> Hi @mosment3DRepo
> 
> To summarise my understanding of the tests:
> 
> 1. The Drawings SDK (DWG, DGN, DXF) have severe issues with the hierarchy changing. This also affects partial meshes, which result in selection issues.
> 2. The existing Revit versions (2020, 2021) are OK. The BIM cards have slightly different parameters due to (mostly good) changes in ODA. The default tessellation settings have changed.
> 3. The new Revit import has a different hierarchy to the Plugin. Both are 'correct', but the plugin has additional groupings that are not reflected in the ODA import.
> 4. There is a single selection issue for NWD 2022 (see above).
> 
> From the above,
> 
> 1. Needs to be fixed
> 2. Is OK
> 3. I am not sure?
> 4. Being discussed above.
> 
> Is that right?

Correct, for #3 I am happy to leave as is for now

**Comment by carmenfan** [comment]
@miadibe  @mosment3DRepo  ready for a re-test

**Comment by miadibe** [comment]
Great thanks Carmen and Sebastian. I'll test again this afternoon

**Review by mosment3DRepo — APPROVED** [review]
- Tree for RVT, DWG, DGN and DXF now resolved. 
- No more double selection of elements.
- Correct model object counts as per previous ODA version
- Outstanding discrepancies with Plugin will be covered as a separate issue (not release critical)

**Pull request merged**
