### PR TITLE
Issue 3034 - 4.22.0 release candidate

### LINKED ISSUE #3034: 4.22.0 release
### Description
This issue is to cut a certain point in staging to become v4.22.0

So we can QA and address any bug fixes without extra features being merged in.

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #3034

#### Description
Release of all features/fixes implemented in 4.21 development cycle
- [4.21.0](https://github.com/3drepo/3drepo.io/milestone/225?closed=1)
- [4.21.1](https://github.com/3drepo/3drepo.io/milestone/226?closed=1)
- [4.21.2](https://github.com/3drepo/3drepo.io/milestone/227?closed=1)
- [4.21.3](https://github.com/3drepo/3drepo.io/milestone/228?closed=1)
- [4.21.4](https://github.com/3drepo/3drepo.io/milestone/229?closed=1)

3drepobouncer: [4.21.0](https://github.com/3drepo/3drepobouncer/milestone/111?closed=1) [4.21.1](https://github.com/3drepo/3drepobouncer/milestone/111?closed=1)
3drepounity: [4.21.0](https://github.com/3drepo/3drepounity/milestone/81?closed=1)

Plugins to go along with this release:
https://www.dropbox.com/sh/s95bi6onjzuf8yg/AAB9RXbFeW40Mz1XCc-IBVj3a?dl=0

---

### Bugs
- [ ] <del> [1. Model Container fails to be deleted](https://github.com/3drepo/3drepo.io/issues/3059#issuecomment-1047099374) </del>Wont' fix - see [here](https://github.com/3drepo/3drepo.io/pull/3035#issuecomment-1048711399)
- [x] [2. Map tiles are not running](https://github.com/3drepo/3drepo.io/issues/3059#issuecomment-1047109036)

### UI Oddities
- [ ] [Base/Compare/Target slider](https://github.com/3drepo/3drepo.io/pull/3035#issuecomment-1048090652) - Known issue since 4.19.2 #2854 
- [ ] [Group Description text in Groups card](https://github.com/3drepo/3drepo.io/pull/3035#issuecomment-1048665417)

### CODE REVIEW

**Comment by miadibe** [comment]
### 3. UI Oddity: Base/Compare/Target slider
Slider does not appear in the Compare card as expected when another card is opened. Appears to stay in the initial place instead of moving with the card. 

### Steps to replicate
- Open the compare card for any model
- Run 3D diff or Instant clash and keep the session active without deactivating the orange button
- Open another card (i.e. views) 

### Current Behaviour
- The slider works functionality but does not appear at the right place

### Expected Behaviour
- Slider should be attached to the compare card

### Pictures/ Gifs of the error
[Link to video](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Product/Support/GitHub%20Issues/Videos/3.%20UI%20oddity.mp4)

**Comment by miadibe** [comment]
### 4. UI Oddity: Group Description text in Groups card 
When description text is longer than a line, text doesn't wrap up. This is not the case for other cards like Issues or Risks

### Steps to replicate
- Create a group or edit an existing one
- Write a description text longer than 1 line and save the group
- Go back to the groups card

### Expected Behaviour
- Wrap description text like in the Issues/Risks cards

### Pictures/ Gifs of the error
groups ui risks
groups ui

**Comment by carmenfan** [comment]
> @carmenfan I can't edit your initial comment to add the UI bug link

I'll add it dw

**Comment by carmenfan** [comment]
> ### 3. UI Oddity: Base/Compare/Target slider
> Slider does not appear in the Compare card as expected when another card is opened. Appears to stay in the initial place instead of moving with the card.
> 
> ### Steps to replicate
> * Open the compare card for any model
> * Run 3D diff or Instant clash and keep the session active without deactivating the orange button
> * Open another card (i.e. views)
> 
> ### Current Behaviour
> * The slider works functionality but does not appear at the right place
> 
> ### Expected Behaviour
> * Slider should be attached to the compare card
> 
> ### Pictures/ Gifs of the error
> [Link to video](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Product/Support/GitHub%20Issues/Videos/3.%20UI%20oddity.mp4)

This is a known issue since 4.19.2 https://github.com/3drepo/3drepo.io/issues/2854

**Comment by carmenfan** [comment]
@miadibe 

This one: https://github.com/3drepo/3drepo.io/issues/3059#issuecomment-1047099374

@ChristosTsiotsias  has identified that this is failing because it appears to have revisions that are produced by the [metadata schema branch](https://github.com/3drepo/3drepo.io/pull/2876) - i.e. you created that federation in that deployment, or someone has ran a migration script on it.

Metadata branch has breaking schema changes, hence we do not expect any model revisions produced by that branch to be compatible with the release candidate (and vice versa). So this is not really a bug that a customer would run into it will naturally fix itself when metadata schema branch has merged in and we've ran the migration script.

**Pull request merged**
