### PR TITLE
Issue 2236 - Defined ids for html elements 

### LINKED ISSUE #2236: Walkme: Add unique ids to frontend elements to be able to id them in walkme
### Description
Add ids as described in  https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Support/Walkthrough?preview=3D+Repo+Element+Naming+Requirement.pptx

### Tasks
The following elements should have a unique id.

In the viewer:
- [x] Each button on the left bar.
- [x] Each card
- [x] Each card with opened details
- [x] Each 'add-new' button in each card
- [x] 'save' button in groups
- [x] 'add comment' buttons in issues and risks
- [x] The div that contains all the add measurements in measurements
- [x] 'save' button when creating a new issue/risk
- [x] 'save' button in views
- [x] Each button  on the top right
- [x] The entire bottom toolbar

In the dashboard:
- [x] Each teamspace in models & federations
- [x] Each project for each teamspace
- [x] Each model area for each project

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #2236 

#### Defined ids
image

image

image

### CODE REVIEW

**Review by carmenfan — APPROVED** [review]

**Comment by carmenfan** [comment]
code looks fine, just need @3drepo/product-team to check whether they can do what they need with it!

Can merge once they approve

**Comment by mosment3DRepo** [comment]
still waiting on WalkMe to restate license, review scheduled for wc 19/10/2020

**Review by mosment3DRepo — APPROVED** [review]
Approved subject to global QA check before release

**Comment by carmenfan** [comment]
@mosment3DRepo if you want the ID tags for presenter mode as well then it might be worthwhile to let @m1chalkubiak whilst he's still working on it.

**Pull request merged**
