### PR TITLE
ISSUE #3290 -  Extra space needed below the last row on Teamspaces screen

### LINKED ISSUE #3290: Extra space needed below the last row on Teamspaces screen
image

This spacing should be equal to the top spacing (150px approx). It might also be good to fade out the 'Welcome, <name>!' on scroll so it doesn't ever need to tuck under the nav which may look odd

### PR DESCRIPTION
**Pull request by The-Daniel**
This fixes #3290 

#### Description
- adds spacing below teamspace list
- Welcome message fades out on scroll
- Also fixed a bug where navigating to teampsace dashboard from the user modal whilst in the viewer instead took you to `/v5/viewer`

#### Test cases
- View teamspace dashboard with different screen sizes

### CODE REVIEW

**Comment by george-hadfield** [comment]
The welcome message isn't fading out for me

**Comment by The-Daniel** [comment]
> The welcome message isn't fading out for me

hmm you're right. I'll see why it's only working locally

**Review by george-hadfield — CHANGES_REQUESTED** [review]
Once welcome message is fading out, this can be approved

**Comment by The-Daniel** [comment]
Try again now @george-hadfield. Let me know if you want to change the animation speed/trigger point. I can also quite easily make the text move up as it fades away too

**Comment by george-hadfield** [comment]
Thanks @The-Daniel - can you make it a bit smoother so it starts to fade as soon as your scroll and gradually disappears?

**Pull request merged**
