### PR TITLE
ISSUE #2296 - UI fixes

### LINKED ISSUE #2296: UI fixes
### Description
A list of small UI improvements to be attended to TBD

- [ ] [_Last Updated_ field in the group's card is inconsistent](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728224487)
- [x] [Long view names should have a full name presented on hover (like with the model tree elements)](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728224563)
- [x] [Peculiar behaviour discovered when editing federations right after the model name change](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728224663)
- [ ] [Edit measurement's name icon is poorly positioned](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728224858)
- [x] [Federation Name Limit is now showing up as a warning message](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728224978)
- [x] [Model Name limit message is confusing](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-728225108)
- [x] [The CV is eclipsing the treatment file name when it is too long](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-732206803)
- [x] [Autosuggestions positioning issue during filtering list](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-733039102)
- [x] [Add a character limit for Job titles](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-732247270)
- [x] [Add options menu with base options in Views Card](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-733044366)
- [x] [Auto-populated revision name should truncate to the max character length](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-739870509)
- [x] [Limit Job role character length to 50](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-739973466)
- [x] [Increase revision name limit to 50 on the UI](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-739973466)
- [ ] [Increase revision name limit to 50 on the backend/API](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-739973466)
- [x] [Ticket Screenshot update during an edition of pin cause disappearing of an edited pin (both Risks & Issues).](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-733689500)
- [x] [Fix styling of the tabs on issues card](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-733766046)
- [x] [Reset viewerGUI state after leaving model](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-735797649)

### PR DESCRIPTION
**Pull request by m1chalkubiak**
This fixes #2296

Bug List:
- [x] [Unable to add new jobs to a project](https://github.com/3drepo/3drepo.io/pull/2358#issuecomment-747763069)
- [x] [Issues & Risks "Attachment" tab doesn't activate once Issue/RIsk is saved](https://github.com/3drepo/3drepo.io/pull/2358#issuecomment-747768655)
- [x] [If you add a Risk pin and save the risk before saving the pin, you get an error message](https://github.com/3drepo/3drepo.io/pull/2358#issuecomment-747768876)

### CODE REVIEW

**Comment by m1chalkubiak** [comment]
Hi @carmenfan can You please take a look at this? I'm not exactly sure why Travis is failing and if any of my changes could be the cause of that.

**Comment by keifgwinn** [comment]
I think it might be a render speed thing, the image decoded looks like the wrong login is doing the right thing, but it's also slightly transparent which is causing it to not recognise it. 

image

**Comment by m1chalkubiak** [comment]
> I think it might be a render speed thing, the image decoded looks like the wrong login is doing the right thing, but it's also slightly transparent which is causing it to not recognise it.

Hi @keifgwinn Can we try to run these tests again? I don't think any of the changes I made could affect how quickly this modal appears.

**Comment by carmenfan** [comment]
@m1chalkubiak  it's fine, it breaks a lot 😆 ...

**Comment by mosment3DRepo** [comment]
[Limit Job role character length to 50](https://github.com/3drepo/3drepo.io/issues/2296#issuecomment-732247270 ) seems to not be working correctly, unable to add any new jobs:

image

**Comment by mosment3DRepo** [comment]
### Description
Issues & Risks "Attachment" tab doesn't activate once Issue/RIsk is saved

Expected behaviour: Once issue is save the attachment tab should be valid and allow you to attach things

### GIF
NoAttachment

**Comment by mosment3DRepo** [comment]
### Description
If you add a Risk pin and save the risk before saving the pin, you get an error message

### GIF
pinSave

**Comment by m1chalkubiak** [comment]
Hi @mosment3DRepo 
Thank you for pointing out those cases. All mentioned issues should be now fixed. Please let me know if there is anything else to fix.

**Review by Charence — APPROVED** [review]

**Pull request merged**
