### PR TITLE
ISSUE 4083 - Fix BCF import/export

### LINKED ISSUE #4083: Unable to import .bcf's into model containers or federations
Description
This bug is seen when trying to import a .bcf file to either a model container or a federation. When trying to import the .bcf to a container model, the message 'uploading BCF' appears  but no issues are uploaded. 
When trying to import the same .bcf file into a federation, 'Internal Error Status Code: 500 error message appears. 

This bug is occurring in: Production
This requires a hotfix to production: TBD

Steps to replicate

- Create an issue in [this](https://www.3drepo.io/v5/viewer/Faisal_Ramady/f4770170-c0ef-11ed-8253-5f6c87107c4e/d1fb3d50-c0f4-11ed-b39e-b9454b38bb98) model 

- Export issue as .bcf 

- import .bcf to [this](https://www.3drepo.io/v5/viewer/Faisal_Ramady/f4770170-c0ef-11ed-8253-5f6c87107c4e/079e6ae0-c0f0-11ed-b39e-b9454b38bb98) model 

- import .bcf to [this](https://www.3drepo.io/v5/viewer/Faisal_Ramady/f4770170-c0ef-11ed-8253-5f6c87107c4e/432f4d00-c0f4-11ed-b39e-b9454b38bb98) federation

### PR DESCRIPTION
**Pull request by Charence**
This fixes #4083

#### Description
- Resolves blank BCF exports
- Resolves non-IFC GUID BCF imports
- Resolves hanging if error encountered on BCF import
  - NOTE: current behaviour is import process will be aborted and error thrown; alternatively, we could have it continue process remainder of BCF file?

#### Test cases
- Export BCF
- Import BCF

### CODE REVIEW

**Comment by carmenfan** [comment]
@Charence  can you add a test case in the v4 test suite for this

**Comment by Ramadyfm** [comment]
I can confirm Issue-4083 resolves this BCF import issue 

Tested creating an issue in [this](https://issue-4083.dev.3drepo.io/v5/viewer/Faisal_Dev/ce88ea80-c966-11ed-88ef-078aa7e31f1f/da49cbf0-c966-11ed-88ef-078aa7e31f1f)
container.
Tested importing an issue to [this ](https://issue-4083.dev.3drepo.io/v5/viewer/Faisal_Dev/ce88ea80-c966-11ed-88ef-078aa7e31f1f/0baff9d0-c967-11ed-adee-fb412e9c4e9b) container.
Tested importing an issue to [this](https://issue-4083.dev.3drepo.io/v5/viewer/Faisal_Dev/ce88ea80-c966-11ed-88ef-078aa7e31f1f/92dca970-c968-11ed-adee-fb412e9c4e9b) federation.

Note 
Is there any way we could also bring in the pins?

**Comment by carmenfan** [comment]
> Is there any way we could also bring in the pins?

Nope, BCF schema doesn't have pins (at least when we last checked it, it didn't)

We could store pins as bespoke fields inside the XML, but that's beyond the scope of fixing the bug

**Comment by Charence** [comment]
> Note
> Is there any way we could also bring in the pins?

At the moment we don't support pins (`position`) as it doesn't seem to be part of the BCF schema, but we could add an extra 3D Repo specific field to store it if there's a use case for exporting/re-importing to 3D Repo and we want to retain pins.

**Review by anorrie — APPROVED** [review]

**Review by carmenfan — APPROVED** [review]

**Pull request merged**
