### PR TITLE
ISSUE #2656 add dxf and dwg to list of file formats we accept

### LINKED ISSUE #2656: DWG support
### Description
Changes required on the webserver to support dwg/dxf files.

This issue is dependant on https://github.com/3drepo/3drepobouncer/issues/475

### Goals
- [ ] DWG files should get processed successfully
- [ ] DXF files should get processed successfully

### Tasks
- add dwg/dxf to the list of supported extensions

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #2656
#### Description
- add dxf and dwg to the accepted file format list

#### Test cases
- dwg/dxf should be allowed through the API

### CODE REVIEW

**Comment by mosment3DRepo** [comment]
### Capturing Property Set information

Civil 3D can capture Property Set information against model elements. At the moment these are not getting processed by 3D Repo.

Example model - [Dropbox Link](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/3D%20Models/DWG%20Free%20models?preview=3D-House_with_PSet.dwg)

{3D Repo Link)[https://issue-2656.dev.3drepo.io/viewer/internal_3DRepo/6d292680-dd8e-11eb-ab91-238449c8f689)
image


Civil 3D Screenshot
image

**Review by mosment3DRepo — CHANGES_REQUESTED** [review]
Review required to see if Property Sets are available

**Comment by carmenfan** [comment]
> ### Capturing Property Set information
> Civil 3D can capture Property Set information against model elements. At the moment these are not getting processed by 3D Repo.
> 
> Example model - [Dropbox Link](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/3D%20Models/DWG%20Free%20models?preview=3D-House_with_PSet.dwg)
> 
> [3D Repo Link](https://issue-2656.dev.3drepo.io/viewer/internal_3DRepo/6d292680-dd8e-11eb-ab91-238449c8f689)
> image
> 
> Civil 3D Screenshot
> image

@mosment3DRepo 
had a look and I can't really find any data in the oda debug app.
I also tried to open this file with vanilla AutoCAD and i don't see the property sets. I'm guessing we need the civils SDK to get the data https://www.opendesign.com/products/civil

**Comment by mosment3DRepo** [comment]
> > ### Capturing Property Set information
> > Civil 3D can capture Property Set information against model elements. At the moment these are not getting processed by 3D Repo.
> > Example model - [Dropbox Link](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/3D%20Models/DWG%20Free%20models?preview=3D-House_with_PSet.dwg)
> > [3D Repo Link](https://issue-2656.dev.3drepo.io/viewer/internal_3DRepo/6d292680-dd8e-11eb-ab91-238449c8f689)
> > image
> > Civil 3D Screenshot
> > image
> 
> @mosment3DRepo
> had a look and I can't really find any data in the oda debug app.
> I also tried to open this file with vanilla AutoCAD and i don't see the property sets. I'm guessing we need the civils SDK to get the data https://www.opendesign.com/products/civil

Yeah it does seem to be Civil specific. I assume the Civil product from ODA is an additional cost 

In that case are we able to at least bring the layer name in to the metadata so it can be used in smart groups and the BIM Card.

At the moment we use it in the tree to categorise the objects:
image

Could we have an attribute called "Layer" with the value of the parent?

**Review by mosment3DRepo — APPROVED** [review]
Approved in current state, additional functionality to be added in 4.20 to include Layer name in metadata

**Pull request merged**
