### PR TITLE
Issue 3411 - Groups details UI is a bit wonky

### LINKED ISSUE #3411: Groups details UI is a bit wonky
### UI Oddities

- [x] Text is overlapping when creating a group

> This bit will also address #3417. The form helper text "_This field is required_" has to be removed from the preview titles
image

- [x]  Field labels have inconsistent alignment

image

- [x]  Properties section can expand and collapse but has no icon

image

- [x]  Chevron for 'Operation' select field should be navy

image

- [x]  Group type text is too big

image

Should match the sizing of other dropdown text such as in issues

image

- [x] Border colours are different to issues

image

These should be consistent and match what's been done in issues 

- [x]  Set value colour is wrong. Should be the same as Set operation

image

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #3411 (and #3417)

#### Description
Fixed UI oddities in Groups card

### CODE REVIEW

**Comment by The-Daniel** [comment]
image
Long descriptions overflow behind bottom panel (for a smart group)

**Comment by The-Daniel** [comment]
image
The border seems to disappear on the bottom of the description box. It's weird, but I think it's to dow ith the height of the main parent element

**Comment by The-Daniel** [comment]
image
Error message appears behind text when description is long

**Comment by sanmont3drepo** [comment]
The spacing between the name of the group and the author seem to be gone.
In this branch:
image

in Staging:
image

**Comment by sanmont3drepo** [comment]
The size of the description textfield is not adjusting to the content of the field once is read only:
image

For context, I entered this value in the textfield:
```
sfsfsfsf




s
fs



```

**Review by sanmont3drepo — APPROVED** [review]

**Pull request merged**
