### PR TITLE
Issue 1387: Smart groups migration

### PR DESCRIPTION
**Pull request by dleszcz**
- Groups list https://github.com/3drepo/3drepo.io/issues/1386
- Group details https://github.com/3drepo/3drepo.io/issues/1387
- Remove Angular code

### CODE REVIEW

**Comment by simplypixi** [comment]
> * Delete is not removing the group from list until you refresh the page
> * Updated Groups are not being updated until refreshed
> * New group is not displayed on Group list until refreshed
@carmenfan Did you have ChatService enabled? Because response of create, update and delete are handle by this service. Should we handle these actions in two different ways? I mean, using http response and the chat service.

> Clicking on the rule chip should populate the rule editing area with the existing data
@dleszcz Did you change something here? It was working on the morning. :(

> None of the new groups are showing the created by user

@carmenfan Are you sure it is not an issue on backend side? I think we reported similar bug today, but we'll check it! ;)

**Comment by carmenfan** [comment]
> @carmenfan Are you sure it is not an issue on backend side? I think we reported similar bug today, but we'll check it! ;)

Does sound likely to be a backend bug since old groups is displaying... I'll have a look!

**Comment by simplypixi** [comment]
> @carmenfan Are you sure it is not an issue on backend side? I think we reported similar bug today, but we'll check it! ;)

@Charence BE returns old data on the response while saving/updating group.

image

image

**Comment by carmenfan** [comment]
@carmenfan Did you have ChatService enabled? Because response of create, update and delete are handle by this service. Should we handle these actions in two different ways? I mean, using http response and the chat service.

I know you deleted this but to answer your question - the user who created the item (and this applies to risks/issues/anything else as well) needs to get it updated by http. Reason being is that we know Chat service does not work for some of our clients due to corporate firewall, so at the very least the states of the app need to be sound without it for the user who's doing the work.

**Comment by simplypixi** [comment]
> > @carmenfan Did you have ChatService enabled? Because response of create, update and delete are handle by this service. Should we handle these actions in two different ways? I mean, using http response and the chat service.
> 
> @simplypixi
> I know you deleted this but to answer your question - the user who created the item (and this applies to risks/issues/anything else as well) needs to get it updated by http. Reason being is that we know Chat service does not work for some of our clients due to corporate firewall, so at the very least the states of the app need to be sound without it for the user who's doing the work.

Got it! ;)

**Comment by carmenfan** [comment]
**It no longer let me save until I alter the Description field:**
image

**Comment by carmenfan** [comment]
@simplypixi 

- The problem where the backend isn't giving you the updated info after a http put should be fixed
- The problem with user name not being shown should also be fixed. You no longer need to send `updatedBy` and `updatedAt` on your HTTP requests as that will be automatically generated based on session info/current time on server. (if you send it, it'll just be ignored)

**Comment by simplypixi** [comment]
> @simplypixi
> 
> * The problem where the backend isn't giving you the updated info after a http put should be fixed
> * The problem with user name not being shown should also be fixed. You no longer need to send `updatedBy` and `updatedAt` on your HTTP requests as that will be automatically generated based on session info/current time on server. (if you send it, it'll just be ignored)

Awesome! ;)

**Comment by carmenfan** [comment]
@simplypixi @dleszcz I've updated the backend so it now returns you sharedIDs on smart group post/put requests. The highlights are now showing :)

3 things:
1. To make this work, the backend needs to know what revision is the user currently viewing. So I've changed the end points to take in revision, i.e. instead of `/:teamspace/:model/groups/:groupid`, it's now `/:teamspace/:model/revision/:rid/groups/:groupid` or `/:teamspace/:model/revision/master/head/groups/:groupid` The old endpoint still works for backwards compatibility, but please change all your end point calls to this new one

2. When I was looking into this I realised groups had the url structure the wrong way round, it was putting `groups` before `revision` so I've now swapped them around (i.e. it was  `/:teamspace/:model/groups/revision/master/head/gid` instead of `/:teamspace/:model/revision/master/head/groups/gid` . I think I've changed all the frontend to the new version now. But please bear this in mind!

3. Now that it's showing the highlights, I found a bug. when you edit a smart group and click save, it is not removing the currently highlighted objects before it applies the new set:

**Comment by simplypixi** [comment]
@carmenfan We have a problem with the backend. Probably after the latest changes, because we have never noticed that before.
It doesn't appear on each model. We noticed that is happening on model: `viewer/subscriptionTest/9929074c-52f7-4ca5-8dbe-02894aec09a4`, when we where logged into `carmen` account. 

It's a memory leak, which is related to `buildRule` function in the group model.
Could you look at that?
image

**Comment by dleszcz** [comment]
@carmenfan @Charence 

One more error. Could you check it, please? It happens after group(normal) update.

screenshot 2019-03-06 at 09 27 09


FYI, Mariusz just updated URLs ;)

**Comment by carmenfan** [comment]
> 
> 
> @carmenfan @Charence
> 
> One more error. Could you check it, please? It happens after group(normal) update.
> 
> screenshot 2019-03-06 at 09 27 09
> 
> FYI, Mariusz just updated URLs ;)

This is fixed!

**Comment by carmenfan** [comment]
> -- EDIT --
> It seems to happen on each model with defined rules - which make sense :P
What do you mean by defined rules? Can you show me what the group looks like?

**Comment by simplypixi** [comment]
> > -- EDIT --
> > It seems to happen on each model with defined rules - which make sense 📦
> 
> @simplypixi
> What do you mean by defined rules? Can you show me what the group looks like?
> 
> EDIT: I think I know what you mean... I managed to reproduce it in the exists rule. Let me know if it's something else!

That's exactly what I meant. ;)

**Comment by carmenfan** [comment]
> 
> 
> > > -- EDIT --
> > > It seems to happen on each model with defined rules - which make sense 📦
> > 
> > 
> > @simplypixi
> > What do you mean by defined rules? Can you show me what the group looks like?
> > EDIT: I think I know what you mean... I managed to reproduce it in the exists rule. Let me know if it's something else!
> 
> That's exactly what I meant. ;)

Also fixed :)

**Comment by dleszcz** [comment]
@carmenfan We just finished fixing your requests :)

**Comment by carmenfan** [comment]
- [ ] `Number of objects` should only be showing what the group objects are, not the number of objects currently being highlighted (i.e. it should only change when user click save):


- [ ] Save button doesn't enable if I change the group name:


- [ ] Save button in smart group doesn't enable/disable like manual selection mode
image


- [ ] We need to disable override when we go into edit group (for that particular group), once the user exits, it should repaint the overrides:

This is what's happening in staging:


- [ ] it should be last update**d**, also can we please have the timestamp similar to the ones in risks?
image

- [ ] Overrides needs to clear when the group is deleted (there also seems to be some errors in the console):


- [ ] As a Viewer, I should not be able to edit existing groups. The description and group type are disabled, but I can still change colour and group name and try to submit my changes:

**Comment by simplypixi** [comment]
@carmenfan I have a small question. Should be the user able to add/select object, while the group is a smart group?

I think about that situation:
image

**Comment by carmenfan** [comment]
> @carmenfan I have a small question. Should be the user able to add/select object, while the group is a smart group?
> 

You should be able change the highlighting in the viewer (reset button will allow the user to see the original state should he needs to!), but upon save, it shouldn't try to save the selected ids if it's on the criterias type, it should only save the rules.

**Comment by paloknapo** [comment]
- [ ] Selecting chips doesn't always update filter fields


- [ ] Paste filters should create chips directly without user's CTRL+V


- [ ] Rename copy "Paste criteria" to "Paste filters"
image

- [ ] Show "Set filed" and "Set operation" in empty form fields
image

- [ ] Please change "Criteria" to "Smart" in Group type
image

- [ ] Please rename Criteria to Filters 
image

- [ ] Display number of objects in list view
image

- [ ] Scroll bar appears without good reason 


- Group type icon doesn't update

**Comment by simplypixi** [comment]
> * Paste filters should create chips directly without user's CTRL+V

@paloknapo @carmenfan We already discussed that. We are not able to implement a solution which behaves like native "paste" (with cross-browser compatibility), because of browser security reasons. We can't get into the clipboard if the user doesn't invoke paste event using a keyboard shortcut. That's why text input appears.

Nevertheless, there is an alternative, we can store data in local/session storage, but you lose cross-browser compatibility.

**Comment by dleszcz** [comment]
Hello @carmenfan,

According to Pavol's request:
> Display number of objects in list view

Are we able to extract this data based on the group object?

```
calculateTotalMeshes(group.objects); // ?
```
Will it always be the correct objects number value?

Because now we get this value on this way:
```
Viewer.getObjectsStatus();
calculateTotalMeshes(objectsStatus.highlightedNodes);
```

**Comment by simplypixi** [comment]
> * 2 filters with same operations are not allowed. If user tries this, Update button is disabled and message is displayed below: "Filter with this operation is already used"
>   image

I think we need to precise it a bit. :)  Do you mean two different filters whether two the same filters?

**Comment by carmenfan** [comment]
> Viewer.getObjectsStatus();
> calculateTotalMeshes(objectsStatus.highlightedNodes);
> ```

@dleszcz This asks the viewer the list of objects that it is currently highlighting, which should be correct if it is done immediately after highlighting the group (assuming you clear the highlgihts before you highlight the group)

This number should *theoretically* be the same as you accumulating the length of `shared_id` arrays withing `group.objects`

So for pavols' request you can just display the total of shared_id entries within the group's data.

**Comment by dleszcz** [comment]
Ok, thanks @carmenfan !

**Comment by carmenfan** [comment]
> @paloknapo @carmenfan We already discussed that. We are not able to implement a solution which behaves like native "paste" (with cross-browser compatibility), because of browser security reasons. We can't get into the clipboard if the user doesn't invoke paste event using a keyboard shortcut. That's why text input appears.
> 
> Nevertheless, there is an alternative, we can store data in local/session storage, but you lose cross-browser compatibility.

Yes, I don't think Pavol read that conversation. Just ignore this :)

**Comment by dleszcz** [comment]
@carmenfan @paloknapo @Charence fixes done

But, I found on more bug:
1. Go to some _smart_ group details
2. Change type to _normal_
3. Save

Backend returns group object with rules array, which causes the group type has not changed after the saving.

**Comment by carmenfan** [comment]
> @carmenfan @paloknapo @Charence fixes done
> 
> But I found on more bug:
> 
> 1. Go to some _smart_ group details
> 2. Change type to _normal_
> 3. Save
> 
> Backend returns group object with rules array, which causes the group type has not changed after the saving.

thanks! I'll look into it!

**Comment by carmenfan** [comment]
@dleszcz 

In the middle of fixing this, I found some problems:

Now that i've enforced that a group can only have either objects or rules but not at the same time, I can't update smart groups, as they're trying to send an empty object array:
image

- Also, I'm seeing override being toggled on everytime I enter the group:


- Finally, Can we make it say `1 object` when it's 1? or say` x object(s)`
image

**Comment by dleszcz** [comment]
> Can we make sure we only send objects or rules?
OK, sure 👍

**Comment by dleszcz** [comment]
@carmenfan I updated smart group without objects array, and then i got this:

Screenshot 2019-03-14 at 08 22 58

**Comment by simplypixi** [comment]
> * Now that i've enforced that a group can only have either objects or rules but not at the same time, I can't update smart groups, as they're trying to send an empty object array:

@carmenfan I'm wondering, why you not save the group type in the database. It's more convenient, isn't it? And more scalable - it'll be easier to add next group type in the future if you will came up with some new idea.
What do you think?

**Comment by carmenfan** [comment]
> @carmenfan I updated smart group without objects array, and then i got this:
> 
> Screenshot 2019-03-14 at 08 22 58

Sorry, that should be fixed

> @carmenfan I'm wondering, why you not save the group type in the database. It's more convenient, isn't it? And more scalable - it'll be easier to add next group type in the future if you will come up with some new idea.
What do you think?

@Charence  came up with the schema. So he's probably better positioned to answer why it's done that way. I think ti's fine to add a group type, but we'd still need to check arguments validity. It's not really for our own UI - we know it'll be doing the right thing, but there are customers trying to use direct API access so we need checks in place to make sure they're trying to do what they seem like they are trying to do :)

**Comment by carmenfan** [comment]
@dleszcz @simplypixi 

I've just commited some code to check the duplicate rule problem (i.e. multiple rules checking the  same field names) I used Postman to test it and i think it's working. But do let me know if you run into problems!

Will probably do some more commits in the new couple of days to add some backend tests, but it shouldn't affect you guys :)

**Comment by dleszcz** [comment]
hello again @carmenfan 
I tested switching between types and after changing from _smart_ to _normal_ i got this:

Screenshot 2019-03-14 at 14 14 50

no _shared_ids_ in objects item:
Screenshot 2019-03-14 at 14 14 19

**Comment by carmenfan** [comment]
@dleszcz I'm struggling to reproduce this. Can you tell me the steps you took to see this?

> no _shared_ids_ in objects item:
> Screenshot 2019-03-14 at 14 14 19

This is request payload... so you are sending a PUT request where object entries doesn't have `shared_ids`? that's invalid. If this is the case the error is correct. If there are no shared_ids within the model/submodel you're sending then it shouldn't have an entry (i.e. if you want to create an empty normal group, `objects: []`) In this case your group is indeed malformed.

**Comment by dleszcz** [comment]
@carmenfan 
1. I sent request with objects 
`[{account: "T_E_S_T"
ifc_guids: []
model: "0687ef98-52b8-4910-a211-4cef1cb7422c"
shared_ids: []}]`
2. In response i got objects:
`[{account: "T_E_S_T", model: "0687ef98-52b8-4910-a211-4cef1cb7422c"}]`
3. I sent request with some rules
4. In response i got rules AND OBJECTS:
`[{account: "T_E_S_T"
model: "0687ef98-52b8-4910-a211-4cef1cb7422c}]`
5. Then after PUT with these objects occur error

**Comment by carmenfan** [comment]
> @carmenfan
> 
> 1. I sent request with objects
>    `[{account: "T_E_S_T" ifc_guids: [] model: "0687ef98-52b8-4910-a211-4cef1cb7422c" shared_ids: []}]`
> 2. In response i got objects:
>    `[{account: "T_E_S_T", model: "0687ef98-52b8-4910-a211-4cef1cb7422c"}]`
> 3. Then I sent request with some rules
> 4. In response i got rules AND OBJECTS:
>    `[{account: "T_E_S_T" model: "0687ef98-52b8-4910-a211-4cef1cb7422c}]`
> 5. Then, after PUT with these objects i got an error **group request malformed**

I'm failing to reproduce this , I see the empty array on step 2:
image


Are you sure you're at the latest of this branch?

Also, you shouldn't be sending ifc_guids with your post/put request (probably doesn't hurt, but it shouldn't be there)

**Comment by dleszcz** [comment]
@carmenfan Yes, I am sure. Can you pull my last commit? It happens only when group dont have any objects

**Comment by carmenfan** [comment]
@dleszcz  sanity question - did you restart the server after you update?

I've updated, but I'm still struggling 😆 

step 1, i created an empty group, my payload looks different (and also response):
image

image

Then I change it to smart group and the payload and response is as follows:
image
image

Updating back to normal groups with the selected objects:
image

image




All working 😱

**Comment by carmenfan** [comment]
Unrelated note, When I try to delete all, I get an error:


And override all is automatically toggled if there's no groups:
image

Also, if override all is checked, when a new group is created, instead of unflagging override all, it should override the new group:



In conclusion, the override all boolean should only change if:
- User clicked on the button to toggle on/off
- Override all is on, and user clicked to turn off override in one of the groups

Otherwise, the state of the group should respect the override all property instead of changing it, unless we're currently editing that group. Hope this make sense 😆

**Comment by dleszcz** [comment]
:(

ezgif com-video-to-gif (1)

**Comment by carmenfan** [comment]
> :(
> 
> ezgif com-video-to-gif (1)

Ok I managed to reproduce it! 🎉  

I'll look into it lol

**Comment by carmenfan** [comment]
> > :(
> > ezgif com-video-to-gif (1)
> 
> Ok I managed to reproduce it! 🎉
> 
> I'll look into it lol

@dleszcz Fixed!

**Comment by dleszcz** [comment]
@carmenfan It works! ;) Also, I fixed your last requests related with deleting all and overriding groups.

**Comment by carmenfan** [comment]
> @carmenfan It works! ;) Also, I fixed your last requests related with deleting all and overriding groups.

Yay! I think it's pretty much there, so I'll get @sanmont3drepo to code review this and @paloknapo  to do a last User test

**Comment by carmenfan** [comment]
I've changed the target to staging as there isn't much point in merging it back to the old backend branch.

@dleszcz @simplypixi Can you solve the conflict? thanks!!

**Comment by paloknapo** [comment]
- [ ] Can't save smart group if it has lot of objects
image

- [ ] Please change override all icon
image

- [ ] Please update "more about RegEx" link to: 
https://3drepo.com/regex-for-data-validation/

**Comment by sanmont3drepo** [comment]
There is an error that's been thrown when you click on "reset to saved selection"

error reset

**Comment by simplypixi** [comment]
> There is an error that's been thrown when you click on "reset to saved selection"
> 
> error reset

@dleszcz I think we missed it during recent rebasing

**Comment by simplypixi** [comment]
> * [ ]  Can't save smart group if it has lot of objects.
>   image

**Comment by simplypixi** [comment]
> > * [ ]   Can't save smart group if it has lot of objects.
> >   image

@carmenfan  It's happening on backend side, isn't it?

**Comment by carmenfan** [comment]
@simplypixi yes definitely a backend bug, we'll look into it our side! :)

**Comment by simplypixi** [comment]
> @simplypixi yes definitely a backend bug, we'll look into it our side! :)

Cool! ;)

**Comment by simplypixi** [comment]
> There is an error that's been thrown when you click on "reset to saved selection"
> 
> error reset

Fixed! ;]

**Comment by simplypixi** [comment]
@carmenfan 

PR will be ready when you fixed backend. ;)🤞

**Comment by carmenfan** [comment]
image

scroll bar is fixed in staging (from https://github.com/3drepo/3drepo.io/issues/1395) but it's not in here :(

**Comment by dleszcz** [comment]
> scroll bar is fixed in staging (from #1395) but it's not in here :(
Our scrolling group details issue fix was the reason... 👎 
Repaired.

**Comment by sanmont3drepo** [comment]
- [ ] When I click on the background it doesn't deselect the already selected mesh

error deselect

**Comment by dleszcz** [comment]
@sanmont3drepo your request fixed

**Pull request merged**
