### PR TITLE
ISSUE #4301 - Fixed edit pin not working

### LINKED ISSUE #4301: Not able to edit the location of a issue or safetibase pins
### Description
No longer able to edit positions of issue or safetibase pins 

- This is happening in: production 
- This requires a hotfix to production: no

### Steps to replicate
- Open this model: [here](https://www.3drepo.io/v5/viewer/Faisal_Ramady/fbdde3f0-4df6-11ed-9d86-577ac9033907/2751e730-5161-11ed-9d86-577ac9033907) 
- Click on any created issues or risks and try to edit their pin locations

### Current Behaviour
- Not able to edit the location of saved pins

### Expected Behaviour
- Should be able to edit saved location of pins

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #4301

#### Description
- Fixed edit pin
- Fixed some bad selectors that added the pin twice
- Fixed some pin selection weirdness

### CODE REVIEW

**Comment by Amantini1997** [comment]
This was bug already there, but I am not sure whether part of this PR was to fix it.
Custom tickets pins do not update until the camera position changes

https://github.com/3drepo/3drepo.io/assets/43547703/c892b800-ac78-4e64-bdb4-83a6800a0a5d

**Comment by sanmont3drepo** [comment]
> This was bug already there, but I am not sure whether part of this PR was to fix it. Custom tickets pins do not update until the camera position changes
> 
>  Registrazione.2023-07-10.170502.mp4

Im unable to reproduce it it , can you reproduce it @The-Daniel @carmenfan ?

**Comment by The-Daniel** [comment]
> > This was bug already there, but I am not sure whether part of this PR was to fix it. Custom tickets pins do not update until the camera position changes
> > Registrazione.2023-07-10.170502.mp4
> 
> Im unable to reproduce it it , can you reproduce it @The-Daniel @carmenfan ?

I'm also unable to reproduce. However I've found what I think is another bug.
If you have a required pin and delete it, and then update any other field the pin will undelete itself.

**Comment by sanmont3drepo** [comment]
> > > This was bug already there, but I am not sure whether part of this PR was to fix it. Custom tickets pins do not update until the camera position changes
> > > Registrazione.2023-07-10.170502.mp4
> > 
> > 
> > Im unable to reproduce it it , can you reproduce it @The-Daniel @carmenfan ?
> 
> I'm also unable to reproduce. However I've found what I think is another bug. If you have a required pin and delete it, and then update any other field the pin will undelete itself.

That's unrelated to this branch. That should be fixed or changed in the pin input property.

**Review by Amantini1997 — APPROVED** [review]

**Pull request merged**
