### PR TITLE
ISSUE #1976 - Add missing fields in risks filters

### LINKED ISSUE #1976: Safetibase search is missing the new fields
new fields added from v3 isn't on the chip search
image

Also, we're calling `/:ts/mitigation/criteria` every time we enter a risk detail. This field doesn't change and we're making too many database read for no a lot of reason. I think making the change to support search will avoid that as we will call this api at initialisation. But something to bear in mind!

### PR DESCRIPTION
**Pull request by m1chalkubiak**
This fixes #1976

#### Description
- As suggested call for `/:ts/mitigation/criteria` were moved to initialization of risk panel
- Additional filters were added base on `/:ts/mitigation/criteria` endpoint data

### CODE REVIEW

**Comment by m1chalkubiak** [comment]
@carmenfan 
Fixed the same filters that are loaded for the risk panel search are now also used in the kanban board for risks, previously I missed it.

**Comment by carmenfan** [comment]
@m1chalkubiak  associated activity list is showing the risk factor data:



Can we also make the list scrollable? As demostrated on the gif the dropdown is getting cut off

**Comment by m1chalkubiak** [comment]
@carmenfan 
Now it should be scrollable if there will be a need.

**Comment by carmenfan** [comment]
> @carmenfan
> Now it should be scrollable if there will be a need.

@m1chalkubiak awesome thanks! Is this also addressed?

> @m1chalkubiak associated activity list is showing the risk factor data:

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak associated activity list is showing the risk factor data:

@carmenfan I just pushed a fix for this

**Review by carmenfan — APPROVED** [review]

**Pull request merged**
