### PR TITLE
ISSUE 2886 - implement delete federation

### LINKED ISSUE #2886: Revamping - Delete Federation modal
### Description
For deleting federation there should be a popup acccesible through the menu in the item.

### Goals
- [ ] Users with permissions can trigger the popup for deleting the federation
- [ ] A backend call should take place and delete the federation

### Tasks
- [ ] Create the popup using the popup system and follow the ui 
- [ ] Add delete endpoint to api service
- [ ] Add redux/saga action for deleting the federation
- [ ] Add frontend test for the saga

###  Considerations 
Base this of https://github.com/3drepo/3drepo.io/issues/2883

### Related Resources
MockUp : https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3329%3A49276
Delete container endpoint issue: https://github.com/3drepo/3drepo.io/issues/2769

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #2886

#### Description
Created modal to delete a federation
Added delete endpoint to API service
Added redux/saga action for deleting the federation
Added frontend tests for the saga

### CODE REVIEW

**Comment by george-hadfield** [comment]
@Amantini1997 just need the URL to test

**Comment by Amantini1997** [comment]
> I received this error window when trying to delete - is that expected?
> 
> image

It should not. The code error at the bottom denotes is an issue with the server. I tried to replicate it on my device and I did not get the error. Let me ask @sanmont3drepo

**Comment by sanmont3drepo** [comment]
> > I received this error window when trying to delete - is that expected?
> > image
> 
> It should not. The code error at the bottom denotes is an issue with the server. I tried to replicate it on my device and I did not get the error. Let me ask @sanmont3drepo

Maybe  @george-hadfield  don't have admin permissions for deleting that federation?

**Comment by keifgwinn** [comment]
@george-hadfield had some strange data in that fed he chose to delete

{"level":"error","message":"Unrecognised external service: http ","timestamp":"2022-01-19T16:13:13.656Z"}
16:13:13.657
{"level":"error","message":"Unrecognised error code {\"message\":\"File is stored an unrecognised storage type\",\"status\":500,\"code\":\"UNRECOGNISED_STORAGE_TYPE\",\"value\":190}","timestamp":"2022-01-19T16:13:13.657Z"}
16:13:13.657
{"label":"NET","level":"info","message":"{\"status\":500,\"code\":\"UNKNOWN\",\"latency\":\"34\",\"contentLength\":231,\"user\":\"ghadfield\",\"method\":\"DELETE\",\"originalUrl\":\"/api/v5/teamspaces/ghadfield/projects/88ca0650-2070-11ec-92db-f3ce04003eea/federations/88dfff50-2070-11ec-92db-f3ce04003eea\"} ","timestamp":"2022-01-19T16:13:13.657Z"}
16:13:13.694
{"level":"info","message":"File removed: \"47/171/4ad1ad65-f085-4e76-8e62-23911937a566\"","timestamp":"2022-01-19T16:13:13.694Z"}
16:13:13.694
{"level":"info","message":"File removed: \"205/18/6fc42b68-e014-48d5-86dd-34d83d52e113\"","timestamp":"2022-01-19T16:13:13.694Z"}
16:13:13.695
{"level":"info","message":"File removed: \"64/223/133e22ee-4181-47d4-afff-5c6642b64177\"","timestamp":"2022-01-19T16:13:13.695Z"}
16:13:13.695
{"level":"info","message":"File removed: \"160/233/64b23ae9-a4c9-4bd6-99bf-9e0c4d106e83\"","timestamp":"2022-01-19T16:13:13.695Z"}

**Comment by carmenfan** [comment]
> > > I received this error window when trying to delete - is that expected?
> > > image
> > 
> > 
> > It should not. The code error at the bottom denotes is an issue with the server. I tried to replicate it on my device and I did not get the error. Let me ask @sanmont3drepo
> 
> Maybe @george-hadfield don't have admin permissions for deleting that federation? @carmenfan any ideas?

Permissions shouldn't resolve into a 500 - so this sounds like we have a bug on the backend.

from the log @keifgwinn posted it looks like a corrupted federation.

@george-hadfield  can you produce steps to replicate? (i.e. which federation from which teamspace are you trying to remove?)

**Comment by george-hadfield** [comment]
I tried removing **Lego_House_Federation**

https://user-images.githubusercontent.com/78047794/150370672-f7249680-6402-47d1-a404-1f6f36e49db2.mov

**Comment by carmenfan** [comment]
> I tried removing **Lego_House_Federation**
> 
>  Screen.Recording.2022-01-20.at.15.35.22.mov

this should be fixed now @george-hadfield

**Review by george-hadfield — APPROVED** [review]

**Review by carmenfan — APPROVED** [review]

**Pull request merged**
