### PR TITLE
ISSUE #2558 weird colouring on double sided geometry 

### LINKED ISSUE #2558: double sided geometry fix
this issue is to build a version of https://github.com/3drepo/3drepounity/issues/369 to see if the attempt fix works good enough

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #2558

#### Description
- updated unity with https://github.com/3drepo/3drepounity/pull/370

### CODE REVIEW

**Comment by BDavydov** [comment]
@carmenfan @mosment3DRepo 
Just had a look at the Issue Branch and can confirm that the FBX models are behaving as expected. Plus I am not able to apply colour overrides and in Navisworks and see them in 3D Repo.
**BEFORE**
image
**NOW**
image
image

**Review by mosment3DRepo — APPROVED** [review]
Bogdan's testing = successful

**Comment by carmenfan** [comment]
@3drepo/product-team re-requested review for more models needs to be tested

**Pull request merged**
