### PR TITLE
ISSUE 2691 - 4.17.0 bug fixes

### LINKED ISSUE #2691: 3drepo io v4.17.0 (Release Candidate) QA
### UI Oddities
- [x] ~~[Spacing on elements in Risk Card inconsistent](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-880521001)~~ (caused by https://github.com/3drepo/3drepo.io/pull/2646)
- [x] [Underline in Issues & Risk cards is inconsistent](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-880700259)
- [x] [Comment expand button missing from Issue & Risks](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-881405081)
- [x] [Smart Group filters can't be modified](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-885063132)
- [x] [White screen after revision link](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-883337026) (carmen)
- [x] [SPM import error](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-884873958) - devops issue. to be dealt with on https://github.com/3drepo/DevOps/issues/235
- [x] [Can't update SafetiBase Viewpoint without taking a new model screenshot](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-885047344) (Charence)
- [x] [Retain risk viewpoint on screenshot update](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-885060223) (Charence)
- [x] Retain risk screenshot on viewpoint update (Charence)
- [x] [BCF import/export fail](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-884957232)
- [x]  [Empty "Assign" field when creating a new issue](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-885535011)(Carmen)
- [x] API key auth session should not check referer (Charence)
- [x] [Investigate "Filter with this operation is already used" in groups](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-887460033) (Charence)

### PR DESCRIPTION
**Pull request by Charence**
This fixes #2691 

#### Description
Addresses identified bugs

### Issues
- [x] [Issue & Risk title moving further to the right](https://github.com/3drepo/3drepo.io/pull/2718#issuecomment-889264575)
- [x] [Group details collapse upon open](https://github.com/3drepo/3drepo.io/pull/2718#issuecomment-889289713)
#### Test cases
See issue

### CODE REVIEW

**Comment by mosment3DRepo** [comment]
### Initial Bug check

- [ ] [Underline in Issues & Risk cards is inconsistent](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-880700259)
- [ ] [Comment expand button missing from Issue & Risks](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-881405081)
- [ ] [Smart Group filters can't be modified](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-885063132)
- [ ] [White screen after revision link](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-883337026) (carmen)
- [ ] [SPM import error](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-884873958) - devops issue. to be dealt with on https://github.com/3drepo/DevOps/issues/235
- [ ] [Can't update SafetiBase Viewpoint without taking a new model screenshot](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-885047344) (Charence)
- [ ] [Retain risk viewpoint on screenshot update](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-885060223) (Charence)
- [ ] Retain risk screenshot on viewpoint update (Charence)
- [ ] [BCF import/export fail](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-884957232)
- [ ]  [Empty "Assign" field when creating a new issue](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-885535011)(Carmen)
- [ ] API key auth session should not check referer (Charence)
- [ ] [Investigate "Filter with this operation is already used" in groups](https://github.com/3drepo/3drepo.io/issues/2691#issuecomment-887460033) (Charence)

**Comment by mosment3DRepo** [comment]
### Issue & Risk title moving further to the right

The title of issues and risks seems to be creeping over, it was a little further over in 4.17.0 but we must've missed it. It is even more pronounced now:

image

**Comment by mosment3DRepo** [comment]
### Group details collapse upon open

When you open a group the top frame seems to collapse, on a smart group you have the option to expand it again but for regular groups there is no way to get it back. Which means there is no way to edit the groups.

### Steps

1. Create a normal group
2. Create a smart group
3. Go back into both groups, notice the detail disappears

### GIF
Group hide

**Comment by carmenfan** [comment]
@mosment3DRepo  fixed the 2 bugs you raised so far, just triggered another deployment. Should work as intended once it's deployed.

**Comment by carmenfan** [comment]
pointed this PR to master as we have merged the RC to master so we can make way for revamp development.

we **SHOULD NOT** merge any further changes on staging into this branch.

**Comment by mosment3DRepo** [comment]
@carmenfan  I was a bit confused by your last comment so not sure if the changes you made are now on this branch, but it looks like the Groups collapsing issue has been fixed, but the Issues & Risks titles still have the spacing problem.

It also seems as though we've lost the creator name in the groups list:

image

**Comment by carmenfan** [comment]
> @carmenfan I was a bit confused by your last comment so not sure if the changes you made are now on this branch, but it looks like the Groups collapsing issue has been fixed, but the Issues & Risks titles still have the spacing problem.

@mosment3DRepo the prev comment has nothing to do with this. We just moved staging along as we really needed to merge the branches for revamp. It's just a logistic thing.

The bug you identified was fixed, which was raised about the new issues having the gap (as it has no number). We had to separate the issue number and title as separate components to be able to reuse the editable field component for editing titles, this is why you're seeing that padding, as it's reserving 3 digit worth of spaces for issues. @sanmont3drepo  is taking a look now to see if we can make it flexible.

> 
> It also seems as though we've lost the creator name in the groups list:
> 

I think these are issue/risks/sequence/views groups and are somehow bleeding through when it's not suppose to, i'll take a look.

**Comment by carmenfan** [comment]
@mosment3DRepo 

It should be resolved. obviously we can't wipe out what's been done so if those were there before the last deployment then it'll still be there.

But you shouldn't see new ones created when you import BCF. So going forwards you shouldn't see new ones, unless there's another function that's creating groups without tagging them....

**Comment by mosment3DRepo** [comment]
OK great, just tested with views, BCF and 4D and seems to be keeping all new ones hidden. @miadibe is going to test the Navisworks issue and then we should be good to go

**Comment by carmenfan** [comment]
@miadibe @mosment3DRepo ready for testing. you will need to use this installer for navis plugin to connect to this branch: https://www.dropbox.com/s/okl2q2sarxo0xfz/%5Bv4.17.3%20%28with%20ISSUE_2691%29%20-%20DO%20NOT%20DISTRIBUTE%5D%203D%20Repo%20Navisworks%20Plugins.msi?dl=0

image

**Comment by mosment3DRepo** [comment]
@m1chalkubiak I have added you as an admin to a project (mosment3ddev/IFC Parameter Testing) there are models in there with additional parameters.

I have a few comments:

**Comment by mosment3DRepo** [comment]
### Colouring in sub items

As you mentioned the alternating row colouring doesn't work in this situation but I think it would be good to show which values exist on the child level by colouring them as per the below mock up

image

**Comment by mosment3DRepo** [comment]
### Incorrect Parameter name

The child parameter name is currently just repeating the parent, where it should be the second part of the original string (after the :: delimeter):

image

**Comment by mosment3DRepo** [comment]
### Text overflow not working on Parameter name

On long parameter names the text is no longer overflowing onto the next line, instead it is cropped. This causes an issue if 2 parameters start with the same text but are cut off at the end

image

**Comment by mosment3DRepo** [comment]
### Copy Group & Select Elements not working

The 2 hover over buttons only appear to take one half of the parameter string on the child level, so they do not select anything, and the group logic is incorrect

image

**Comment by mosment3DRepo** [comment]
### Reorder List

In order to make it more user friendly can we reorder the list of metadata so that it puts all the parent items at the bottom of the list and sorts all the orphans alphabetically.

At the moment the parents showing up alongside the other values is a bit jarring

image

**Review by mosment3DRepo — APPROVED** [review]
QA test complete

**Pull request merged**
