### PR TITLE
ISSUE #4015 5.0.6 release candidate

### LINKED ISSUE #4015: Wrong position of object in 3D Repo when assigning multiple objects to a resource with a transformation in Synchro
### Description
This bug is seen when assigning multiple objects to a resource that has two tasks created with at least one transformation in Synchro. The relative position of one of the objects are out of place in 3D Repo. Enabling or disabling the transformation in 3D Repo has no effect with the position of the objects. 

- This bug is occurring in: Production
- This requires a hotfix to production: TBD

### Steps to replicate
- Created 3 objects in synchro 
- Assigned all 3 objects to a resource (called Cylinder & Box) 
- Create 2 different tasks from the resource (Task 1 : "Cylinder & Box" (this task has no transformation) and Task 2 : "Cylinder & Box 
Transformation" (this task has a transformation))
- .sp file can be downloaded [here ](https://www.dropbox.com/s/svzu74ylrzswbla/Box%20and%20cylinders%20Transformation.sp?dl=0) and exported to 3D Repo.
- .spm file can be downloaded [here ](https://www.dropbox.com/s/nyhigtxxszwzgr4/Box%20and%20cylinders%20Transformation3.spm?dl=0) and uploaded directly to 3D Repo 

Specific focus times:
-  .spm file before task 1 can be found [here](https://www.dropbox.com/s/5m8l2rrjfz1zpqj/Box%20and%20cylinders%20Transformation%205th%20January%202020.spm?dl=0)
- .spm file during task 1 can be found [here ](https://www.dropbox.com/s/sc7rukhjpqpjtj1/Box%20and%20cylinders%20Transformation%208th%20January%202020.spm?dl=0)
- .spm file in between task 1 and 2 can be found [here ](https://www.dropbox.com/s/yc4cronvdwbr51n/Box%20and%20cylinders%20Transformation%2010th%20January%202020.spm?dl=0)
- .spm file during task 2 can be found [here](https://www.dropbox.com/s/nhhk955uaiy8gqo/Box%20and%20cylinders%20Transformation%2012th%20Jan%202020.spm?dl=0) 
- .spm file after task 2 can be found [here ](https://www.dropbox.com/s/8hyab429ldr8fs2/Box%20and%20cylinders%20Transformation%2016%20th%20January%202020.spm?dl=0)
-  First try uploading with transformations tick box checked and then without it checked in 3D Repo

### Current Behaviour
- One of the cylinders is out of position

### Expected Behaviour
- The cylinder should be shown as the same position as in Synchro 

### Pictures/ Gifs of the error
In Synchro:
image

In 3D Repo:

image

Video recording of sequence in Synchro:

https://user-images.githubusercontent.com/100203626/221622517-2173ae73-cad3-4b2f-a6d6-300a7b759503.mp4

Video recording of sequence in 3D Repo:

https://user-images.githubusercontent.com/100203626/221623205-70a13c41-665a-4115-9dd6-a65841936aae.mp4

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #4015
#### Description
addresses https://github.com/3drepo/3drepo.io/issues/4015
which requires:
  - https://github.com/3drepo/3drepobouncer/issues/603
  - https://github.com/3drepo/3drepounity/issues/457

#### Test cases
#4015 should be resolved

### CODE REVIEW

**Comment by carmenfan** [comment]
converting this to draft as the import isn't correct... Left is processed locally on my laptop (windows), right is azp 😢. 
image

**Comment by carmenfan** [comment]
@Ramadyfm this is ready to test

note: `extent` button and zoom to object doesn't work as intended when the object is transformed (waiting on @sebjf  to have a look) so you may have to navigate around manually to view the sequence

**Review by anorrie — APPROVED** [review]

**Comment by carmenfan** [comment]
@keifgwinn  we can dismantle this custom bouncer now

**Pull request merged**
