### PR TITLE
ISSUE #3871 - restyle system log messages

### LINKED ISSUE #3871: Style system logs for V5 Issues and Risks
### Description

This seems to have been missed during the V5 styling issues. Setting the dropdown in the comment section to either "System logs" or "All" will show changes that have been made to the issue/risk
image
The spec shows the design for comments/system logs in the upcoming custom tickets comment section. This will likely use new components/styles, so we want to make sure the V4 comment sections used in Issues and Risks have appropriate styling. We can use the Custom Tickets spec as inspiration

### Goals

Have a clean looking and understandable display for the system logs

### Tasks
- [ ] Add V5 style overrides for issues/risks system logs

### Related Resources

MockUp : [here](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1591%3A14816&t=gC3lbvj2MsmIIgip-0)

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #3871 

#### Description
System logs have been restyles.

#### Test cases
Take a look at the system logs on their own (`System logs` on the dropdown menu), and then select `All` to see how they behave when rendered together with normal messages 

P.S. to create a new system log message, create/delete a shape

### CODE REVIEW

**Review by The-Daniel — APPROVED** [review]

**Comment by george-hadfield** [comment]
### Add <hr> above first item and below last item for system logs
The message looks part of the system log entry at the moment

image

**Review by george-hadfield — CHANGES_REQUESTED** [review]
One change

**Comment by george-hadfield** [comment]
@Amantini1997 

https://www.loom.com/share/ff7a4b9df5f74e6c9c05a2d6285e8a6d

**Review by george-hadfield — APPROVED** [review]

**Review by The-Daniel — APPROVED** [review]

**Pull request merged**
