### PR TITLE
Issue 3161 - Viewer Facelift - Layout

### LINKED ISSUE #3161: Viewer facelift - Layout
### Description
The layout looks bad. We need to fix the colours and the button to match.

### Goals
- [ ] As a user I want to see the viewer consistent with the rest of v5

### Tasks

image

**Circles**

Changes
image

- [x] Make default background of circles white
- [x] Change the icon colour to primary.main on hover (background stays white)
- [x] Change the active state to secondary.main and the icon colour to primary.main
- [x] Align the circles vertically underneath the '3D' logo
- [x] Reduce to padding/margin between the circles to match the design
- [x] Move the cards a touch closer to the circles (I can't do this in css)

**Toolbar**

Changes
image

- [x] Change background colour to secondary.main
- [x] Icons should be positioned horizontally centre inside the toolbar
- [x] Change the border-radius of the toolbar from 30px to 5px
- [x] Reduce spacing between icons slightly (I couldn't do this in css)
- [x] Add a 90% transparency to the background of the toolbar so that model is very slightly visible underneath
- [ ] Ensure the spacing between the bottom of the browser and the bottom of the toolbar is similar to my screenshot at the top of these comments (around 20px)

**Bugs in toolbar**
- [x]  Fix touch-area of a few buttons (in the horizontal bar) is reduced at the bottom. 
image
In other words, all the buttons with the small dash underneath cannot be clicked at the bottom like the other buttons (nor the mouse turns into a cursor). 

To give an idea, the red perimeter delimits the touchable area of the first two buttons
image

This problem, however, exists in staging too for the same buttons
image

### Related Resources
MockUp : `link to mockup`

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #3161 

#### Description
Fixed styling

### CODE REVIEW

**Comment by george-hadfield** [comment]
### Halve the space between the circle and the tooltip

image

**Comment by Amantini1997** [comment]
> ### Halve the space between the circle and the tooltip
> image

@george-hadfield fixed

**Review by sanmont3drepo — APPROVED** [review]
Is ok by me if its ok with you @george-hadfield  we can merge it in

**Review by george-hadfield — APPROVED** [review]

**Pull request merged**
