### PR TITLE
Issue 3841 - Suggested treatment dialog facelift

### LINKED ISSUE #3841: Fix the styling of the Suggested Treatments modal in V5 SafetiBase
### Description

This modal was left out of the SafetiBase facelift as the button only appears if the user uploads a Treatment Suggests CSV in the teamspace settings.

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Go to Teamspace Settings (this might have to be in V4. Go to `/dashboard/teamspaces` and click the cog next to your teamspace name)
- In the treatment suggestions upload a valid template file (e.g. [this one](https://github.com/3drepo/3drepo.io/files/10337411/My.Treatments.csv))
- Now navigate to a Container/Federation in this teamspace
- Open/Create a Safetibase issue.
- In the Risk tab set the category to one of the categories listed in your treatment suggestions CSV. (If using the example file use 'Environmental Issue')
- Now switch to the Treatment tab. There will now be a 'Suggest' button.
- Clicking this opens an unstyled modal

### Current Behaviour
- The modal has some V5 style, but it hasn't been fine-tuned for its specific use. The styling is a bit "all over the place"

### Expected Behaviour
- The modal has a clean V5 style

### Pictures/ Gifs of the error
image
image

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #3841

#### Description
The suggested treatments dialog has been re-styled to look better

### CODE REVIEW

**Comment by george-hadfield** [comment]
Can you re-run this please @Amantini1997

**Comment by george-hadfield** [comment]
Redirecting to status screen

image

**Comment by george-hadfield** [comment]
### Left align stage and type single selects
Also add another 10px spacing between stage select and type label

image

**Comment by george-hadfield** [comment]
### Empty suggestion box is too narrow

It should span the width of the content area. The content area is the left side of the text to the right side of the select button.

image

**Comment by george-hadfield** [comment]
### Change select button to primary button (teal)

**Comment by george-hadfield** [comment]
### Put stage and type on separate lines

image

**Review by george-hadfield — CHANGES_REQUESTED** [review]
Few comments left

**Review by The-Daniel — DISMISSED** [review]

**Review by george-hadfield — APPROVED** [review]

**Comment by The-Daniel** [comment]
image
I don't know if we want the custom scrollbar here?

**Comment by sanmont3drepo** [comment]
> image I don't know if we want the custom scrollbar here?

We probably will get rid of custom scrollbars . Just need to settle for a style for native scrollbars

**Review by sanmont3drepo — APPROVED** [review]

**Pull request merged**
