### PR TITLE
ISSUE 1121 - Changed home page logo

### LINKED ISSUE #1121: Logo change
### Description

The 3D Repo site logo requires changing. 

### Goals

- [x] Change Logo
- [x] Test for responsive sizing on all breakpoints.

### Tasks

- [x] Find where current logo is stored.
- [x] Change logo
- [x] Test on mobile and browser to ensure logo sizes correctly.
Changes from pull request
- [x] Remove black logo
- [x] Upload White logo

### PR DESCRIPTION
**Pull request by niblux**
This fixes #1121 

#### Description
- Changed home page logo.
- Both blue and black versions of logo have been uploaded to make it easier to swap if necessary.

### CODE REVIEW

**Comment by carmenfan** [comment]
Also make sure you tag your commits with ISSUE #<issue number> and pull requests should also references it on the title

**Comment by niblux** [comment]
I have removed the black logo and added the new white logo.

**Comment by carmenfan** [comment]
Remove the blue logo then we're good to go!

**Comment by niblux** [comment]
The blue logo has been removed and changes committed 👍

**Pull request merged**
