### PR TITLE
ISSUE 2107 - Comments Issue

### LINKED ISSUE #2107: Issue Comments Feedback
- [ ] Issue 1

### PR DESCRIPTION
**Pull request by m1chalkubiak**
This fixes #2107

#### Description
- [x] [Issue comments background inconsistency](https://github.com/3drepo/3drepo.io/issues/2107#issuecomment-657650277)
- [x] [Quote reply is prone to create errors for new users](https://github.com/3drepo/3drepo.io/issues/2107#issuecomment-657659440)

### CODE REVIEW

**Comment by carmenfan** [comment]
@m1chalkubiak  is this ready for another look?

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak is this ready for another look?

@carmenfan Yes, I think that all the mentioned issues have been fixed.

**Comment by m1chalkubiak** [comment]
@carmenfan 
I found the reason for this strange behavior and fix it.

**Comment by carmenfan** [comment]
@m1chalkubiak getting white-screened when I click on new risk in the viewer:
image

**Comment by m1chalkubiak** [comment]
@carmenfan 
Now I've tested editing and creating a new ones for both issues and risk on viewer and board page, as well as group panel. Hope everything will be working now correctly.

**Pull request merged**
