### PR TITLE
ISSUE #3887 - Release candidate for 5.0.5

### LINKED ISSUE #3887: Release Candidate 5.0.5
Previously this was an issue for V5: Remove menus/buttons for non-admin users, but now it will contain all hotfixes needed for 5.0.5

### Description

Currently the APIs block users without the relative permissions from performing certain actions, but the UI should reflect this too

### Goals

- [ ] Remove options for non-admins to access areas of the app/commands they are blocked from performing
- [ ] Teamspace & Project Admins should have access, anyone with Viewer, Commenter, Collaborator access to a container/fed within the teamspace should have the options removed

### Tasks
See https://docs.google.com/spreadsheets/d/1DJWz09Nwi59TtbwRE5r4FPMHWcDsNBTaZWNnx7Ax7_U/edit#gid=289465492 for live version
image

### PR DESCRIPTION
**Pull request by The-Daniel**
This fixes #3887 

Contains:
- V5: Remove menus/buttons for non-admin users
- https://github.com/3drepo/3drepo.io/issues/3950
- https://github.com/3drepo/3drepo.io/issues/3975
- https://github.com/3drepo/3drepo.io/issues/3982
- https://github.com/3drepo/3drepo.io/issues/3981
- https://github.com/3drepo/3drepo.io/issues/3991
- <del>https://github.com/3drepo/3drepobouncer/issues/600</del> (no longer part of the RC)
- [Import transformation should be checked by default if the file is .spm](https://github.com/3drepo/3drepo.io/pull/3943#issuecomment-1440263186)
- https://github.com/3drepo/3drepo.io/pull/3998
- https://github.com/3drepo/3drepo.io/issues/3992
- https://github.com/3drepo/3drepo.io/issues/4005
- https://github.com/3drepo/3drepo.io/pull/3997#pullrequestreview-1311116541
- https://github.com/3drepo/3drepo.io/issues/4003

<details><summary>Non admin support details</summary>

#### Description
- Adds permissions to V5
- Trying to access a page when you don't have sufficient rights redirects you to the closest safe route
- A user should not be able to submit a form that they don't have permission to do so. Buttons and inputs should be disabled or hidden
- Adds selectors for getting teamspace, project, container, and federation permissions

#### Test cases

- Go through V5 as different permissions and try to access things that should be inaccessible
- Teamspace admins should be able to access everything

## Note

I have invited you to my teamspace so you can easily test this. There are two projects. One where you are project admin, and another where you are not. In the latter project the containers and federations each have names which describe which permissions you have on them.

If there's anything you need me to add to these teamspaces so you can test please let me know

https://issue-3887.dev.3drepo.io/v5/dashboard/Daniel/84ce7e80-a3ca-11ed-bcea-83150479d65c/t/federations

Also there's a project with only viewer access containers, so you can see that the "Upload Files" button disappears
</details>

### CODE REVIEW

**Review by Amantini1997 — CHANGES_REQUESTED** [review]

**Comment by carmenfan** [comment]
@The-Daniel reminder to rebase this to #3910 

Good to do it before a code review so if you added anything from staging by mistake the reviewers can spot them

**Comment by carmenfan** [comment]
this branch will merge to master as part of a hotfix

Please avoid merging staging in!

**Review by Amantini1997 — APPROVED** [review]

**Comment by sanmont3drepo** [comment]
The disabled button in the revision list looks kind of weird in that context
image

**Comment by sanmont3drepo** [comment]
Maybe we should get rid of the 'tasks' tab (originally it was going to be the replacement for the kanban board if Im not mistaken)

image

**Comment by sanmont3drepo** [comment]
In  federations and containers settings  would get rid of the "save changes" button and change "cancel" button to "close". I dont know what you think @mosment3DRepo 

image

**Comment by sanmont3drepo** [comment]
Would get rid directly of this tab if I dont have permissions. I cant see anything but just the name of the project. It would confuse me if I were a user.

image

**Comment by sanmont3drepo** [comment]
When you are in issues and risk (v4 revamp) the redirect if you have your session expired doesnt work correctly.
logout

**Review by sanmont3drepo — CHANGES_REQUESTED** [review]
When you are in issues and risk (v4 revamp) the redirect if you have your session expired doesnt work correctly.
logout

**Comment by carmenfan** [comment]
Import transformation should be checked by default if the file is `.spm`

image

**Comment by mosment3DRepo** [comment]
> * V5: Remove menus/buttons for non-admin users
> * [Session expiry doesn't redirect to login any more #3950](https://github.com/3drepo/3drepo.io/issues/3950)
> * [Custom tickets button not showing  #3975](https://github.com/3drepo/3drepo.io/issues/3975)
> * [Can't drag select on certain models #3982](https://github.com/3drepo/3drepo.io/issues/3982)
> * [Can't create view on certain models #3981](https://github.com/3drepo/3drepo.io/issues/3981)
> * [404 error when loading federations/containers #3991](https://github.com/3drepo/3drepo.io/issues/3991)
> * [export IFC models in m 3drepobouncer#600](https://github.com/3drepo/3drepobouncer/issues/600)
> * [Import transformation should be checked by default if the file is .spm](https://github.com/3drepo/3drepo.io/pull/3943#issuecomment-1440263186)
> * [ISSUE #3983 - Invitations V5 Fix #3998](https://github.com/3drepo/3drepo.io/pull/3998)
> * [Viewer seems to only support 1 browser tab #3992](https://github.com/3drepo/3drepo.io/issues/3992)
> * [IndexedDbCache cannot be created by an embedded viewer #4005](https://github.com/3drepo/3drepo.io/issues/4005)
> * [ISSUE 3990 - allow unity-util to work without index db #3997 (review)](https://github.com/3drepo/3drepo.io/pull/3997#pullrequestreview-1311116541)
> * [Transformation instructions are not honoured if it's instructed whilst the mesh is hidden #4003](https://github.com/3drepo/3drepo.io/issues/4003)

I agree with a lot of your points, but since Dan is away and we need to get the fix out, I will raise a separate Issue

**Comment by mosment3DRepo** [comment]
@carmenfan can we pull the IFC unit change out, we've realised it will cause other problems that we can't test for right now

**Comment by mosment3DRepo** [comment]
**Matt's testing checklist 23/02/2023**

- [ ] V5: Remove menus/buttons for non-admin users
- [ ] https://github.com/3drepo/3drepo.io/issues/3950
- [ ] Custom tickets button not showing  #3975
- [ ] https://github.com/3drepo/3drepo.io/issues/3982
- [ ] https://github.com/3drepo/3drepo.io/issues/3981
- [ ] https://github.com/3drepo/3drepo.io/issues/3991
- [ ] https://github.com/3drepo/3drepobouncer/issues/600
- [ ] https://github.com/3drepo/3drepo.io/pull/3943#issuecomment-1440263186
- [ ] https://github.com/3drepo/3drepo.io/pull/3998
- [ ] https://github.com/3drepo/3drepo.io/issues/3992
- [ ] https://github.com/3drepo/3drepo.io/issues/4005
- [ ] https://github.com/3drepo/3drepo.io/pull/3997#pullrequestreview-1311116541
- [ ] https://github.com/3drepo/3drepo.io/issues/4003

**Comment by carmenfan** [comment]
> @carmenfan can we pull the IFC unit change out, we've realised it will cause other problems that we can't test for right now

Yes we can remove it

**Comment by mosment3DRepo** [comment]
**Power BI working**:

image

**Pull request merged**
