### PR TITLE
Issue 3182 - Due Date field added on risks

### LINKED ISSUE #3182: Add Date to risks
### Description
Many customers from different companies are requesting the addition of a due date field in SafetiBase.

Requires triage @mosment3DRepo 

### Goals
- [ ]  Similarly to Issues user should be able to set a due date for a risk with the calendar window that appears

### Tasks
- [ ] new API end point to add dates for risks
- [ ] update UI with new field

### PR DESCRIPTION
**Pull request by ChristosTsiotsias**
This fixes #3182

#### Description
Risks now have a due date field similarly to the issues.

#### Test cases
The user should be able to set the due date upon risk creation and update it both on ticket board and in model.

### CODE REVIEW

**Review by carmenfan — CHANGES_REQUESTED** [review]
due date missing in the risk report

image

**Comment by carmenfan** [comment]
@ChristosTsiotsias  it's failing linter check 
image

**Comment by keifgwinn** [comment]
/azp run

updating mongo hostnames

**Comment by miadibe** [comment]
I reviewed this and found some inconsistencies: 

**1. You cannot filter risks by Due Date in SafetiBase (but you can with Issues)**
due date2

**2. When you create a PDF report, the Due Date is today's date and not the chosen Due date - This happens in both reports issued from Kanban board or issue card**
due date3
due date4

**3. When you modify a risk's due date, same issue as Point 2.** 
due date5

Ran by @mosment3DRepo, the above wasn't included in user stories. Other than that feature works well.

**Comment by carmenfan** [comment]
@miadibe  @ChristosTsiotsias has addressed the changes, ready for another look when the deployment is up

**Comment by miadibe** [comment]
I've tested this again now, I don't see the changes

**Comment by carmenfan** [comment]
@miadibe  the deployment failed. let's try again...

**Comment by carmenfan** [comment]
@miadibe  it deployed successfully this time so it should work now

**Comment by miadibe** [comment]
@carmenfan @mosment3DRepo this has now been tested and can confirm is working successfully, great job

**Comment by carmenfan** [comment]
> @carmenfan @mosment3DRepo this has now been tested and can confirm is working successfully, great job

@miadibe @mosment3DRepo great. In that case can one of you hit approve so we can merge this? 😆

**Review by carmenfan — APPROVED** [review]

**Pull request merged**
