### PR TITLE
Issue 3151 - Elastic modules upgrade

### LINKED ISSUE #3151: Upgrade Elastic packages
### Description

We're currently using 7.12 modules but we're up to 7.17 in production elastic. We've also encountered a dependency issue on the current branch of staging.

### Goals

- [x] Upgrade elastic modules to latest
- [x] Ensure operational

### Tasks

- [x] Upgrade package

### PR DESCRIPTION
**Pull request by keifgwinn**
This fixes #3151

#### Description
Upgraded the elastic modules

#### Test cases
Service boots and reports to elastic properly

### CODE REVIEW

**Review by carmenfan — APPROVED** [review]
Feel free to merge after you've verified it works

**Comment by keifgwinn** [comment]
APM/Custom Logins working in this branch, good to go.

**Review by carmenfan — APPROVED** [review]

**Pull request merged**
