### PR TITLE
ISSUE #3364 - exit shapes mode on tab change

### LINKED ISSUE #3364: Exiting the "Shapes" tab in issues and risks should exit shape the tool
### Description

Currently once you have completed drawing a shape in the issues/risks card you must remember to click the shape button again before you switch tabs, otherwise 3D Repo will continue to show the shape tool under the mouse pointer.

Switching tabs should adopt the same behaviour as closing the card, the tool is abandoned and any half drawn shapes are removed/

### Goals

- [ ] As a user and I want to draw a single shape in an issue and then navigate back to the Properties tab
- [ ] As a user I only want the shape tool to be enabled when I can see the shape interface in a card so that I don't get confused
- [ ] As a user if I have not completed drawing a shape and I navigate to a different tab I expect the shape to be abandoned and the shape tool turned off

### Related Resources

Current Behaviour:

https://user-images.githubusercontent.com/62879582/174758911-6f4b57eb-6916-458f-a33c-7e82a817dad8.mp4

Expected Behaviour:

https://user-images.githubusercontent.com/62879582/174758976-f21fe06b-47c4-40f0-ac1c-c748eb055f96.mp4

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #3364

#### Description
On tab change, the shapes container detects a change in the active state and sets the measureMode to empty

### CODE REVIEW

**Review by The-Daniel — DISMISSED** [review]
I've noticed that the measureMode remains active when closing the issues/risks card. I'm not sure if this is desired behaviour or not

**Comment by Amantini1997** [comment]
> I've noticed that the measureMode remains active when closing the issues/risks card. I'm not sure if this is desired behaviour or not

@mosment3DRepo when the user closes the card, should the measure mode stop?

**Comment by mosment3DRepo** [comment]
> > I've noticed that the measureMode remains active when closing the issues/risks card. I'm not sure if this is desired behaviour or not
> 
> @mosment3DRepo when the user closes the card, should the measure mode stop?

Yes, basically it should turn off whenever the measurement window is no longer on screen

**Comment by The-Daniel** [comment]
I'm not sure if this is a bug or a feature, because I think it's niche and could even be useful. But when you start making a measurement in an issue/risk and click the same measure tool in the other card then the initial measurement persists, and when you finish the measurement/shape it saves it to the second card. I personally think this is fine, but what do you think @mosment3DRepo 
https://user-images.githubusercontent.com/62481250/212963797-76b58754-a2c3-4a8e-8a8b-e87b2ad72bb4.mp4

**Review by sanmont3drepo — APPROVED** [review]

**Pull request merged**
