### PR TITLE
Issue 3262 - Update screenshot modal

### LINKED ISSUE #3262: New design needed for update screenshot modal
Design link https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136509%3A173535

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #3262 

#### Description
Screenshot bottom toolbar was refactored following the new design

#### Nice to know
The screenshot modal contains a few dropdown menus which are modals inside a major modal. However, they are all rendered as as siblings in the DOM, making them hard to style. To solve this issue, the MUI `content` property was used in the theme so that all these modals are rendered as descendant of the `#v4Overrides` container

### CODE REVIEW

**Comment by george-hadfield** [comment]
### Select fields needs fixing
image

**Comment by george-hadfield** [comment]
### Change colour picker component to use the same style as measurements

image

**Review by sanmont3drepo — APPROVED** [review]

**Pull request merged**
