### PR TITLE
Issue 4556 - v5.6 Release candidate 

### LINKED ISSUE #4556: Release Candidate v5.6
This is the QA branch for v5.6 release

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #4556

#### Description
Release candidate for 5.6.0

#### Test cases
Full QA test should pass:  https://asitesol.sharepoint.com/:x:/s/3DRepoTeamFolder/EUSWVxDmdSJNiDVarJi_cT4BXKwxCRjJDMR66kfaP_-nnQ?e=8wuXew

#### Bug template
````
### Description
<!-- Brief description of the bug -->

### Steps to replicate

### Current Behaviour

### Expected Behaviour

### Pictures/ Gifs of the error
````
#### Round 2

- [x] [New ticket button appears if I am a view and clicked on the body of the ticket card](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1789063351) (Alessandro)
- [x] [Changing a deleted group doesn't trigger an update request, but it is overwriting some other group in the list.](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1789134500) (Santiago)

<details><summary>Round 1</summary>
<p>

#### Release Critical
- [x] [App crashing when navigating from issues/risks card back to dashboard](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779367679) (Santiago)
- [x]  [Revision description and format are not showing up on socket.io updates](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779416419) (Carmen)
- [x] [App crashing when the user doesn't have permissions to all of the containers](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779461393) (Alessandro)
- [x] [App crashes if you try to click on the number of containers when you don't have permissions to any of the containers](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779519551) (Alessandro)
- [x] [Default value consistency within tabular view](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779515661) (Alessandro)
- [x] [Issue/Risk pin colliders are too small](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779566612)
- [x] [(backend) Session ID clashes are back](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779568413) (carmen)
- [x] [Sequence is not resetting view when exiting sequence card](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779760173)  (Santiago)
- [x] [colour overrides check box remains ticked after we've reset the overrides](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780661323) (Alessandro)
- [x] [Compare card is broken](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780792618) (Carmen)
- [x] [App crashes if you open the 'create group' form, delete and existing group, and then click save](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780834013)(Santiago)
- [x] [Ticket pins are not removing themselves when they are removed](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780949455) (Alessandro)
- [x] [Do not reset the clipping plane if we are selecting a ticket without a default view/ no camera in the default view](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1781004441) (Alessandro)
- [x] [App crashes on LoD drop down change](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1781019946) (Daniel)
- [x] [Viewers should not be able to add filters to a smart group](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1781155596) (Daniel)
- [x] [Colour overrides are not displayed when the page is refreshed on a ticket](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1781203211) (Alessandro)

#### Highly desired
- [x] [Search by issue/risks numbers should work](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1781262437) (Alessandro)
- [x] [Default pin should be focused after we've saved a new ticket.](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1781014596) (Alessandro)
- [x] [Loading state for when saving tickets](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780962500) (Alessandro)
- [x]  [Revision count not updating when revisions are being declared as void](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779292482) (Alessandro)
- [x] [visual settings UI bugs](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779467227) (Alessandro)
- [x] [Username field should get validated asap](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779523353) (Alessandro)
- [x] [Adding a risk comment is causing the app to create random history log for the risk](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779548883) (Alessandro)
- [x] [Tree search should match federation groups entries as well](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779661796) (Daniel)
- [x] [Group updates coming from socket.io should not disrupt the user's current work](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780787266) (fixed in the previous groups issue by Santiago)
- [x] [Login error message is obscured ](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1787515233) (Daniel)

#### Nice to have
- [x]  [Formatting on legal pages](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779260266) (Daniel)
- [x]  [Suggest password should not overwrite username on sign up form](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779407107) (Daniel)
- [x]  [Sorting containers doesn't work](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779445969) (Alessandro)
- [x] [Alphabetical sort is not case sensitive on views](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779570483)  (Alessandro)
- [x] [Last updated field in groups should have the same date format as everywhere else](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779621423) (Alessandro)
- [x] [User should not be able to compare the same revision](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780802634) (Santiago)
- [x] [weird scroll bar on groups search](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780860905) (Alessandro)
- [x] [Disable export groups and download json when there are no groups](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780932371) (Alessandro)
- [x] [Paste filter button are not aligned](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1781090577) (Alessandro)
- [x] [Pasting filters with prefined rules allows for multiple rules to be created under the same name](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1781093806) (Alessandro)
- [x] [Search bar high on ticket search](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1783162328) (Daniel)

#### Can live without (spin out separate issues)
- [x] [Resrouce deletion should trigger an update in issue/risk history](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779525077) (Alessandro)
- [New container created under the favourite section should be automatically favourited](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780970206)
- [Only filtered ticket pins should be visible](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1783156043) (Daniel - made a separate issue for it #4563)
- [UI is terrible when the image has weird aspect ratio](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780751030) (Santiago)

#### Won't fixed (expected behaviour)
- [Autosuggest password doesn't work on chrome](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779459468)
- [Opacity has no affect on highlights](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780695873)
- [Unity error modal looks off](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780863590)
- [Lag when scrolling on ticket comments](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780967532)
- [Remove new ticket button under the rows on tabular view if the issue doesn't have sufficient access](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779586286) (Alessandro)
- [Smart group count is zero until a group is deleted/updated](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1781227679) (Seems to only happen when socket.io is not working)
- [notifications showing undefined if the container no longer eixsts](https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1779278234) (Alessandro)

</p>
</details>

### CODE REVIEW

**Comment by sebjf** [comment]
**Privacy Page**
1. Is support@3drepo.org still the correct address?
2. Cookies Policy URL 
image

**Terms Page**
1. Inconsistent use of whitespace
image

**Also, the footer on our production site,**

1. Still has a (dead) link to 3D Send 😢 
2. LinkedIn icon doesn't show
image

**Comment by sebjf** [comment]
**Notifications**

I am guessing this is because the container has since been deleted?

image

Is this the expected behaviour? (That it says undefined, as opposed to something else, or not showing up at all?)

**Comment by sebjf** [comment]
**File Upload Dialog**

If a file upload is Cancelled, after a moment the Container switches to the Processing state, preventing the user from doing anything but deleting it.


https://github.com/3drepo/3drepo.io/assets/5058369/2c9b7a68-2452-4c60-9798-d92605f4d3ba

**Comment by Amantini1997** [comment]
**Cannot navigate from the viewer to the dashboard when issue/risk card is open**
- go to the viewer;
- click on the issue/risk card to open it;
- from here, reach the dashboard (navigate back in history or use the breadcrumbs).

The app crashes complaining about _Cannot read properties of undefined (reading 'v5')_

**Comment by sebjf** [comment]
**New Revision**

When uploading a revision, the Revision Description does not update once processing is complete, until after the page has refreshed.

image

**Comment by sanmont3drepo** [comment]
- [ ] Sorting federations by container doesnt work

image

**Comment by The-Daniel** [comment]
### Description
Autosuggest strong password does not seem to work in Chrome, although this appears to be a problem with Chrome as it doesn't work on other [websites](https://www.amazon.co.uk/ap/register?openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.return_to=https%3A%2F%2Fwww.amazon.co.uk%2Fref%3Drhf_sign_in&openid.assoc_handle=gbflex). (Firefox works)

### Pictures/ Gifs of the error
https://issue-4556.dev.3drepo.io/v5/signup

**Comment by sebjf** [comment]
Clicking Containers on a Federation for which permissions are granted for only some Containers, results in a blank screen

image
image

@carmenfan, not sure where to link this because it wasn't part of the actual viewer test - I just did it because I was testing different permissions permutations for the viewer!

**Comment by sebjf** [comment]
**Visual Settings**

Box outline for shadows is off.

image

**Comment by The-Daniel** [comment]
Not necessarily a bug, but wouldn't it make sense if we disable the login button when the user is locked out?
image

**Comment by sanmont3drepo** [comment]
- [ ] Listing all federations which a user has permissions to doesn't work.
image

image

**Comment by Amantini1997** [comment]
**Tabular view: default value**
- Group by priority and try to create a new ticket for container A from a group batch (e.g. "High")
- from another group batch (e.g. "Medium") if you click on new ticket for container A, the priority value is not changed. If you do the same for another container (e.g. container B) then it works

**Comment by sanmont3drepo** [comment]
- [ ] clicking on number of containers as a viewer or commenter causes a blank page

**Comment by The-Daniel** [comment]
### Description
On sign up the username field does not get validated until another field errors and the username field is clicked again

### Steps to replicate
- open user sign up
- enter an invalid username (e.g. use spaces)
- It will not error
- create an error in either the email or password field
- click the username field again
- click outside the username field to blur it
- it will now error

### Current Behaviour
- A user can proceed to the next stage of account creation with an invalid username

### Expected Behaviour
- An invalid username will show an error on blur

### Pictures/ Gifs of the error
image
image

**Comment by sebjf** [comment]
**Risks**

Should removal of resources in Risks show up in the system log?

image

**Comment by sebjf** [comment]
**Risk Comments**

Adding a comment under Risks causes the labels for the Consequence and Likelihood System Log Entries to show (invalid) until they are changed or the page is refreshed.

https://github.com/3drepo/3drepo.io/assets/5058369/a9aae4eb-531c-4a86-8f63-a84186756eb6

**Comment by sebjf** [comment]
**Risk Pins**

Pin Colliders are too small

https://github.com/3drepo/3drepo.io/assets/5058369/3346f551-dee3-4e2d-8548-b58e76b78a39

**Comment by carmenfan** [comment]
Getting a lot of session Id clashes (or we're trying to store the login records more than once?

image

**Comment by The-Daniel** [comment]
### Description

Views card alphabetical sort is not case sensitive

### Pictures/ Gifs of the error
image

**Comment by The-Daniel** [comment]
The last updated field in a group does not show the year. Everywhere else in the app we seem to use dd/mm/yyyy for last updated date. Seems a bit odd to me
image

**Comment by Amantini1997** [comment]
**Custom ticket: template default image**
Create a template with `{ defaultImage: true }`, the received template in the frontend is actually missing that property
image

<details>
<summary>template code</summary>
<code>{
  "name": "Only default properties",
  "code": "ODP",
  "config": {
    "comments": true,
    "issueProperties": true,
    "defaultView": true,
    "defaultImage": true,
    "pin": true
  }
}
</code>
</details>

**Comment by sanmont3drepo** [comment]
- [ ] When searching in a tree of a federation that has groups, the search doesnt match the group


_This is a federation with "monkeys" as a group of containers_
a federation with groups
searching

**Comment by carmenfan** [comment]
### Description
View not resetting properly after a sequence if I've viewed an issue.

### Steps to replicate
- go to this model: https://issue-4556.dev.3drepo.io/v5/viewer/QA5_6/3a0d0ea0-7356-11ee-8a44-d122d1a78af0/58978210-7356-11ee-8a44-d122d1a78af0
- inspect the sequence in steps of frame to get familiar with the sequence
- In the middle of the sequence, create an issue
- exit the issue
- exit the sequence card

### Current Behaviour
Colour overrides, transformations are not being reset. Hitting reset colour override after is resetting the colour and also the transformation.

### Expected Behaviour
status of the model should reset to its original state

### Pictures/ Gifs of the error
img-25-42-23-06-42

**Comment by carmenfan** [comment]
I'm a divider line, all bugs reported above this post has been prioritised

**Comment by Amantini1997** [comment]
**Ticket:Groups on clear overrides checkboxes stay ticked**
- Open a ticket with some colour overrides checked (see them reflected in the viewer)
- Click on "clear overrides" in the bottom bar

### Expected Behvaiour
The colour overrides should lose the tick

### Actual Behaviour
The colour overrides keep the tick

**Comment by The-Daniel** [comment]
Group override opacity has no effect on the group highlights
image

**Comment by The-Daniel** [comment]
### Description
Groups card "Delete all groups" modal is squished and you can't read all of modal title

### Steps to replicate
In groups card use the ellipses menu and select delete all

### Pictures/ Gifs of the error
image

**Comment by sanmont3drepo** [comment]
- [ ] Uploading an image with a different aspect ratio/size looks bad:

image

**Comment by The-Daniel** [comment]
### Description
Possibly a rare occurrence, but very annoying. It happened to me as I was QAing on the same model Alessandro was on.

If you are creating a ticket group and another user creates a ticket group before you click save then the realtime event ads their group but also causes the form to change to editing the new group. The data from the group you were creating is lost.

### Steps to replicate
- Open the same model in two accounts (using two browsers or incognito mode).
- Open the same ticket in both accounts 
- Open the same viewpoint groups
- In both browsers click create new group and fill in some details
- In one browser click save

### Current Behaviour
- The new group is added to the groups list in both browsers
- The other user will have their 'new group' form change to an 'edit group' form of the newly made group
- This user will have all the data from their new group form lost

### Expected Behaviour
- The new group is added to the list for the other user
- Their form remains in the 'create group' mode and all the details are still there

### Pictures/ Gifs of the error
image
image

**Comment by sebjf** [comment]
**Compare**

On this model 

https://issue-4556.dev.3drepo.io/v5/viewer/QA5_6/aa5831d0-733d-11ee-bf26-6fe220add3a3/ee340120-7344-11ee-bb68-a9db1c86335d

Starting a Comparison shows the error

image

The comparison appears to work when the error is dismissed however.

**Comment by carmenfan** [comment]
I'm a divider line, all bugs reported above this post has been prioritised

**Comment by sebjf** [comment]
**Compare**

**Compare**

On this model 

https://issue-4556.dev.3drepo.io/v5/viewer/QA5_6/aa5831d0-733d-11ee-bf26-6fe220add3a3/ee340120-7344-11ee-bb68-a9db1c86335d

- [ ] The Compare tool allows selecting the same revision as the base to compare to. This results in the viewer trying to load it twice which (causing errors, as it is not possible to load the same assets twice in Unity).

image

**Comment by The-Daniel** [comment]
### Description
TICKET GROUPS: App crashes if you open the 'create group' form, delete and existing group, and then click save

### Steps to replicate
- Open a populated custom tickets groups list
- Click the create group button to open the form
- With the form open delete a group
- Save the new group

### Current Behaviour
- The app crashes
- The group is not created

### Expected Behaviour
- The user can create a new group with no problems

### Pictures/ Gifs of the error
image
image

**Comment by The-Daniel** [comment]
Weird scroll bar in groups card search
image
### Steps to replicate
- Open the groups card
- Add a search term
- Collapse the search bar

**Comment by The-Daniel** [comment]
Unity error modal looks off
image

**Comment by The-Daniel** [comment]
When the groups list is empty 'Download JSON' is as useful as 'Export groups' and should probably also be disabled
image

**Comment by ChristosTsiotsias** [comment]
### Description
Default pin of a ticket remains on model even after delete. Also does not seem  to be hidden even after clicking on a different ticket's pin

### Steps to replicate
- Create two tickets and set a default pin on each one
- Enter the first ticket and delete the pin (the pin does not dissapear)
- Exit ticket details and go back to ticket list (the pin still appears)
- Click on the second pin, that should display the second ticket (the deleted pin still appears)

### Current Behaviour
The deleted pin remains on model

### Expected Behaviour
The deleted pin should dissapear upon deletion

**Comment by ChristosTsiotsias** [comment]
### Description
Saving a ticket with a lot of data takes a long time and a user may be confused on wheather the save is fired and press the button again. Pressing Save ticket again sends the request for a second time and the user may end up with 2 identical tickets.

### Steps to replicate
- Create a new ticket based on a template that has a lot of properties and modules (eg 'All')
- Populate all properties and modules
- Click Save ticket

### Current Behaviour
Saving the ticket takes a few seconds and the Save ticket button is still clickable.
If the user clicks the button for a second or third time another save request is sent

### Expected Behaviour
Save button should be disabled while the request is processed

### Pictures/ Gifs of the error

https://github.com/3drepo/3drepo.io/assets/71635617/2e409706-f3b9-463e-9635-0827286e5404

**Comment by ChristosTsiotsias** [comment]
### Description
There seems to be a small lag when scrolling in the comments section

### Steps to replicate
- Add some comments in a ticket
- Scroll up and down

### Current Behaviour
The is s slight lag when scrolling

### Expected Behaviour
The scrolling should be smooth

### Pictures/ Gifs of the error

https://github.com/3drepo/3drepo.io/assets/71635617/54e8784c-e2e4-4986-b40b-5f111ebdcfe4

**Comment by ChristosTsiotsias** [comment]
### Description
Creating a new container using favourites section creates a new container but does not mark it as favourite

### Steps to replicate
- Create a new container using the New Container button at the Favourites section

### Current Behaviour
A new container is created but its not marked as favourite

### Expected Behaviour
A new container should be created but it should be marked as favourite

**Comment by carmenfan** [comment]
I'm a divider line, all bugs above this have been prioritised

**Comment by carmenfan** [comment]
### Description
Do not reset the clipping plane if we are selecting a ticket without a default view/ no camera in the default view


### Steps to replicate
- come here https://issue-4556.dev.3drepo.io/v5/viewer/QA5_6/4c482d00-733a-11ee-a81a-73bc060d12f2/76c86c30-7348-11ee-bb68-a9db1c86335d
- click on the one ODP:1 (has a view)
- then click on MNV:1 (no view)

### Current Behaviour
clipping planes are removed

### Expected Behaviour
clipping planes should stay unless we're replacing the view

### Pictures/ Gifs of the error
img-26-16-23-01-16

**Comment by carmenfan** [comment]
### Description
Default pin should be focused after we've saved a new ticket.

It's a weird situation where it stays unfocused until we exit the ticket, then it becomes focused

### Steps to replicate
- Create a ticket with a default pin
- Save ticket

### Current Behaviour
Ticket is teal in colour and stays teal in colour upon save, but as soon as you exit the ticket it becomes focused

### Expected Behaviour
it should just become focused upon save

### Pictures/ Gifs of the error
img-26-16-23-01-16

**Comment by ChristosTsiotsias** [comment]
### Description
App crashes when LOD dropdown selection changes

### Steps to replicate
- Follow the process to upload a new revision to a container
- Select an rvt file
- Before uploading try to set the LOD

### Current Behaviour
The app seems to freeze and the user cannot click anywhere

### Expected Behaviour
The app should not freeze and the dropdown should change

###Pictures/ Gifs of the error

https://github.com/3drepo/3drepo.io/assets/71635617/e4c8400a-b1bb-4773-9a4d-a5f40d91d0f1

**Comment by The-Daniel** [comment]
A follow on to this comment https://github.com/3drepo/3drepo.io/pull/4557#issuecomment-1780932371
Surely all the options should be disabled if the groups list is empty EXCEPT for import groups
image

**Comment by The-Daniel** [comment]
Groups card past filter buttons ae misaligned
image

**Comment by The-Daniel** [comment]
Groups card: You cannot create a filter with a name that already exists but there is nothing preventing a user from pasting a filter with a pre-existing name
image

**Comment by The-Daniel** [comment]
### Description
Groups card: A viewer can add filters to a smart group (They can't save the group though).
They can also change the filters by deleting existing chips, or using the options button for 'Clear all' or 'Paste filters'

### Steps to replicate
Open the groups card
open a smart group
Fill out the fields for a filter
Click "Create filter"

### Current Behaviour
The user can create a filter
However this is useless since they cannot save the group

### Expected Behaviour
The create filter fields are disabled (They should not be hidden so that a viewer can click a filter chip and see what the filter does)

### Pictures/ Gifs of the error
image 
image

**Comment by Amantini1997** [comment]
## Overrides do not render when the page is refreshed on a ticket
In the viewer, open up a ticket that has some groups in "default view" with colour overrides visible.
With the ticket expanded, refresh the page.

### Expected Behaviour
The meshes should get coloured according to the colour overrides

### Actual Behaviour
The colours are not being picked

**Comment by carmenfan** [comment]
User should be able to search for issues/risks number and find matches
img-26-37-23-03-37

**Comment by carmenfan** [comment]
I'm a divider, all bugs above me are prioritised

**Comment by Amantini1997** [comment]
## Only "filtered" tickets' default pins should be visible
At the moment we can see the default pins of all the tickets.
Instead, we should only render the pins for the tickets in the tickets list.

i.e:
If a ticket is "completed" and I am looking at the open (non-completed) tickets, the former's pins should be hidden.
Also, If I am filtering the tickets using the search bar, those tickets not matching the searchQuery should not have their pins rendered

**Comment by Amantini1997** [comment]
## Search bar changes height as the user start typing
Open the custom ticket card in the viewer and start typing anything in the search bar. You'll notice that its height changes
image

### Expected Behvaiour
The bar should keep the same height unless more than one line is required

**Comment by Amantini1997** [comment]
> * [ ]  Sorting federations by container doesnt work
> 
> image

What should be the sorting criterion, just the total number of containers?

**Comment by carmenfan** [comment]
Dividing line - bugs reported above are all prioritised

**Comment by carmenfan** [comment]
#### We should show the error message provided by the backend unless it's code is UNKNOWN

image

**Comment by carmenfan** [comment]
New ticket button appears if I am a view and clicked on the body of the ticket card

img-01-31-23-02-31

**Comment by carmenfan** [comment]
Editing a newly create group brings you to the new group modal
img-01-07-23-03-07

**Comment by carmenfan** [comment]
Changing a deleted group doesn't trigger an update request, but it is overwriting some other group in the list.

I think ideally we need a modal to tell the user that the group they're trying to update has been removed and it definitely shouldn't alter another group in the list.
img-01-12-23-03-12

**Pull request merged**
