### PR TITLE
Issue 5073 - Streaming visualiser

### LINKED ISSUE #5073: Supermesh Visualiser Deployment
Making a issue so the supermesh visualiser (see issues [#537](https://github.com/3drepo/3drepounity/issues/537) on the viewer and [#414](https://github.com/3drepo/3D-Repo-Product-Team/issues/414) from the product team) can be deployed and tested.

### PR DESCRIPTION
**Pull request by FJThiel**
This fixes #5073 

PR so the supermesh visualiser (see issues https://github.com/3drepo/3drepounity/issues/537 on the viewer and https://github.com/3drepo/3D-Repo-Product-Team/issues/414 from the product team) can be deployed and tested.

Do not merge

### CODE REVIEW

**Comment by FJThiel** [comment]
@AsiteZane 
Command for activating the visualiser is:
UnityUtil.unityInstance.SendMessage('SupermeshVisualiser','ToggleVisualiser')

**Review by AsiteZane — CHANGES_REQUESTED** [review]
1. **Definition**: Dynamic update isn't clear to me, please could you advise what it should be doing?
2. **Colour gradients**: White and Black as colours can become difficult to see sometimes against certain background colours, could we try to avoid those colours if possible?
3. **Scrolling** : the scroll wheel on the mouse is very slow compared to dragging the list or dragging the scrollbar. Please increase the sensitivity so the behaviours are consistent.
4. **Clicking through supermeshes**: current behaviour when selecting a supermesh is that we isolate the supermesh and zoom to the extent of the supermesh. What I would prefer please is that the selected supermesh is instead highlighted in a colour and transparency of choice. Please consider whether just highlighting the supermesh is adequate or whether supermeshes other than the selected one need to reduce their transparency to emphasise the focus of the selected one. 
5. **Extra Buttons**: As this functionality is removed from clicking on a supermesh, -please could there also be separate button on the toolbar that allows me to isolate a supermesh and zoom extent on a supermesh - these are two separate buttons.

@sebjf please add any further comments if required.

**Review by AsiteZane — APPROVED** [review]
All working great, thank you Felix!

**Pull request closed without merging**
