### PR TITLE
Issue 3065- Streaming Milestone 1

### PR DESCRIPTION
**Pull request by sebjf**
This addresses #3065. This PR is created only to have a build made. It should not be merged.

`UnityUtil.unityInstance.SendMessage("StreamingManager","SetThreshold",100000)`

### CODE REVIEW

**Comment by sebjf** [comment]
Hi @carmenfan, just a note to say this is ready to go!

**Review by carmenfan — DISMISSED** [review]

**Comment by carmenfan** [comment]
@mosment3DRepo indexedDBcache is also merged in. Ready for review.

**Review by mosment3DRepo — DISMISSED** [review]
Approved with following settings:

image

**Review by carmenfan — APPROVED** [review]

**Pull request merged**
