### PR TITLE
ISSUE #2139 - Fix permissions update in user management

### LINKED ISSUE #2139: Permissions should onyl be updated for the user that the UI has changed
At the moment if you update one user's project/model permissions, it sends a http request to update everyone in the list:
image
image

It should really only update the person it has changed

### PR DESCRIPTION
**Pull request by m1chalkubiak**
This fixes #2139

### CODE REVIEW

**Comment by m1chalkubiak** [comment]
@carmenfan 
The fix that I did previously only fixed this issue on the project tab, now I fixed it on the models' tab as well.
But as you correctly noticed the endpoint to which we send information about updated permissions for models only supports the POST method, which ends up overwriting other users. Because of that, we would also need an update on BE side.

**Comment by carmenfan** [comment]
> @carmenfan
> The fix that I did previously only fixed this issue on the project tab, now I fixed it on the models' tab as well.
> But as you correctly noticed the endpoint to which we send information about updated permissions for models only supports the POST method, which ends up overwriting other users. Because of that, we would also need an update on BE side.

@Charence  can you look into adding patch endpoints for editing permissions?

**Comment by Charence** [comment]
> > @carmenfan
> > The fix that I did previously only fixed this issue on the project tab, now I fixed it on the models' tab as well.
> > But as you correctly noticed the endpoint to which we send information about updated permissions for models only supports the POST method, which ends up overwriting other users. Because of that, we would also need an update on BE side.
> 
> @Charence can you look into adding patch endpoints for editing permissions? We need to make sure we can also remove permissions using this, as the previous post request means to remove a user we just remove that data and overwrite the whole thing

@m1chalkubiak I'm currently implementing a PATCH endpoint on the backend for model permissions. I'm wondering if you have any preferences on the return value from the endpoint?

The current model permissions POST endpoint returns the full model settings. I think this is unnecessary.

Would it be sufficient to give `{status: ok}` as a response or do you think it may be useful to provide the updated state of `permissions`?

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak I'm currently implementing a PATCH endpoint on the backend for model permissions. I'm wondering if you have any preferences on the return value from the endpoint?
> 
> The current model permissions POST endpoint returns the full model settings. I think this is unnecessary.
> 
> Would it be sufficient to give `{status: ok}` as a response or do you think it may be useful to provide the updated state of `permissions`?

@Charence Currently, we are using this response to update the application state. So leaving it unchanged would mean no need for additional changes on the part of the FE.

**Comment by carmenfan** [comment]
> @Charence Currently, we are using this response to update the application state. So leaving it unchanged would mean no need for additional changes on the part of the FE.

@m1chalkubiak  do you actually need it? I'd imagine the front end already has the right state? I'd thought the response is redundant

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak do you actually need it? I'd imagine the front end already has the right state? I'd thought the response is redundant

@carmenfan Definitely it is doable fully on FE side, I'm just saying how it is currently done. We can change it, I will just need to do some additional refactor.

**Comment by carmenfan** [comment]
> > @m1chalkubiak do you actually need it? I'd imagine the front end already has the right state? I'd thought the response is redundant
> 
> @carmenfan Definitely it is doable fully on FE side, I'm just saying how it is currently done. We can change it, I will just need to do some additional refactor.

Let's do that, for the backend to pass it back it needs to do an extra db read for what seems like information you already know 😆

**Comment by Charence** [comment]
> > > @m1chalkubiak do you actually need it? I'd imagine the front end already has the right state? I'd thought the response is redundant
> > 
> > 
> > @carmenfan Definitely it is doable fully on FE side, I'm just saying how it is currently done. We can change it, I will just need to do some additional refactor.
> 
> Let's do that, for the backend to pass it back it needs to do an extra db read for what seems like information you already know 😆

Backend has been updated.

New endpoint is `PATCH /:teamspace/:model/permissions`

To add user permission:
```
PATCH /acme/00000000-0000-0000-0000-000000000000/permissions HTTP/1.1
[
   {
      user: "alice",
      permission: "collaborator"
   }
]
```

To add multiple permissions:
```
PATCH /acme/00000000-0000-0000-0000-000000000000/permissions HTTP/1.1
[
   {
      user: "bob",
      permission: "commenter"
   },
   {
      user: "mike",
      permission: "viewer"
   }
]
```

To remove user permission, use empty string on `permission`:
```
PATCH /acme/00000000-0000-0000-0000-000000000000/permissions HTTP/1.1
[
   {
      user: "mike",
      permission: ""
   }
]
```

Successful response:
```
{
   status: "ok"
}
```

**Comment by m1chalkubiak** [comment]
Hi @Charence 
I think there was a slight misunderstanding about which endpoint we are talking about.

So this issue is about "User management" page, Projects tab on witch we can change users permissions either for the entire project or for specific models & federations.

For projects we are using:
`/:teamspace/projects/:project`
We are sending something like that:
```json
{
"name":"3dRepo",
"permissions":[
   {
      "user":"pavol",
      "permissions":["admin_project"]
   }
]
}
```
And it's works (We are using PUT method)

For models & federations, we are sending request to:
`api/:teamspace/models/permissions`
And body looks that:
```json
[{
   "name":"Best model",
   "model":"04ca3938-9acb-4518-96eb-f55db556e8ea",
   "subModels":[],
   "permissions":[
      {
         "user":"carmen",
         "permission":"viewer"
      }
   ]
},
{
   "name":"Carmen's Model",
   "model":"14941c96-ac4a-4d24-9e63-5d04c21fa56c",
   "subModels":[],
   "permissions":[
      {
         "user":"carmen",
         "permission":"viewer"
      }
   ]
},
{
   "name":"A new model",
   "model":"797c1cb9-d6e8-4cfc-9b5d-7cc84b61fc68",
   "subModels":[],
   "permissions":[
      {
         "user":"carmen",
         "permission":"viewer"
      }
   ]
}
]
```

And currently, this will overwrite permissions for other users as the POST method is the only one that is handled on this endpoint.

Summarizing `api/:teamspace/models/permissions` is the endpoint that we need to work on, as we need to be able to send user permissions change for multiple models.

With the endpoint of a single model We would need to iterate over each chosen model and made separate API call for it, it doesn't sound like a good way to solve this issue.

**Comment by Charence** [comment]
> Summarizing `api/:teamspace/models/permissions` is the endpoint that we need to work on, as we need to be able to send user permissions change for multiple models.
> 
> With the endpoint of a single model We would need to iterate over each chosen model and made separate API call for it, it doesn't sound like a good way to solve this issue.

@m1chalkubiak OK, I will let you know when I have made changes to the multiple model permissions API.

**Comment by Charence** [comment]
> > Summarizing `api/:teamspace/models/permissions` is the endpoint that we need to work on, as we need to be able to send user permissions change for multiple models.
> > With the endpoint of a single model We would need to iterate over each chosen model and made separate API call for it, it doesn't sound like a good way to solve this issue.
> 
> @m1chalkubiak OK, I will let you know when I have made changes to the multiple model permissions API.

@m1chalkubiak This endpoint is now available at PATCH /:teamspace/models/permissions

Example usage:
```
PATCH /acme/models/permissions HTTP/1.1
[
   {
      model: "00000000-0000-0000-0000-000000000000",
      permissions: [
         {
            user: "alice",
            permission: "collaborator"
         },
         {
            user: "bob",
            permission: "commenter"
         },
         {
            user: "mike",
            permission: ""
         }
      ]
   },
   {
      model: "11111111-1111-1111-1111-111111111111",
      permissions: [
         {
            user: "charlie",
            permission: "viewer"
         }
      ]
   }
]
```

Similar to the other single model permission PATCH endpoint, removal can be achieved by setting `permission` to an empty string. `name` and `subModels` is not necessary. Only `model` ID and `permissions` needed.

The response is as discussed:
```
{
   status: "ok"
}
```

**Comment by carmenfan** [comment]
@m1chalkubiak changing this to draft so we know not to look into it. Change it back when it's ready ! :)

**Comment by m1chalkubiak** [comment]
@Charence 
Endpoint PATCH `/:teamspace/models/permissions` is working fine and this part of the task is done.

Unfortunately, I noticed that the previous part - changing of users' projects permissions, does not work well (it also overwrites the permissions of other users), but it is visible only after refreshing the page, so I did not notice it before.

It is about endpoint:
`/:teamspace/projects/:project`

on which we are using the PUT method:

```json
{
   "name":"Clinic",
   "permissions":[
      {
         "user":"Carmen",
         "permissions":[
            "admin_project"
         ]
      }
   ]
}
```

We probably should handle the PATCH method on this endpoint as well, are you will be able to help me with that?

**Comment by Charence** [comment]
> It is about endpoint:
> `/:teamspace/projects/:project`
> 
> We probably should handle the PATCH method on this endpoint as well, are you will be able to help me with that?

@m1chalkubiak This PATCH endpoint has now been added.

**Review by Charence — DISMISSED** [review]

**Review by carmenfan — CHANGES_REQUESTED** [review]
@Charence  also missing tests for the new endpoints?

**Comment by m1chalkubiak** [comment]
@carmenfan I'm just checking if you need any changes on the FE side to be done on this branch? Last time I worked on it, everything worked fine, but I see that you have made changes on the BE side, so I'd rather ask.

**Comment by carmenfan** [comment]
> @carmenfan I'm just checking if you need any changes on the FE side to be done on this branch? Last time I worked on it, everything worked fine, but I see that you have made changes on the BE side, so I'd rather ask.

No changes required right now. It's just waiting on me finding the time to look through it. Will tag you if we need your attention! Thanks!

**Comment by carmenfan** [comment]
In general it's all working, but one thing..

@m1chalkubiak 
image


These buttons seems to be permanently disabled now?

**Comment by carmenfan** [comment]
@m1chalkubiak  any thoughts? 😆

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak any thoughts? 😆

Apologies @carmenfan , I'm checking this out right now.

**Comment by m1chalkubiak** [comment]
@carmenfan I believe there was quite big problem with updating state of component responsible for rendering this permission table.  However, this problem did not come on this branch, but rather, it has occurring before. Now, simply during testing this particular subpage, it was easier to find the right case.
Because while going from the project permissions tab to the model & federation permissions which was the default user's flow everything worked fine. The problem were reproducing only when refreshing the page when we were switched to model & federation permissions tab.

Now hopefully it should work fine.

**Review by carmenfan — APPROVED** [review]

**Pull request merged**
