### PR TITLE
ISSUE #2705 shapes improvement

### LINKED ISSUE #2705: Measuring shapes algorithm modification
this is a deployment issue for https://github.com/3drepo/3drepounity/issues/391

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #2705
#### Description
- applying changes made in coupled unity ticket.

#### Test cases
- shapes will now be on a set 3D plane after the 3rd point has been selected.

### CODE REVIEW

**Comment by mosment3DRepo** [comment]
Not sure if it was supposed to, but this still hasn't fixed the original problem:

ShapeDraw

**Comment by carmenfan** [comment]
tagging @mosment3DRepo for review as it's now fixed

**Comment by carmenfan** [comment]
rolled back to the 1608c98 of the unity branch

**Comment by carmenfan** [comment]
merging in and will be tested as part of #2691

**Pull request merged**
