### PR TITLE
ISSUE #3183 - if container has no revisions you cannot open it in viewer

### LINKED ISSUE #3183: Link working on empty containers
### Description
Link working on empty containers and containers that are currently being processed even though there's nothing to load.

- This is happening in: staging
- This requires a hotfix to production: no
- 
### Steps to replicate
- Create an empty container
- Click to enter the container

### Current Behaviour
- The user can enter the container and get an error

### Expected Behaviour
- The user shouldn't be able enter the container and get an error

### PR DESCRIPTION
**Pull request by The-Daniel**
This fixes #3183

#### Description
- Prevents the user from accessing the viewer for containers that do not have any revisions

### CODE REVIEW

**Comment by george-hadfield** [comment]
Remove underline hover state from Container title when there are no revisions. Make the container title 'base.light' if there are no revisions. Change text 'Latest revision' to 'No revisions'

Build
image

Design
image

**Review by george-hadfield — CHANGES_REQUESTED** [review]
Small changes

**Comment by The-Daniel** [comment]
@george-hadfield how do you want it to work for when a container is in the process of uploading its first container (i.e. queued, processing, maybe even failed?). I assume the link should still not be clickable, but do you want the colours to change?

**Comment by george-hadfield** [comment]
If you can't load a model, please use the disabled grey as above. 
If there is a status such as those you mentioned, then use the colour as built now

image

**Review by george-hadfield — APPROVED** [review]

**Review by sanmont3drepo — APPROVED** [review]

**Pull request merged**
