### PR TITLE
ISSUE #2362 - Migration to material-ui 4.x.x

### LINKED ISSUE #2362: Upgrade material-ui
### Description
Upgrade version of material-ui library to the 4.x.x 

### Tasks
- [x] Support for forwardRef in all needed components
  - [x] `textField.component` refactor 
- [x] Update material-ui to latest version
- [x] Use Fab component instead of Button with "fab" variant
- [x] Adjust styles on login & sign-up pages
- [x] Review dashboard pages
  - [x] Align displaying of select list
  - [x] Align displaying of Tabs
  - [x] Incorrect background color during editing ticket title
  - [x] Checkboxes in User management page stopped working
  - [x] Broken styles in profile/user menu
- [x] Review model viewer components
  - [x] Expandable details in panels stopped working
  - [x] Fix react devtools warnings
  - [ ] Use new `@material-ui/pickers` instead of deprecated `material-ui-pickers`

### PR DESCRIPTION
**Pull request by m1chalkubiak**
This fixes #2362

#### Description
I've updated `material-ui` (core & icons) to the newest `4.11.2` version basing on the migration guide from the [documentation](https://material-ui.com/guides/migration-v3/).
Although I tried to adjust all differences from the previous appearance of the elements, there will certainly be places where spacing, font sizes, or generally understood spacing will be different. 
In the most visible places, I tried to adjust it, however, if you notice any place where it should be further worked on, let me know.

From the practical side, the most important changes include:
- [Button] Deprecated button variants were removed (flat, raised and fab)
 Fab variant was moved to a separate component.
- [Tooltip] The child needs to be able to hold a ref. The [composition guide](https://material-ui.com/guides/composition/#caveat-with-refs) explains the migration strategy.
- Changes in [typography variants](https://material-ui.com/guides/migration-v3/#typography)
Now default font size is 16px

The changes apply to many components that are used in a large number of places in the application, so We really should test the application as a whole comparing to the current staging to make sure that everything works properly.

### CODE REVIEW

**Review by carmenfan — CHANGES_REQUESTED** [review]
- Update Available panel is misaligned with semi colons on the page:
image

- semi colons on Notifications -> clear all confirmation dialog:
image


- Extra semi colon on error dialog:
image

- Padding and text size is very different here to before:
image
- arrow in the wrong place on treatment suggestion:
image

- `Filters` is significantly smaller than before on the groups tab (smart group):
image

- The tabs here were centred/stretched to the width of the panel:
-image

- spacing missing between revision tag and uploaded date:
image

**Comment by m1chalkubiak** [comment]
> * Update Available panel is misaligned with semi colons on the page:
> * semi colons on Notifications -> clear all confirmation dialog:
> * Extra semi colon on error dialog:
> * Padding and text size is very different here to before:
> * arrow in the wrong place on treatment suggestion:
> * `Filters` is significantly smaller than before on the groups tab (smart group):
> * The tabs here were centred/stretched to the width of the panel:
> * spacing missing between revision tag and uploaded date:

@carmenfan All the above comments have been corrected.

**Review by carmenfan — APPROVED** [review]

**Pull request merged**
