### PR TITLE
Issue 1284: Issues/Risks components

### LINKED ISSUE #1284: Migration: Issues / SafetiBase components
**Description**
Summary task

**Tasks list**
- [x] [List item](https://github.com/3drepo/3drepo.io/issues/1264)
- [x] [Details](https://github.com/3drepo/3drepo.io/issues/1265)
- [x] [Log](https://github.com/3drepo/3drepo.io/issues/1266)
- [x] [Screenshot dialog](https://github.com/3drepo/3drepo.io/issues/1268)
- [x] [Filters](https://github.com/3drepo/3drepo.io/issues/1269)
- [x] [Menu](https://github.com/3drepo/3drepo.io/issues/1270)
- [x] [New comment](https://github.com/3drepo/3drepo.io/issues/1271)

### PR DESCRIPTION
**Pull request by simplypixi**
This fixes #1284

I've decided to merge this shared branch because of two reasons:

1. We need to rebase this branch everytime we need latest changes from staging/Views.
2. You can start reviewing this part of migration before we merge risks/issues into this branch.

These components (except Screenshot dialog) are not bound to any place in the app, so you are only able to check the code.
Moreover, the screenshot dialog was checked in another PR.

Let me know if something is not understandable. ;)

### CODE REVIEW

**Comment by sanmont3drepo** [comment]
@simplypixi @dleszcz  would it better to merge #1273  to staging ?
This branch is trying to merge to an already merged branch/closed issue?

**Comment by dleszcz** [comment]
> @simplypixi @dleszcz would it better to merge #1273 to staging ?
> This branch is trying to merge to an already merged branch/closed issue?

@sanmont3drepo 
Changed.

**Comment by carmenfan** [comment]
Risks branch is branched from this right?

Would it be easier to just change risk to staging?

At the moment we really struggle to understand this code as there's no linkage  to the app use. If we just give up on this branch and merge risk to staging then we can see the change set added from this branch.

**Comment by simplypixi** [comment]
> Risks branch is branched from this right?
> 
> Would it be easier to just change risk branch to merge to staging?
> 
> At the moment we really struggle to understand this code as there's no linkage to the app use. If we just give up on this branch and merge risk to staging then we can see the change set added from this branch.

Good point!
I'll close the PR ;)

**Pull request closed without merging**
