### PR TITLE
Issue 1566 - Migration: event service

### LINKED ISSUE #1566: Migration: Event Service

### PR DESCRIPTION
**Pull request by dleszcz**
This fixes #1566

### CODE REVIEW

**Comment by carmenfan** [comment]
This looks fine, just need to actually test it once it's slightly more up to date.

**Comment by dleszcz** [comment]
> * [x]  When you edit/save a pin, you can no longer get rid of it by clicking on the background.
@carmenfan fixed!

**Comment by carmenfan** [comment]
@dleszcz 
Pins seems ok now, but the state of create issue is broken. It's not displaying the screenshot + comments section and the save button isn't disabled upon save.

(left is branch, right is staging)



And log is complaining about something when I hit save:
image

**Comment by carmenfan** [comment]
@dleszcz Nvm the bug, i just realised it's from the tree branch. Put in a note on that one.

This can be merged if conflicts are resolved.

**Comment by dleszcz** [comment]
> @dleszcz Nvm the bug, i just realised it's from the tree branch. Put in a note on that one.
> 
> This can be merged if conflicts are resolved.

@carmenfan Conflicts resolved

**Pull request merged**
