### PR TITLE
 Issue 1639: Grid view - Searching

### LINKED ISSUE #1639: Teamspaces: Searching

### PR DESCRIPTION
**Pull request by dleszcz**
This fixes #1639

### CODE REVIEW

**Comment by carmenfan** [comment]
@dleszcz  this is already merged? https://github.com/3drepo/3drepo.io/pull/1661

What's going on? 😆

**Comment by dleszcz** [comment]
> @dleszcz this is already merged? #1661
> 
> What's going on? 😆

Oh, my mistake :( I thought that is not already merged because on GH issue page I didn't see merge commits (because there are showed only commits with issue number in message)

It should be 1608 into tree

**Comment by dleszcz** [comment]
@carmenfan According to your mail. I did pull on my local ISSUE_1608 branch and its looking good I think.

Screenshot 2019-09-24 at 14 47 24

**Comment by carmenfan** [comment]
@dleszcz 

Just 1608 -> 1475. 1590 is already merged into 1475 via https://github.com/3drepo/3drepo.io/pull/1607

**Pull request closed without merging**
