### PR TITLE
ISSUE #3317 - SafetiBase - Risk details

### LINKED ISSUE #3317: Safeti base - Risk details
### Description
Safeti base  in the viewer  has a broken ui in v5 - we need to update it to make it usable for users.

### Goals
- [ ] As a user I want to use safetibase in v5 with the ui that matches the rest of  v5

### Tasks
- [ ] Fix the layout
- [ ] Update the background colour
- [ ] Update the description field UI
- [ ] Update the Level of risk UI
- [ ] Match the files ui to the new one

### Related Resources

How it looks now:

How it should look:
[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136550%3A176546)

### PR DESCRIPTION
**Pull request by The-Daniel**
This fixes #3317 

#### Description
- fixes the styling in the V5 viewer for the SafetiBase Risk tab

#### Test cases
- View existing SafetiBase risks
- Create a new SafetiBase risk and check the UI isn't whack.

### CODE REVIEW

**Review by Amantini1997 — APPROVED** [review]

**Comment by george-hadfield** [comment]
### Change styling of input fields to new style
Treatment and Treatment details are using the old style inputs, can these be change to the new one? Also, the Suggest button is too close to the section above - move all fields down to create space.

image

**Comment by george-hadfield** [comment]
### Spacing between field labels and titles needs fixing

image

**Comment by george-hadfield** [comment]
### Alignment of save and clear icons needs fixing

image

**Review by george-hadfield — CHANGES_REQUESTED** [review]
Some issues to address

**Comment by The-Daniel** [comment]
> Some issues to address

This PR is just for the Risk tab. The other tabs haven't been touched yet

**Comment by george-hadfield** [comment]
The risk details tab is fine and approved

**Review by george-hadfield — APPROVED** [review]

**Pull request merged**
