### PR TITLE
ISSUE #2904 - Responsive federations list

### LINKED ISSUE #2904: Revamping -  Federations responsiveness
### Description
Federations should be able to handle  when the browser is resized

### Goals
- [ ] Columns should scale the same as containers
- [ ] Responsive: Content needs margin left and right at smaller breakpoints.

### Tasks
- [ ] ...

### Related Resources
image

[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3274%3A46976)

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #2904 

#### Description
- Responsive desing for federations
- It hides the columns of the federations list as the user resizes the window

#### Test cases
- Resize the window and see how it responds in this [link](https://issue-2904.dev.3drepo.io/v5/dashboard)

### CODE REVIEW

**Comment by mosment3DRepo** [comment]
### Odd drop at 1024px wide

When you resize the width below 1024 the area above the accordion doubles in height
ResizeDrop1

**Comment by george-hadfield** [comment]
Yeah I'd be happy with that. Approved from my end.

**Comment by mosment3DRepo** [comment]
# New Federation Priority over Search box

I think we should fix the New Federation button and reduce the size of the search box on width changes @george-hadfield  thoughts?

new proposal on top, current implementation on the bottom:
search compress

**Comment by george-hadfield** [comment]
The current implementation is not how I've seen this previously. Should
work how it does on the containers section. Has there been a deployment
issue with an old version?

**Comment by sanmont3drepo** [comment]
> # New Federation Priority over Search box
> I think we should fix the New Federation button and reduce the size of the search box on width changes @george-hadfield thoughts?
> 
> new proposal on top, current implementation on the bottom: search compress

The problems with that bit will be adressed in this issue:
https://github.com/3drepo/3drepo.io/issues/2927

Regarding to the list is there anything else?

**Review by george-hadfield — APPROVED** [review]

**Review by carmenfan — APPROVED** [review]

**Pull request merged**
