### PR TITLE
ISSUE #2936 - ODA upgrade testing branch

### PR DESCRIPTION
**Pull request by keifgwinn**
This deployment is a way to access fixes 3DRepoBouncer [#523](https://github.com/3drepo/3drepobouncer/issues/523)
and DevOps link https://github.com/3drepo/DevOps/issues/310

#### Description

Access to upgraded ODA 22.11

### CODE REVIEW

**Comment by carmenfan** [comment]
@mosment3DRepo ready for testing

**Comment by carmenfan** [comment]
Deprecated in favour of #2974.

Can destroy @keifgwinn

**Comment by keifgwinn** [comment]
deleted resources

**Pull request closed without merging**
