### PR TITLE
Issue 4435 - new Modal design

### LINKED ISSUE #4435: New Modal styling
### Description
Use the new styling for modals

### Goals
- [ ] replace the old modal styling with the new one

### Tasks

- [ ] Check the viewer uses the new styling everywhere
- [ ] Check v5 uses the new styling everywhere

### Related Resources
[link](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=605-38114&mode=design&t=1wF7IkcDT6QROuZV-0)

### PR DESCRIPTION
**Pull request by Amantini1997**
This fixes #4435

#### Description
The design for modals was updated.
This PR updated the colours, fonts, and shapes of those elements accordingly

#### Test cases
There are several modals across the app:
- some from V5 in the dashboard;
- some from V4 in the dashboard;
- some from V4 in the viewer;
Make sure all of them abide to the new design

### CODE REVIEW

**Comment by Charence** [comment]
@mehfshaikh and @Charence to investigate deployment

**Review by george-hadfield — APPROVED** [review]

**Comment by The-Daniel** [comment]
@george-hadfield says the upload file modal should have a white header so that the sidebar doesn't look like it's floating. I'm happy other than that

**Review by The-Daniel — APPROVED** [review]

**Pull request merged**
