### PR TITLE
ISSUE 2700 - upgrade dependencies

### LINKED ISSUE #2700: Address vulnerabilities
### Description
Address alerts from Dependabot https://github.com/3drepo/3drepo.io/security/dependabot

### Goals

- [x] Address critical vulnerabilities
- [x] Address high severity vulnerabilities
- [x] Address moderate severity vulnerabilities

### Tasks

- ~html-pdf~
- [x] nodemailer
- [x] lodash
- [x] pug
- [x] socket.io
- [x] axios

### Related Resources

https://github.com/3drepo/3drepo.io/security/dependabot

### PR DESCRIPTION
**Pull request by Charence**
This fixes #2700 

#### Description
- Upgrade dependencies identified by dependabot to have vulnerabilities

#### Test cases
- Backend and frontend should work as before
- Dependabot identified issues should be resolved

### CODE REVIEW

**Review by carmenfan — CHANGES_REQUESTED** [review]
Socket.io connection is broken. Moving issues across column around kanban is not updating on another client

**Comment by Charence** [comment]
> Socket.io connection is broken. Moving issues across column around kanban is not updating on another client

Fixed! Frontend version wasn't matching.

**Review by carmenfan — APPROVED** [review]

**Pull request merged**
