### PR TITLE
ISSUE #2942 - Users permissions

### LINKED ISSUE #2942: Project user permissions
### Description
To have project permissions in v5 we are going to reuse and re-style the component from v4. 

### Goals
- [x]  Reuse the functionality from v4

### Tasks
- [x] add a route 'user permissions' with a mockup component 
- [x] Try to embed the v4 project persmissions component in  the new route
- [x] Add some prop to pass on the selected project from v5 instead of selecting it from the select box
- [x] Remove the select box if the component is in the v5 environment
- [x] Change model to container (support v4 model naming still?)
- [x] Re-style thecomponent to match the changes

### Related Resources
[Ui Design](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3329%3A48228)

### PR DESCRIPTION
**Pull request by sanmont3drepo**
This fixes #2942 

#### Description
- Laid groundwork to reuse v4 components
- Added a new route/tabe in the projects page : "users permissions"
- Reused ModelPermissions from v4
- Reused ProjectPermissions from v4
- [Url for testing](https://issue-2942.dev.3drepo.io/v5/dashboard)

### CODE REVIEW

**Comment by george-hadfield** [comment]
### Add padding/margin to top of selector/toggle and bottom of tabs
Just needs about an extra 10px spacing

image

**Comment by george-hadfield** [comment]
### Move column headers closer to radio buttons
Reduce padding/margin by around half of what it is currently

Image
image

**Comment by george-hadfield** [comment]
### Increase padding inside toggle
Text is too close to the borders. Increase by around 5px either side of text

Image
image

**Comment by george-hadfield** [comment]
### Bring tooltips closer to column header radio buttons
Currently they are floating quite some distance away from the cursor

Image
image

**Comment by george-hadfield** [comment]
### Change teal underline on search to tertiary blue

image

**Review by carmenfan — APPROVED** [review]

**Pull request merged**
