### PR TITLE
Issue 1567: Migration - Chat service

### LINKED ISSUE #1567: Migration: Chat service

### PR DESCRIPTION
**Pull request by simplypixi**
This fixes #1567

### CODE REVIEW

**Comment by simplypixi** [comment]
@carmenfan During this migration I noticed that BE doesn't send one field (`guid`) on log remove event. It crashes the log list. 
Verified on staging branch.

**Comment by carmenfan** [comment]
> @carmenfan During this migration I noticed that BE doesn't send one field (`guid`) on log remove event. It crashes the log list.
> Verified on staging branch.

@sanmont3drepo can you take a look?

**Comment by sanmont3drepo** [comment]
In the current version and older versions  it uses this type of chat message, using the commentIndex to sort which comment should be deleted:
`42["teamSpace1::3549ddf6-885d-4977-87f1-eeac43a0e818::25266280-8df4-11e9-b1ac-975a1f33f576::commentDeleted",{"comment":"","number":1,"delete":true,"commentIndex":4,"requester":"teamSpace1","sessionId":"QPQ_QPCem5SKcRxrAAAA"}]`

In the #1498 PR it uses a `{_id:"XXXX"}` type of message for deleting the comment.

So maybe we should wait until that PR is merged.

**Comment by simplypixi** [comment]
> So maybe we should wait until that PR is merged.

@sanmont3drepo @carmenfan 
Unfortunately, we need to merge all migration PR before we get rid of the Angular.
If it is everything ok, I think we can merge this PR - the bug appears also on staging so the PR doesn't change anything in that case. Instead of waiting we should create a new issue.
What do you think?

**Comment by carmenfan** [comment]
> > So maybe we should wait until that PR is merged.
> 
> @sanmont3drepo @carmenfan
> Unfortunately, we need to merge all migration PR before we get rid of the Angular.
> If it is everything ok, I think we can merge this PR - the bug appears also on staging so the PR doesn't change anything in that case. Instead of waiting we should create a new issue.
> What do you think?

What @sanmont3drepo meant was that this is not a problem anymore once his PR is merged. So he was suggesting to wait for it. Also he thinks most likely there'll be conflicts with this branch.

We'll merge this to 1539, but bear in mind that the conflicts will have to resolved there as the @sanmont3drepo 's branch will most likely be merged in before that one.

**Comment by sanmont3drepo** [comment]
Found a couple of bugs:
- New notification chat event doesn't work.
received message:
notification insert message
javascript error:
notification insert-error-notifications realtime

- When someone else creates a comment in issues and you receive the message of the comment created it duplicates the comment and also throws an error:
insert comment error

- When someone else updates the issue it adds a empty comment instead of the system comment and throws an error:
error change issue

**- Similar problems happens with risks** 

- When someone else  deletes a group it throws an error:
error deleting group

- When you are creating a viewpoint it throws an error and get stuck in edit mode. Not sure if this has to do with the chat service, but I tried it in staging and it works there

**Comment by simplypixi** [comment]
@sanmont3drepo Each "mutation detection" event/error is also appearing on staging, the difference is we added new dev tool (on the Tree branch, which is parent of this one) to detect potential state mutations. So those issues already exist, but earlier we weren't able to find it. Obviously, the tool is enabled only in development mode.

We can fix them on this branch or just create a new ticket and do it later. It's up to you.
Just let me know about the decision.

The rest will be fixed ;)

**Comment by simplypixi** [comment]
> * When someone else creates a comment in issues and you receive the message of the comment created it duplicates the comment and also throws an error:

As far as I remember it's caused by missing id - the issue that I mentioned at the beginning.

**Comment by sanmont3drepo** [comment]
> * hen someone else creates a comment in issues and you receive the message of the comment created it duplicates the comment and also throws an


> > * When someone else creates a comment in issues and you receive the message of the comment created it duplicates the comment and also throws an error:
> 
> As far as I remember it's caused by missing id - the issue that I mentioned at the beginning.

In this case is sending the id:
image

Maybe you were expecting a "_id" field instead of guid?

**Comment by dleszcz** [comment]
> > * hen someone else creates a comment in issues and you receive the message of the comment created it duplicates the comment and also throws an
> 
> > > * When someone else creates a comment in issues and you receive the message of the comment created it duplicates the comment and also throws an error:
> > 
> > 
> > As far as I remember it's caused by missing id - the issue that I mentioned at the beginning.
> 
> In this case is sending the id:
> image
> 
> Maybe you were expecting a "_id" field instead of guid?

Hi @sanmont3drepo Can you check this bug once again?

**Comment by sanmont3drepo** [comment]
> > > * hen someone else creates a comment in issues and you receive the message of the comment created it duplicates the comment and also throws an
> > 
> > 
> > > > * When someone else creates a comment in issues and you receive the message of the comment created it duplicates the comment and also throws an error:
> > > 
> > > 
> > > As far as I remember it's caused by missing id - the issue that I mentioned at the beginning.
> > 
> > 
> > In this case is sending the id:
> > image
> > Maybe you were expecting a "_id" field instead of guid?
> 
> Hi @sanmont3drepo Can you check this bug once again?
Hi @dleszcz , it seems that now it doesn't do the duplicate thing, but  noticed two other things:
- The order of the comments is wrong  
- The update property comments insert as blank 

chatservice

**Comment by dleszcz** [comment]
@sanmont3drepo 
I think we probably get bad id from the chat server. Can you verify this?

New comment object from chat server:
Screenshot 2019-06-28 at 12 07 24

Comments list with new object:
Screenshot 2019-06-28 at 12 08 00

**Comment by sanmont3drepo** [comment]
> @sanmont3drepo
> I think we probably get bad id from the chat server. Can you verify this?
> 
> New comment object from chat server:
> Screenshot 2019-06-28 at 12 07 24
> 
> Comments list with new object:
> Screenshot 2019-06-28 at 12 08 00

Hi @dleszcz  we took a look at staging and the guid is not the same as it is when you get the result from the request that get the comments for the issues ( I think is the issue details request) .
Even though the guid is not the same, it should work correctly besides the part of the deletion (in that case the remote deletion wouldnt match any  comment id).
Also the remote system logs should work (the data being sent in the chat is the right one).  

This two things are not working properly in master (also staging), it seems that between the migration of the issue component and the latest release there was some change that was introduced that broke the feature. 

So before this branch gets merge ( or before the #1539) we are merging the #1529  (that one should be merge really soon) and also #1599

**Comment by simplypixi** [comment]
> > @sanmont3drepo
> > I think we probably get bad id from the chat server. Can you verify this?
> > New comment object from chat server:
> > Screenshot 2019-06-28 at 12 07 24
> > Comments list with new object:
> > Screenshot 2019-06-28 at 12 08 00
> 
> Hi @dleszcz we took a look at staging and the guid is not the same as it is when you get the result from the request that get the comments for the issues ( I think is the issue details request) .
> Even though the guid is not the same, it should work correctly besides the part of the deletion (in that case the remote deletion wouldnt match any comment id).
> Also the remote system logs should work (the data being sent in the chat is the right one).
> 
> This two things are not working properly in master (also staging), it seems that between the migration of the issue component and the latest release there was some change that was introduced that broke the feature.
> 
> So before this branch gets merge ( or before the #1539) we are merging the #1529 ( fixes to delete comments, that one should be merge really soon) and #1599 that will fix the problems in the UI and the mismatch guid.

@sanmont3drepo 
Summing up - we can leave it as it is, but we'll have to check that after rebasing this branch or (#1539) on staging with fixes. Am I right? :P
Let me know if I understood something incorrectly. :)

**Comment by sanmont3drepo** [comment]
> > > @sanmont3drepo
> > > I think we probably get bad id from the chat server. Can you verify this?
> > > New comment object from chat server:
> > > Screenshot 2019-06-28 at 12 07 24
> > > Comments list with new object:
> > > Screenshot 2019-06-28 at 12 08 00
> > 
> > 
> > Hi @dleszcz we took a look at staging and the guid is not the same as it is when you get the result from the request that get the comments for the issues ( I think is the issue details request) .
> > Even though the guid is not the same, it should work correctly besides the part of the deletion (in that case the remote deletion wouldnt match any comment id).
> > Also the remote system logs should work (the data being sent in the chat is the right one).
> > This two things are not working properly in master (also staging), it seems that between the migration of the issue component and the latest release there was some change that was introduced that broke the feature.
> > So before this branch gets merge ( or before the #1539) we are merging the #1529 ( fixes to delete comments, that one should be merge really soon) and #1599 that will fix the problems in the UI and the mismatch guid.
> 
> @sanmont3drepo
> Summing up - we can leave it as it is, but we'll have to check that after rebasing this branch or (#1539) on staging with fixes. Am I right? :P
> Let me know if I understood something incorrectly. :)

I'm suggesting to wait for the changes and do all the fixes in this branch in order to minimize the conflicts that you will encounter when rebasing and changing the chat code, if you do it in #1539  after #1567  gets merge it might be harder to resolve the conflicts, because you will be dealing with the conflicts of that branch plus the conlicts on this one.

I'd also suggest that you keep #1539 as updated as posible because resolving all conflicts will be painful if you leave it outdated. 

But whatever suits your process.

**Comment by simplypixi** [comment]
@sanmont3drepo Tbh, It'll be best to merge everything (after review) to  #1539 and then rebase #1539 on updated staging (once).
So if everything (besides that bug) is ok, I suggested merging the PR.
Just leave approve if you are in.

**Comment by simplypixi** [comment]
@sanmont3drepo @carmenfan Can we merge this PR?

**Comment by sanmont3drepo** [comment]
> @sanmont3drepo @carmenfan Can we merge this PR?

Yes

**Pull request merged**
