### PR TITLE
ISSUE 5166 - Upgrade APM dep

### LINKED ISSUE #5166: Upgrade APM dep
### Description
We're currently using `elastic-apm-node` `3.41.1`. APM has stopped reporting to Elastic Cloud following upgrade to Elastic 8.15.1.

### Suggested solution
Try upgrading.

### PR DESCRIPTION
**Pull request by Charence**
This fixes #5166

#### Description
- Upgrade to latest 4.7.3

#### Test cases
- Check APM on Elastic Cloud

### CODE REVIEW

**Comment by Charence** [comment]
APM data appears to be back:

image

image

**Review by carmenfan — DISMISSED** [review]
@Charence looks fine, please decomission the queue and reset build-and-deploy before merging

**Pull request merged**
