### PR TITLE
ISSUE #3146 - Teamspace Selection

### LINKED ISSUE #3146: Teamspace selection
### Description
As the user I want to have a place where I can see my teamspaces and navigate to the one I have selected.

### Goals
- [ ] As a user I want to see the teamspaces I'm member of.
- [ ] As a user I want to navigate to the content of the teamspace I want
- [ ] As a user I want to be able to create a new teamspace

### Tasks
- [ ] Create the teamspace card component 
- [ ] Make the teamspace card component a link to the teamspace (the projects list for that teamspace)
- [ ] List  your teamsapces
- [ ] New teamspace is a link for creating a mail ([mailto](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_mailto)) . Check with @mosment3DRepo  for the content/subject of the email.

**Mailto for new Teamspace**
```
To: "support@3drepo.org"
Subject: "New 3D Repo Teamspace"
Body: "3D Repo Team, I would like to set up a new Teamspace"
```

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=6015%3A42627)

### PR DESCRIPTION
**Pull request by The-Daniel**
This fixes #3146 

#### Description
- Adds a teamspace selection screen that can be accessed after log in
- Clicking Add new teamspace opens up an email with a template message
- Clicking the home icon anywhere on the app sends you to the teamspace selection screen
- Personal teamspaces and shared teamspaces have default images if the teamspace has no image

#### Test cases
- Can click on teamspace card to open up teamspace
- Can open up an email to request a new teamspace by clicking the 'New Teamspace' card

### CODE REVIEW

**Comment by george-hadfield** [comment]
image

Getting this with both #3181 and #3146

**Comment by george-hadfield** [comment]
### Change layout to show a maximum of 3 cards per row (currently 4)

image

**Comment by george-hadfield** [comment]
### Make the '+' in Add new Teamspace white

image

**Comment by george-hadfield** [comment]
### Circle used in New Teamspace should be 32px (currently 27px)

image

Also, give a bit more spacing between the circle and the text below (check design)

**Comment by carmenfan** [comment]
> ### New teamspace card moves when hovering on other Teamspace cards#3140
> image
> 
> image

@george-hadfield @mosment3DRepo 

I thought the avatars are suppose to scale to cover the whole white box instead of centered? or did we decide against it?

**Comment by george-hadfield** [comment]
> > ### New teamspace card moves when hovering on other Teamspace cards#3140
> > image
> > image
> 
> @george-hadfield @mosment3DRepo
> 
> I thought the avatars are suppose to scale to cover the whole white box instead of centered? or did we decide against it?

Yes they should. Was going to be my next issue :)

**Comment by george-hadfield** [comment]
### Teamspace avatars should fill the white box. 

We will upload logos for clients with a white background to save any scaling issues. The issue is that some people may use an image, instead of a logo for their own Teamspace which looks odd with white space around it

image

**Comment by The-Daniel** [comment]
@george-hadfield should these have placeholders like your personal teamspace (e.g. if Carmen's teamspace didn't have an image it would become 'CF'), or should it default to a 3D Repo logo or something else?

**Comment by george-hadfield** [comment]
> @george-hadfield should these have placeholders like your personal teamspace (e.g. if Carmen's teamspace didn't have an image it would become 'CF'), or should it default to a 3D Repo logo or something else?

I would use initials in this case

**Comment by george-hadfield** [comment]
### Align text correctly in Teamspace cards

Only the 'ghadfield' one has the correct text alignment, the rest look like the text is too low down.

image

**Review by george-hadfield — CHANGES_REQUESTED** [review]
Couple of issues to address

**Comment by The-Daniel** [comment]
@carmenfan what did you say the 'Add teamspace' card should do?

**Comment by carmenfan** [comment]
> @carmenfan what did you say the 'Add teamspace' card should do?

I said it should probably link to `contact us` in 3drepo.com instead of the `mailto:`

but andrew said there's a ask for quote page so maybe there's a better link... @mosment3DRepo  thoughts?

**Comment by The-Daniel** [comment]
> > > @carmenfan what did you say the 'Add teamspace' card should do?
> > 
> > 
> > I said it should probably link to `contact us` in 3drepo.com instead of the `mailto:`
> > but andrew said there's an `ask for quote` page so maybe there's a better link ([pricing page](https://3drepo.com/pricing/)?)... @mosment3DRepo  thoughts?
> > EDIT: looking at the Request a quote form it def makes sense to direct the user there than a free form email
> > image
> 
> Agreed, this makes more sense from a lead generation point of view

I'm currently not able to link to a modal (it might be possible with an html id and some javascript magic on the website) so should I just link to the pricing page?

**Comment by mosment3DRepo** [comment]
> > > > @carmenfan what did you say the 'Add teamspace' card should do?
> > > 
> > > 
> > > I said it should probably link to `contact us` in 3drepo.com instead of the `mailto:`
> > > but andrew said there's an `ask for quote` page so maybe there's a better link ([pricing page](https://3drepo.com/pricing/)?)... @mosment3DRepo  thoughts?
> > > EDIT: looking at the Request a quote form it def makes sense to direct the user there than a free form email
> > > image
> > 
> > Agreed, this makes more sense from a lead generation point of view
> 
> I'm currently not able to link to a modal (it might be possible with an html id and some javascript magic on the website) so should I just link to the pricing page?

Use the pricing page for now, I'm just checking whether Ben can get a hyperlink for the form in WordPress

**Comment by The-Daniel** [comment]
@george-hadfield ready for another review

**Comment by george-hadfield** [comment]
### Bottom row should always be centered under first row

image

**Review by george-hadfield — CHANGES_REQUESTED** [review]
Just the card alignment. Happy for this to go after the alignment is done

**Comment by george-hadfield** [comment]
### Move title and cards down 
The title and cards need to be moved down slightly as they are currently centred to the whole screen. The top of the 'welcome' title and the bottom of the last card should have equal spacing from the bottom of the browser to the line below the navigation bar

image

**Comment by The-Daniel** [comment]
> ### Move title and cards down
> 
> The title and cards need to be moved down slightly as they are currently centred to the whole screen. The top of the 'welcome' title and the bottom of the last card should have equal spacing from the bottom of the browser to the line below the navigation bar
> 
> image

So the content should be vertically centred? I.e. the spacing above and below will change depending on how many lines the cards take up so that they're always centred

**Comment by george-hadfield** [comment]
### At a smaller breakpoint the layout needs fixing

We need to introduce a scrollbar to the page and change the `max-width` to `85vw`.

Build
image

With 85vw
image

Add padding or margin above the title so this doesn't happen
image

**Review by george-hadfield — CHANGES_REQUESTED** [review]
One issue left

**Review by sanmont3drepo — CHANGES_REQUESTED** [review]

**Review by george-hadfield — APPROVED** [review]

**Review by sanmont3drepo — APPROVED** [review]

**Pull request merged**
