### PR TITLE
ISSUE #4525 - New Logo

### LINKED ISSUE #4525: Update 3drepo logo
### Description
Because we are part of asite now we need to update the logo in all the places where they are to reflect the state of the company

### Goals
- [ ] Get users to know that we are now part of asite

### Tasks
- [ ] Update the logo in the login/signup pages
- [ ] Update the logo in the footer of the dashboard pages

### Related Resources
[
Images](https://asitesol.sharepoint.com/sites/3DRepoTeamFolder/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2F3DRepoTeamFolder%2FShared%20Documents%2FMarketing%2FLogos%2FAsite%203D%20Repo%20Logos%2FPNG&p=true&ct=1697545608534&or=Teams%2DHL&ga=1&LOF=1)

### PR DESCRIPTION
**Pull request by The-Daniel**
This fixes #4525 

#### Description
Updated the company logo
Gave the logos consistent naming

#### Test cases
Check that the logo looks fine:
- On the login page
- On the sign up page
- In the footers of the dashboard
- In the V4 dashboards
- In the V4 Viewer
- In the javascript is disabled warning page ([how to](https://developer.chrome.com/docs/devtools/javascript/disable/))

### CODE REVIEW

**Comment by Amantini1997** [comment]
I am sure this is not a big deal at all and I am just being pecky, but the logo in the footer is now closer to the side
image

**Comment by Amantini1997** [comment]
In the registration email, we say Asite 3D Repo, but also only 3D Repo. Is that important?
image

**Comment by Amantini1997** [comment]
In local I have this logo in the viewer, which I can see has not been updated. However, I am not able to see it in the deployed branch. Should this get fixed?
image

**Comment by Amantini1997** [comment]
I know this is outside the scope of this issue, but should this be fixed?
image
(the other 2 tabs have "Asite" in the title)
image

**Comment by carmenfan** [comment]
> I know this is outside the scope of this issue, but should this be fixed? image (the other 2 tabs have "Asite" in the title) image

Yea change it please

**Comment by carmenfan** [comment]
> In local I have this logo in the viewer, which I can see has not been updated. However, I am not able to see it in the deployed branch. Should this get fixed? image

don't worry about this one

**Comment by carmenfan** [comment]
> In the registration email, we say Asite 3D Repo, but also only 3D Repo. Is that important? image

It's fine, 3D Repo is the product, Asite 3D Repo Ltd is the company name i guess

**Review by carmenfan — APPROVED** [review]

**Review by Amantini1997 — APPROVED** [review]

**Pull request merged**
