### PR TITLE
Issue 1639: Teamspaces: Searching/Sorting/Items design

### LINKED ISSUE #1639: Teamspaces: Searching

### PR DESCRIPTION
**Pull request by simplypixi**
This fixes #1639 

Also includes sorting and the rest of the design changes.

### CODE REVIEW

**Comment by simplypixi** [comment]
@carmenfan Searching and sorting are ready.
Because of showing in some cases almost all items as expanded we are struggling with performance issue (while searching).
Nevertheless, you can test the PR - just bear in mind this bug while testing this PR.
In the meantime, we will work on the fix.

**Comment by simplypixi** [comment]
> @carmenfan Searching and sorting are ready.
> Because of showing in some cases almost all items as expanded we are struggling with performance issue (while searching).
> Nevertheless, you can test the PR - just bear in mind this bug while testing this PR.
> In the meantime, we will work on the fix.

@carmenfan 
We did everything we could about the performance case. Could you look at this PR and let us know if the performance acceptable?

**Comment by simplypixi** [comment]
> * Can we remove the firstname/second name? I know Pavol specified it, but we now agree that it doesn't make much sense 😆
> * [ ]  Can we move the project names back to the left? And bring back the icon (that becomes an outline when expanded) something like this:

I thought so! :D

**Comment by simplypixi** [comment]
> * the search term should be bolded instead of the non search term:

Model/Federation name is bolded by default - but more than highlighted query.
Should we set the name as unbolded or make the levels equal?

> Search speed in general is ok I think. But it takes a little bit longer than expected if I'm removing search term / cancelling the search. Anything we can do about that?

Yep. This is the case which I mentioned.
To be honest, we tried a lot of approaches to speed up the rendering process after removing the filter, but each of these solutions wasn't good enough. A browser just has a lot to do while cleaning up the DOM (during a transition between two different results lists).

I have two ideas yet:
- using icon-font instead of svgs to render model/federation menu
- using react-window to render only the elements which are in the viewport

I'm not sure if they will change something significantly.
On the other hand, we won't find out if we don't try. :P

**Comment by simplypixi** [comment]
> Unchecking federations on the search term should filter out all the federations as a result, unless project is checked and it satisfy the search term (then it should display everything it has)


@carmenfan 

I think we have to write down cases. :)

I assume a query is set for each case.

**C.1 - Selected: models**
1. models - only models which meet the query and/or other filters
2. federations - none
3. projects - only projects with nested results

**C.2 - Selected: models, federations**
1. models - only models which meet the query and/or other filters
2. federations - only feerations which meet the query and/or other filters
3. projects - only projects with nested results

**C.3 - Selected: models, federations, projects **
1. models - only models which meet the query and/or other filters
2. federations - only federations which meet the query and/or other filters
3. projects - projects with nested results or projects which meet the query but without nested results

**C.4 - Selected: projects **
1. models - all models if project meets the query; none if doesn't
2. federations - all federations if project meets the query; none if doesn't
3. projects - only projects, which meet the query

Let me know what you think ;)

**Comment by carmenfan** [comment]
@simplypixi 

> Model/Federation name is bolded by default - but more than highlighted query.
Should we set the name as unbolded or make the levels equal?

Would it be possible to keep the font of the original model names, but make the search time change colour (e.g. dark green)?

> Yep. This is the case which I mentioned.

> To be honest, we tried a lot of approaches to speed up the rendering process after removing the filter, but each of these solutions wasn't good enough. A browser just has a lot to do while cleaning up the DOM (during a transition between two different results lists).
> 
> I have two ideas yet:
> 
> using icon-font instead of svgs to render model/federation menu
> using react-window to render only the elements which are in the viewport
> I'm not sure if they will change something significantly.
> On the other hand, we won't find out if we don't try. :P

ok XD It's not the end of the world slow, it was just significant enough to ask 

> 
> I think we have to write down cases. :)
> 
> I assume a query is set for each case.
> 
> C.1 - Selected: models
> 
> models - only models which meet the query and/or other filters
> federations - none
> projects - only projects with nested results
> C.2 - Selected: models, federations
> 
> models - only models which meet the query and/or other filters
> federations - only feerations which meet the query and/or other filters
> projects - only projects with nested results
> C.3 - Selected: models, federations, projects
> 
> models - only models which meet the query and/or other filters
> federations - only federations which meet the query and/or other filters
> projects - projects with nested results or projects which meet the query but without nested results
> C.4 - Selected: projects
> 
> models - all models if project meets the query; none if doesn't
> federations - all federations if project meets the query; none if doesn't
> projects - only projects, which meet the query
> Let me know what you think ;)

C3. 
Models/federations which belongs to projects that matches the query should be shown. (Not sure if this is what you mean by other filters)

Other than that. Yes i think this makes sense.

If it helps at all with the speed, I think it is ok to show project matching query as collapsed?

**Comment by dleszcz** [comment]
Hello @sanmont3drepo 

I see build failed on the file you created _linkableField.component.tsx_
Can you take a look? Or maybe it's fixed on some branch? :)

**Comment by sanmont3drepo** [comment]
> Hello @sanmont3drepo
> 
> I see build failed on the file you created _linkableField.component.tsx_
> Can you take a look? Or maybe it's fixed on some branch? :)
> 
> ```
>  69% building 7002/7016 modules 14 active ...nkableField/linkableField.component.tsx
> <--- Last few GCs --->
> 
> [26855:0x103800000]   879562 ms: Mark-sweep 1360.5 (1441.7) -> 1360.5 (1441.7) MB, 844.1 / 0.0 ms  allocation failure GC in old space requested
> [26855:0x103800000]   880844 ms: Mark-sweep 1360.5 (1441.7) -> 1360.5 (1426.7) MB, 1163.2 / 0.0 ms  last resort GC in old space requested
> [26855:0x103800000]   881859 ms: Mark-sweep 1360.5 (1426.7) -> 1360.5 (1426.7) MB, 1015.1 / 0.0 ms  last resort GC in old space requested
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 0x1c724d225879 <JSObject>
>     1: tryStatSync(aka tryStatSync) [fs.js:~514] [pc=0x2a494b53e942](this=0x1c72c2d022d1 <undefined>,fd=13,isUserFd=0x1c72c2d023e1 <false>)
>     2: readFileSync [fs.js:~548] [pc=0x2a494bf69516](this=0x1c72db4ffcc9 <Object map = 0x1c72962b9d59>,path=0x1c72f1146989 <String[89]: /Users/dleszczynski/Sites/3drepo.io/frontend/node_modules/@material-ui/icons/package.json>,options=0x1c72c2d022d1 <undefin...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
>  1: node::Abort() [/Users/dleszczynski/.nvm/versions/node/v8.11.3/bin/node]
>  2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/dleszczynski/.nvm/versions/node/v8.11.3/bin/node]
>  3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/dleszczynski/.nvm/versions/node/v8.11.3/bin/node]
>  4: v8::internal::Factory::NewCodeRaw(int, bool) [/Users/dleszczynski/.nvm/versions/node/v8.11.3/bin/node]
>  5: v8::internal::Factory::NewCode(v8::internal::CodeDesc const&, unsigned int, v8::internal::Handle<v8::internal::Object>, bool, int) [/Users/dleszczynski/.nvm/versions/node/v8.11.3/bin/node]
>  6: v8::internal::CodeGenerator::MakeCodeEpilogue(v8::internal::TurboAssembler*, v8::internal::EhFrameWriter*, v8::internal::CompilationInfo*, v8::internal::Handle<v8::internal::Object>) [/Users/dleszczynski/.nvm/versions/node/v8.11.3/bin/node]
>  7: v8::internal::compiler::CodeGenerator::FinalizeCode() [/Users/dleszczynski/.nvm/versions/node/v8.11.3/bin/node]
>  8: v8::internal::compiler::PipelineImpl::FinalizeCode() [/Users/dleszczynski/.nvm/versions/node/v8.11.3/bin/node]
>  9: v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl() [/Users/dleszczynski/.nvm/versions/node/v8.11.3/bin/node]
> 10: v8::internal::Compiler::FinalizeCompilationJob(v8::internal::CompilationJob*) [/Users/dleszczynski/.nvm/versions/node/v8.11.3/bin/node]
> 11: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions() [/Users/dleszczynski/.nvm/versions/node/v8.11.3/bin/node]
> 12: v8::internal::StackGuard::HandleInterrupts() [/Users/dleszczynski/.nvm/versions/node/v8.11.3/bin/node]
> 13: v8::internal::Runtime_StackGuard(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/dleszczynski/.nvm/versions/node/v8.11.3/bin/node]
> 14: 0x2a494a3042fd
> ```

Is working on every other banch and it seems to be an out of memory error not related in particular to that file.

**Comment by dleszcz** [comment]
@carmenfan Can you check if searching works well?

**Comment by dleszcz** [comment]
> Looks ok other than this bug:
> 
> If the search term matches both the project name and one of the model name, it's only showing the model that matched the search term instead of all the models within the matched project.
> 
> E.g. see below. "Atkins test" within "DGN Test" matches the search term "test", so it's only showing "Atkins test" when it should be showing all models within "DGNTest" as DGNTest also matches the term.
> 

Done :)

**Comment by carmenfan** [comment]
@dleszcz The search looks ok, but I don't think we can merge this without solving the OOM problem on yarn build... 😆

**Comment by dleszcz** [comment]
> @dleszcz The search looks ok, but I don't think we can merge this without solving the OOM problem on yarn build... 😆

Sure! it's weird :/ I'll check what's wrong with this

**Comment by dleszcz** [comment]
@carmenfan Fixed :)

**Pull request merged**
