### PR TITLE
ISSUE #2210 run run_app script to start

### LINKED ISSUE #2210: Update docker image to use /run/run_app script to start node
### Description

Carmen requested the docker image be updated to use the /run/run_app script when starting node to ensure any changes are carried through automatically.

### Tasks

- [ ] Update init.sh

### PR DESCRIPTION
**Pull request by keifgwinn**
This fixes #2210 

#### Description
Updated init.sh to start using the ./run/run_app script to start  node

#### Test cases
test container should start

### CODE REVIEW

**Comment by keifgwinn** [comment]
https://issue-2210.dev.3drepo.io/login is working

**Review by carmenfan — APPROVED** [review]

**Pull request merged**
